import type { HistoricalDataset } from "@/modules/football-data/historical";
import type { BacktestPrediction } from "@/modules/football-backtesting/domain";
import { runHistoricalBacktest } from "@/modules/football-backtesting/engine";
import { createHistoricalV2MatchIntelligence } from "./engine";
import { historicalV2Candidates, type HistoricalV2Parameters } from "./config";
import { createHistoricalV21MatchIntelligence, historicalV21Candidates, type HistoricalV21Parameters } from "./calibration";

const average = (values: number[]) => values.length ? values.reduce((sum, value) => sum + value, 0) / values.length : null;
export function temporalPartition(predictions: BacktestPrediction[], developmentShare = .7) { const sorted = [...predictions].sort((a, b) => a.fixture.kickoffAt.localeCompare(b.fixture.kickoffAt) || a.fixture.providerFixtureId.localeCompare(b.fixture.providerFixtureId)), cutoff = Math.floor(sorted.length * developmentShare); return { development: sorted.slice(0, cutoff), validation: sorted.slice(cutoff) }; }
export function calibrationPartition(predictions: BacktestPrediction[]) { const sorted = [...predictions].sort((a, b) => a.fixture.kickoffAt.localeCompare(b.fixture.kickoffAt) || a.fixture.providerFixtureId.localeCompare(b.fixture.providerFixtureId)), developmentEnd = Math.floor(sorted.length * .55), calibrationEnd = Math.floor(sorted.length * .7); return { development: sorted.slice(0, developmentEnd), calibration: sorted.slice(developmentEnd, calibrationEnd), lockedReference: sorted.slice(calibrationEnd) }; }
export function predictionMetrics(predictions: BacktestPrediction[]) { const correct = predictions.filter((item) => item.correct).length, actualDraws = predictions.filter((item) => item.actualOutcome === "draw").length, predictedDraws = predictions.filter((item) => item.predictedOutcome === "draw").length, correctDraws = predictions.filter((item) => item.actualOutcome === "draw" && item.predictedOutcome === "draw").length, precision = predictedDraws ? correctDraws / predictedDraws : null, recall = actualDraws ? correctDraws / actualDraws : null; return { predictions: predictions.length, accuracy: predictions.length ? correct / predictions.length : null, brier: average(predictions.map((p) => (p.probabilities.homeWin - Number(p.actualOutcome === "home")) ** 2 + (p.probabilities.draw - Number(p.actualOutcome === "draw")) ** 2 + (p.probabilities.awayWin - Number(p.actualOutcome === "away")) ** 2)), logLoss: average(predictions.map((p) => -Math.log(Math.max(1e-12, p.actualOutcome === "home" ? p.probabilities.homeWin : p.actualOutcome === "draw" ? p.probabilities.draw : p.probabilities.awayWin)))), actualDraws, predictedDraws, correctDraws, drawPrecision: precision, drawRecall: recall, drawF1: precision !== null && recall !== null && precision + recall ? 2 * precision * recall / (precision + recall) : null }; }
function predictionsFor(datasets: HistoricalDataset[], parameters: HistoricalV2Parameters) { return datasets.flatMap((dataset) => temporalPartition(runHistoricalBacktest(dataset, {}, (input) => createHistoricalV2MatchIntelligence(input, parameters)).predictions).development); }
export function searchHistoricalV2Development(datasets: HistoricalDataset[]) { const results = historicalV2Candidates.map((parameters) => ({ parameters, metrics: predictionMetrics(predictionsFor(datasets, parameters)) })).sort((a, b) => (a.metrics.brier ?? Infinity) - (b.metrics.brier ?? Infinity) || (a.metrics.logLoss ?? Infinity) - (b.metrics.logLoss ?? Infinity) || (b.metrics.drawF1 ?? 0) - (a.metrics.drawF1 ?? 0)); return { candidatesEvaluated: results.length, selected: results[0], results }; }

function calibrationPredictions(datasets: HistoricalDataset[], parameters: HistoricalV21Parameters) { return datasets.flatMap((dataset) => { const manifest = calibrationPartition(runHistoricalBacktest(dataset).predictions), calibrationIds = new Set(manifest.calibration.map((item) => item.fixture.providerFixtureId)), lockedIds = new Set(manifest.lockedReference.map((item) => item.fixture.providerFixtureId)), researchDataset = { ...dataset, fixtures: dataset.fixtures.filter((fixture) => !lockedIds.has(fixture.providerFixtureId)) }; return runHistoricalBacktest(researchDataset, {}, (input) => createHistoricalV21MatchIntelligence(input, parameters)).predictions.filter((item) => calibrationIds.has(item.fixture.providerFixtureId)); }); }
export function searchHistoricalV21Calibration(datasets: HistoricalDataset[]) { const results = historicalV21Candidates.map((parameters) => ({ parameters, metrics: predictionMetrics(calibrationPredictions(datasets, parameters)) })).sort((a, b) => (a.metrics.brier ?? Infinity) - (b.metrics.brier ?? Infinity) || (a.metrics.logLoss ?? Infinity) - (b.metrics.logLoss ?? Infinity) || (b.metrics.accuracy ?? 0) - (a.metrics.accuracy ?? 0) || (b.metrics.drawF1 ?? 0) - (a.metrics.drawF1 ?? 0)); return { candidatesEvaluated: results.length, selected: results[0], results }; }
