import "tsx/esm";
import assert from "node:assert/strict";
import test from "node:test";

const { ACTIVE_LEAGUE_CANDIDATES, verifyCandidateIdentity, windowDates, eligibleFutureFixtures, previousCompletedSeason, buildInMemoryShadowSource } = await import("../modules/football-intelligence/active-league-zero-write.ts");
const { ApiFootballProvider } = await import("../modules/football-data/api-football-provider.ts");
const { runShadowPredictionPipeline, MemoryShadowPredictionRepository, MemoryShadowRunRepository } = await import("../modules/football-intelligence/shadow-pipeline/index.ts");

const now = "2026-08-10T12:00:00.000Z";
const metadata = (overrides = {}) => ({ providerId: "113", name: "Allsvenskan", country: "Sweden", type: "League", seasons: [{ year: "2025", start: "2025-03-29", end: "2025-11-30", current: false }, { year: "2026", start: "2026-03-28", end: "2026-11-29", current: true }], ...overrides });
const normalizedFixture = (overrides = {}) => ({ providerId: "9001", competitionProviderId: "113", homeTeamProviderId: "1", awayTeamProviderId: "2", kickoffAt: "2026-08-11T18:00:00.000Z", status: "scheduled", homeScore: null, awayScore: null, ...overrides });

test("approved active-league candidates are deterministic and ordered", () => assert.deepEqual(ACTIVE_LEAGUE_CANDIDATES.map((item) => item.country), ["Sweden", "Norway", "Finland", "Japan", "China"]));
test("exact identity, domestic league type and current season are required", () => { const candidate = ACTIVE_LEAGUE_CANDIDATES[0]; assert.equal(verifyCandidateIdentity(candidate, [metadata()], now).ok, true); assert.equal(verifyCandidateIdentity(candidate, [metadata({ type: "Cup" })], now).ok, false); assert.equal(verifyCandidateIdentity(candidate, [metadata({ country: "Norway" })], now).ok, false); assert.equal(verifyCandidateIdentity(candidate, [metadata(), metadata({ providerId: "999" })], now).reason, "AMBIGUOUS_PROVIDER_IDENTITY"); assert.equal(verifyCandidateIdentity(candidate, [metadata({ seasons: [{ year: "2026", start: "2026-01-01", end: "2026-12-31", current: false }] })], now).reason, "CURRENT_SEASON_NOT_FOUND"); });
test("current season is dynamically extracted and must contain execution date", () => { const result = verifyCandidateIdentity(ACTIVE_LEAGUE_CANDIDATES[0], [metadata()], now); assert.equal(result.ok && result.season.year, "2026"); assert.equal(verifyCandidateIdentity(ACTIVE_LEAGUE_CANDIDATES[0], [metadata({ seasons: [{ year: "2026", start: "2026-09-01", end: "2027-01-01", current: true }] })], now).reason, "CURRENT_DATE_OUTSIDE_PROVIDER_SEASON"); });
test("72h and defensive 168h windows are bounded in UTC", () => { assert.equal(windowDates(now, 72).end, "2026-08-13T12:00:00.000Z"); assert.equal(windowDates(now, 168).end, "2026-08-17T12:00:00.000Z"); });
test("future fixture gate rejects same-time, later-than-168h, bad status, mismatches and unresolved teams", () => { const ids = new Set(["1", "2"]), end = windowDates(now, 168).end; assert.equal(eligibleFutureFixtures([normalizedFixture()], "113", "2026", ids, now, end).length, 1); for (const fixture of [normalizedFixture({ kickoffAt: now }), normalizedFixture({ kickoffAt: "2026-08-18T12:00:00.000Z" }), normalizedFixture({ status: "finished" }), normalizedFixture({ competitionProviderId: "114" }), normalizedFixture({ awayTeamProviderId: "3" }), normalizedFixture({ awayTeamProviderId: "1" })]) assert.equal(eligibleFutureFixtures([fixture], "113", "2026", ids, now, end).length, 0); });
test("immediately preceding completed season is derived, never guessed", () => { assert.equal(previousCompletedSeason(metadata(), "2026", now)?.year, "2025"); assert.equal(previousCompletedSeason(metadata({ seasons: metadata().seasons.filter((item) => item.current) }), "2026", now), null); });
test("provider discovery uses country plus current only and exposes safe request audit", async () => { const audits = [], urls = [], provider = new ApiFootballProvider({ apiKey: "unit-test-placeholder", enabled: true, onRequest: (audit) => audits.push(audit), transport: async (input) => { urls.push(String(input)); return new Response(JSON.stringify({ response: [{ league: { id: 113, name: "Allsvenskan", type: "League" }, country: { name: "Sweden" }, seasons: metadata().seasons }], errors: [], paging: { current: 1, total: 1 } }), { status: 200, headers: { "x-ratelimit-requests-remaining": "42" } }); } }); const rows = await provider.discoverCurrentCompetitions("Sweden"); assert.equal(rows[0].providerId, "113"); assert.match(urls[0], /leagues\?country=Sweden&current=true$/); assert.doesNotMatch(urls[0], /search|season=/); assert.deepEqual(audits[0], { path: "leagues", parameters: { country: "Sweden", current: "true" }, httpStatus: 200, recordsReturned: 1, rateLimitRemaining: 42 }); });
test("provider methods never call predictions, odds or unrelated endpoints", async () => { const urls = [], provider = new ApiFootballProvider({ apiKey: "unit-test-placeholder", enabled: true, transport: async (input) => { const url = String(input); urls.push(url); const response = url.includes("/teams") ? [{ team: { id: 1, name: "A" } }, { team: { id: 2, name: "B" } }] : []; return new Response(JSON.stringify({ response, errors: [], paging: { current: 1, total: 1 } }), { status: 200 }); } }); await provider.fetchCompetitionFixtures(metadata(), "2026", "2026-08-10", "2026-08-13"); await provider.fetchCompetitionTeams(metadata(), "2026"); await provider.fetchSeasonFixtures(metadata(), "2025"); assert.equal(urls.length, 3); assert.ok(urls.every((url) => !/predictions|odds|standings|statistics|injuries|lineups/.test(url))); });
test("in-memory source preserves provider identities and writes nothing in dry run", async () => { const teams = [{ providerId: "1", competitionProviderId: "113", name: "A", shortName: null, logoUrl: null, country: "Sweden" }, { providerId: "2", competitionProviderId: "113", name: "B", shortName: null, logoUrl: null, country: "Sweden" }], history = []; for (let i = 0; i < 10; i++) history.push(normalizedFixture({ providerId: String(100 + i), kickoffAt: `2026-07-${String(i + 1).padStart(2, "0")}T12:00:00.000Z`, status: "finished", homeScore: i % 3, awayScore: (i + 1) % 2 })); const source = buildInMemoryShadowSource(ACTIVE_LEAGUE_CANDIDATES[0], metadata(), "2026", teams, history, [normalizedFixture()]), predictions = new MemoryShadowPredictionRepository(), runs = new MemoryShadowRunRepository(); const report = await runShadowPredictionPipeline([source], { predictions, runs }, { enabled: true, providerCallsEnabled: false, publicPublishingEnabled: false, globallyPaused: false, horizonHours: 168, maxProviderRequestsPerRun: 0, maxFixtureRefreshAgeMinutes: 180 }, [source.supportedCompetition], { now, dryRun: true, persist: false, providerRefresh: false, horizonHours: 168 }); assert.equal(report.databaseWrites, 0); assert.equal((await predictions.list()).length, 0); assert.equal((await runs.list()).length, 0); assert.equal(report.publications, 0); assert.equal(report.notifications, 0); });
test("zero-write evaluation is deterministic under replay and reordered history", () => { const teams = [{ providerId: "1", competitionProviderId: "113", name: "A", shortName: null, logoUrl: null, country: "Sweden" }, { providerId: "2", competitionProviderId: "113", name: "B", shortName: null, logoUrl: null, country: "Sweden" }], history = Array.from({ length: 12 }, (_, i) => normalizedFixture({ providerId: String(200 + i), kickoffAt: `2026-06-${String(i + 1).padStart(2, "0")}T12:00:00.000Z`, status: "finished", homeScore: i % 2, awayScore: (i + 1) % 2 })); const a = buildInMemoryShadowSource(ACTIVE_LEAGUE_CANDIDATES[0], metadata(), "2026", teams, history, [normalizedFixture()]), b = buildInMemoryShadowSource(ACTIVE_LEAGUE_CANDIDATES[0], metadata(), "2026", teams, [...history].reverse(), [normalizedFixture()]); assert.deepEqual(a.dataset.fixtures.map((x) => x.providerFixtureId).sort(), b.dataset.fixtures.map((x) => x.providerFixtureId).sort()); });

const portfolioSource = (league, fixtureCount) => { const competition = metadata({ providerId: String(league), name: `League ${league}`, country: `Country ${league}` }), candidate = { priority: league, id: `league-${league}`, productName: `League ${league}`, providerName: `League ${league}`, country: `Country ${league}` }, teams = [{ providerId: `${league}01`, competitionProviderId: String(league), name: `A${league}`, shortName: null, logoUrl: null, country: candidate.country }, { providerId: `${league}02`, competitionProviderId: String(league), name: `B${league}`, shortName: null, logoUrl: null, country: candidate.country }], history = Array.from({ length: 12 }, (_, i) => normalizedFixture({ providerId: `${league}8${i}`, competitionProviderId: String(league), homeTeamProviderId: teams[0].providerId, awayTeamProviderId: teams[1].providerId, kickoffAt: `2026-06-${String(i + 1).padStart(2, "0")}T12:00:00.000Z`, status: "finished", homeScore: i % 3, awayScore: (i + 1) % 2 })), upcoming = Array.from({ length: fixtureCount }, (_, i) => normalizedFixture({ providerId: `${league}9${i}`, competitionProviderId: String(league), homeTeamProviderId: teams[0].providerId, awayTeamProviderId: teams[1].providerId, kickoffAt: "2026-08-11T18:00:00.000Z" })); return buildInMemoryShadowSource(candidate, competition, "2026", teams, history, upcoming); };
const portfolioRun = (sources, minimumLeadMinutes = 120, executionNow = now) => runShadowPredictionPipeline(sources, { predictions: new MemoryShadowPredictionRepository(), runs: new MemoryShadowRunRepository() }, { enabled: true, providerCallsEnabled: false, publicPublishingEnabled: false, globallyPaused: false, horizonHours: 168, maxProviderRequestsPerRun: 0, maxFixtureRefreshAgeMinutes: 180 }, sources.map((source) => source.supportedCompetition), { now: executionNow, dryRun: true, persist: false, horizonHours: 168, minimumLeadMinutes });

test("120-minute lead-time gate rejects 119 minutes and accepts exactly 120", async () => { const source = portfolioSource(301, 1); source.upcomingFixtures[0].kickoffAt = "2026-08-10T14:00:00.000Z"; const rejected = await portfolioRun([source], 120, "2026-08-10T12:01:00.000Z"), accepted = await portfolioRun([source], 120, "2026-08-10T12:00:00.000Z"); assert.equal(rejected.skips[0].reason, "FIXTURE_TOO_CLOSE_TO_KICKOFF"); assert.equal(accepted.fixturesEligible, 1); });
test("DAILY_GLOBAL ranking combines leagues and preserves frozen 0/1/2/4 quotas", async () => { for (const [total, expected] of [[4, 0], [5, 1], [10, 2], [20, 4]]) { const counts = [Math.ceil(total / 3), Math.floor(total / 3), total - Math.ceil(total / 3) - Math.floor(total / 3)], sources = counts.map((count, index) => portfolioSource(401 + index, count)), report = await portfolioRun(sources); assert.equal(report.fixturesEligible, total); assert.equal(report.topPicks, expected); assert.equal(new Set(report.records.map((row) => row.rankingDate)).size, 1); } });
test("multi-league output is invariant to league and fixture order", async () => { const sources = [portfolioSource(501, 2), portfolioSource(502, 2), portfolioSource(503, 2)], first = await portfolioRun(sources), second = await portfolioRun([...sources].reverse().map((source) => ({ ...source, upcomingFixtures: [...source.upcomingFixtures].reverse(), dataset: { ...source.dataset, fixtures: [...source.dataset.fixtures].reverse() } }))); const view = (report) => report.records.map((row) => [row.fixtureId, row.homeProbability, row.drawProbability, row.awayProbability, row.confidenceLabel, row.publishingTierCalculated, row.rankingPosition, row.isTopPickCalculated]).sort(); assert.deepEqual(view(first), view(second)); });
