import assert from "node:assert/strict";import{readFile}from"node:fs/promises";import test from"node:test";
const read=(path)=>readFile(new URL(`../${path}`,import.meta.url),"utf8");
test("Supabase auth provider satisfies the provider-neutral contract",async()=>{const source=await read("modules/account/providers.ts");for(const method of["getCurrentUser","getSession","signIn","signUp","signOut","requestPasswordReset","updatePassword"])assert.match(source,new RegExp(method));assert.match(source,/signInWithPassword/);assert.match(source,/resetPasswordForEmail/);assert.match(source,/onAuthStateChange/);assert.doesNotMatch(source,/service.role|SUPABASE_SERVICE/i)});
test("registration, login and recovery retain safe validation states",async()=>{const[forms,validation,redirects]=await Promise.all([read("components/auth-forms.tsx"),read("modules/account/validation.ts"),read("modules/account/redirects.ts")]);assert.match(validation,/Passwords do not match/);assert.match(validation,/at least 8 characters/);assert.match(forms,/confirmation-required/);assert.match(forms,/invalid login credentials/);assert.match(forms,/invalid or expired/);assert.match(redirects,/startsWith\("\/\/"\)/);assert.match(redirects,/fallback/)});
test("protected routes use server identity and trusted admin role",async()=>{for(const path of["app/dashboard/page.tsx","app/account/page.tsx","app/admin/page.tsx","app/admin/orders/page.tsx"]){const page=await read(path);assert.match(page,/requireServerUser/)}const server=await read("modules/account/server.ts");assert.match(server,/profile\?\.role/);assert.match(server,/user\.role !== "admin"/);assert.doesNotMatch(server,/localStorage|sessionStorage|searchParams.*role/)});
test("membership, report access and persisted allowance remain provider-neutral",async()=>{const[services,repositories,gate,migration]=await Promise.all([read("modules/account/services.ts"),read("modules/persistence/repositories.ts"),read("components/report-access-gate.tsx"),read("supabase/migrations/202608080001_batch_4b_auth_hardening.sql")]);assert.match(services,/member\.hasPremiumAccess/);assert.match(services,/alreadyViewed/);assert.match(gate,/recordView/);assert.match(repositories,/prediction_usage/);assert.match(repositories,/provider_fixture_id/);assert.match(migration,/unique index/);assert.match(migration,/revoke execute.*is_admin.*anon/i)});
test("profile updates expose display name only",async()=>{const repository=await read("modules/persistence/repositories.ts");const method=repository.slice(repository.indexOf("class SupabaseProfileRepository"),repository.indexOf("class SupabasePredictionUsageRepository"));assert.match(method,/display_name/);assert.doesNotMatch(method,/role:|account_status|membership|premium/)});
test("canonical URL configuration drives metadata and authentication redirects",async()=>{const[site,layout,home,providers,sitemap,robots,env]=await Promise.all([read("config/site.ts"),read("app/layout.tsx"),read("app/page.tsx"),read("modules/account/providers.ts"),read("app/sitemap.ts"),read("app/robots.ts"),read(".env.example")]);assert.match(site,/https:\/\/9jafootballai\.com\.ng/);assert.match(site,/http:\/\/localhost:3000/);assert.match(layout,/metadataBase: new URL\(siteUrl\)/);assert.match(home,/alternates:\{canonical:getSiteUrl\(\)\}/);assert.match(providers,/getAuthRedirectUrl/);assert.match(sitemap,/getSiteUrl/);assert.match(robots,/sitemap/);assert.match(env,/NEXT_PUBLIC_SITE_URL=https:\/\/9jafootballai\.com\.ng/)});
test("mock authentication requires explicit mock mode",async()=>{const composition=await read("modules/account/application.ts");assert.match(composition,/authConfig\.mode === "mock"/);assert.match(composition,/UnavailableAuthProvider/);assert.doesNotMatch(composition,/client \? new SupabaseAuthProvider\(client\) : new MockAuthProvider/)});
