import "tsx/esm";
import assert from "node:assert/strict";
import test from "node:test";

const { ApiFootballProvider } = await import("../modules/football-data/api-football-provider.ts");
const { footballCompetitions, historicalFootballCompetitionMappings } = await import("../config/football-data.ts");
const envelope = (response, status = 200, errors = []) => new Response(JSON.stringify({ response, errors, paging: { current: 1, total: 1 } }), { status, headers: { "content-type": "application/json" } });
const metadata = { league: { id: 179, name: "Premiership", type: "League" }, country: { name: "Scotland" }, seasons: [{ year: 2024, start: "2024-08-01", end: "2025-05-30", current: false }, { year: 2026, start: "2026-07-31", end: "2027-04-10", current: true }] };
const competition = { providerId: "179", name: "Premiership", country: "Scotland", type: "League", seasons: [{ year: "2026", start: "2026-07-31", end: "2027-04-10", current: true }] };
const teams = [{ team: { id: 247, name: "Celtic", code: "CEL", country: "Scotland" } }, { team: { id: 257, name: "Rangers", code: "RAN", country: "Scotland" } }];
const fixture = (overrides = {}) => ({ fixture: { id: 1001, date: "2026-08-11T18:00:00+00:00", status: { short: "NS" }, ...overrides.fixture }, league: { id: 179, name: "Premiership", country: "Scotland", season: 2026, ...overrides.league }, teams: { home: { id: 247, name: "Celtic" }, away: { id: 257, name: "Rangers" }, ...overrides.teams }, goals: { home: null, away: null } });

test("current-season metadata uses one exact league request and preserves provider current flag", async () => { let calls = 0, url = ""; const provider = new ApiFootballProvider({ apiKey: "test-placeholder-not-live", enabled: true, transport: async (input) => { calls++; url = String(input); return envelope([metadata]); } }), result = await provider.getCompetitionMetadata("179"); assert.equal(calls, 1); assert.match(url, /\/leagues\?id=179$/); assert.deepEqual(result.seasons.filter((season) => season.current), [{ year: "2026", start: "2026-07-31", end: "2027-04-10", current: true, coverage: { standings: false, statistics: false, injuries: false, predictions: false, odds: false } }]); assert.deepEqual([result.providerId, result.name, result.country, result.type], ["179", "Premiership", "Scotland", "League"]); });
test("current mapping is 2026 while historical development mapping remains 2024", () => { const current = footballCompetitions.find((item) => item.id === "scottish-premiership"); assert.deepEqual([current.providerId, current.currentSeason, current.enabled], ["179", "2026", true]); assert.ok(historicalFootballCompetitionMappings.some((item) => item.providerId === "179" && item.season === "2024" && item.purpose === "development-history")); });
test("bounded fixture acquisition calls only teams and fixtures once each", async () => { const urls = [], provider = new ApiFootballProvider({ apiKey: "test-placeholder-not-live", enabled: true, transport: async (input) => { const url = String(input); urls.push(url); return envelope(url.includes("/teams") ? teams : [fixture()]); } }), result = await provider.fetchUpcomingCompetitionWindow(competition, "2026", "2026-08-10", "2026-08-17"); assert.equal(result.requestCount, 2); assert.equal(result.fixtures[0].kickoffAt, "2026-08-11T18:00:00.000Z"); assert.deepEqual(result.teams.map((team) => team.providerId), ["247", "257"]); assert.equal(urls.length, 2); assert.ok(urls.some((url) => /\/teams\?league=179&season=2026/.test(url))); assert.ok(urls.some((url) => /\/fixtures\?league=179&season=2026&from=2026-08-10&to=2026-08-17/.test(url))); assert.ok(urls.every((url) => !/predictions|odds|standings|statistics|injuries|lineups/.test(url))); });
test("competition, season and status mismatches fail closed", async () => { for (const bad of [fixture({ league: { id: 180 } }), fixture({ league: { season: 2025 } }), fixture({ fixture: { status: { short: "FT" } } })]) { let call = 0; const provider = new ApiFootballProvider({ apiKey: "test-placeholder-not-live", enabled: true, transport: async () => envelope(call++ === 0 ? teams : [bad]) }); await assert.rejects(() => provider.fetchUpcomingCompetitionWindow(competition, "2026", "2026-08-10", "2026-08-17"), /competition or season identity|status allowlist/); } });
test("invalid date windows fail before transport", async () => { let calls = 0; const provider = new ApiFootballProvider({ apiKey: "test-placeholder-not-live", enabled: true, transport: async () => { calls++; return envelope([]); } }); await assert.rejects(() => provider.fetchUpcomingCompetitionWindow(competition, "2026", "2026-08-17", "2026-08-10"), (error) => error?.providerCategory === "invalid-request" && error?.safeDiagnostic === "Fixture window dates were invalid."); assert.equal(calls, 0); });
test("empty fixture response is valid and never triggers pagination or retry", async () => { let calls = 0; const provider = new ApiFootballProvider({ apiKey: "test-placeholder-not-live", enabled: true, transport: async (input) => { calls++; return envelope(String(input).includes("/teams") ? teams : []); } }), result = await provider.fetchUpcomingCompetitionWindow(competition, "2026", "2026-08-10", "2026-08-17"); assert.equal(calls, 2); assert.deepEqual(result.fixtures, []); });
