import "tsx/esm";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const shadow = await import("../modules/football-intelligence/shadow-pipeline/index.ts");
const migration = await readFile(new URL("../supabase/migrations/202608100002_batch_4h18_settlement_integrity.sql", import.meta.url), "utf8");

const prediction = (overrides = {}) => ({
  id: "p1", runId: "r1", fixtureId: "fixture-db", providerFixtureId: "100", competitionId: "competition-db", providerCompetitionId: "113", season: "2026", homeTeamId: "home-db", awayTeamId: "away-db",
  kickoffAt: "2026-08-14T15:00:00Z", predictionCreatedAt: "2026-08-10T12:00:00Z", evidenceCutoffAt: "2026-08-09T15:00:00Z", selectedOutcome: "home", homeProbability: .6, drawProbability: .25, awayProbability: .15,
  methodologyKey: "historical-v1", methodologyVersion: "historical-v1-frozen-4h", confidenceVersion: "compact-composite-4h9", confidenceScoreInternal: .8, confidenceLabel: "STRONG", publishingTierCalculated: "TOP_PICK", publishingPolicyVersion: "selective-publishing-4h14", rankingScope: "DAILY_GLOBAL", rankingDate: "2026-08-14", rankingPosition: 1, eligiblePopulationSize: 10, isTopPickCalculated: true, operationalPublicationState: "SHADOW_ONLY", shadowMode: true, settlementStatus: "PENDING", actualHomeGoals: null, actualAwayGoals: null, actualOutcome: null, predictionCorrect: null, settledAt: null, methodologySnapshot: { methodology: "historical-v1-frozen-4h", confidence: "compact-composite-4h9", publishingPolicy: "selective-publishing-4h14" }, createdAt: "2026-08-10T12:00:00Z", updatedAt: "2026-08-10T12:00:00Z", ...overrides,
});
const result = (overrides = {}) => ({ providerFixtureId: "100", providerCompetitionId: "113", season: "2026", homeTeamId: "home-db", awayTeamId: "away-db", kickoffAt: "2026-08-14T15:00:00Z", status: "finished", homeScore: 2, awayScore: 1, ...overrides });
const repositoryWith = async (row = prediction()) => { const repository = new shadow.MemoryShadowPredictionRepository(); await repository.insert(row); return repository; };
const settle = async (row = prediction(), fixture = result()) => { const repository = await repositoryWith(row); return shadow.settleShadowPrediction(repository, row, fixture, "2026-08-14T17:00:00Z"); };

for (const [name, scores, expected] of [["home", [2, 1], "home"], ["draw", [1, 1], "draw"], ["away", [0, 2], "away"]]) test(`completed ${name} result settles`, async () => { const settled = await settle(prediction({ selectedOutcome: expected }), result({ homeScore: scores[0], awayScore: scores[1] })); assert.equal(settled.record.actualOutcome, expected); assert.equal(settled.record.predictionCorrect, true); });
test("incorrect prediction is retained as incorrect", async () => { const { record } = await settle(prediction({ selectedOutcome: "away" })); assert.equal(record.predictionCorrect, false); assert.equal(record.selectedOutcome, "away"); });
for (const [provider, state] of [["postponed", "POSTPONED"], ["cancelled", "CANCELLED"], ["abandoned", "ABANDONED"], ["void", "VOID"]]) test(`${provider} is non-scoring`, async () => { const { record } = await settle(prediction(), result({ status: provider, homeScore: null, awayScore: null })); assert.equal(record.settlementStatus, state); assert.equal(record.predictionCorrect, null); assert.equal(record.actualOutcome, null); });
for (const status of ["scheduled", "live", "halftime", "suspended"]) test(`${status} remains unsettled`, async () => { await assert.rejects(() => settle(prediction(), result({ status, homeScore: null, awayScore: null })), /FIXTURE_NOT_FINAL/); });
test("missing final score is rejected", async () => { await assert.rejects(() => settle(prediction(), result({ homeScore: null })), /FINAL_SCORE_MISSING/); });
for (const [field, value, error] of [["providerFixtureId", "x", "MISMATCHED_FIXTURE_ID"], ["providerCompetitionId", "x", "MISMATCHED_COMPETITION"], ["season", "2025", "MISMATCHED_SEASON"], ["homeTeamId", "x", "MISMATCHED_TEAMS"], ["kickoffAt", "2026-08-14T16:00:00Z", "MISMATCHED_KICKOFF"]]) test(`${field} identity mismatch is rejected`, async () => { await assert.rejects(() => settle(prediction(), result({ [field]: value })), new RegExp(error)); });
test("SHA-256 fingerprint covers immutable identity and model fields", () => { const row = prediction(), fingerprint = shadow.immutablePredictionFingerprint(row); assert.match(fingerprint, /^[a-f0-9]{64}$/); assert.notEqual(fingerprint, shadow.immutablePredictionFingerprint({ ...row, homeProbability: .59 })); assert.notEqual(fingerprint, shadow.immutablePredictionFingerprint({ ...row, fixtureId: "changed" })); });
test("fingerprint canonicalizes equivalent UTC timestamp serializations", () => { const row = prediction(), normalized = { ...row, kickoffAt: "2026-08-14T15:00:00.000+00:00", predictionCreatedAt: "2026-08-10T12:00:00.000+00:00", evidenceCutoffAt: "2026-08-09T15:00:00.000+00:00" }; assert.equal(shadow.immutablePredictionFingerprint(row), shadow.immutablePredictionFingerprint(normalized)); });
test("repository mutation of immutable evidence is detected", async () => { const row = prediction(), repository = await repositoryWith(row), original = repository.updateSettlement.bind(repository); repository.updateSettlement = async (...args) => ({ ...(await original(...args)), confidenceLabel: "LOW" }); await assert.rejects(() => shadow.settleShadowPrediction(repository, row, result(), "2026-08-14T17:00:00Z"), /CRITICAL_IMMUTABILITY_FAILURE/); });
test("identical repeat is idempotent and conflicting repeat is blocked", async () => { const row = prediction(), repository = await repositoryWith(row), first = await shadow.settleShadowPrediction(repository, row, result(), "2026-08-14T17:00:00Z"), identical = await shadow.settleShadowPrediction(repository, first.record, result(), "2026-08-14T18:00:00Z"); assert.equal(identical.disposition, "ALREADY_SETTLED_IDENTICAL"); await assert.rejects(() => shadow.settleShadowPrediction(repository, first.record, result({ homeScore: 0, awayScore: 1 }), "2026-08-14T18:00:00Z"), /SETTLED_RESULT_CONFLICT/); });
test("metrics exclude pending and non-scoring states", () => { const rows = [prediction(), prediction({ id: "p2", settlementStatus: "CANCELLED" }), prediction({ id: "p3", settlementStatus: "SETTLED", actualOutcome: "home", predictionCorrect: true, actualHomeGoals: 1, actualAwayGoals: 0 })], metrics = shadow.calculateForwardShadowMetrics(rows); assert.equal(metrics.overall.predictions, 3); assert.equal(metrics.overall.settled, 1); assert.equal(metrics.overall.correct, 1); assert.equal(metrics.overall.accuracy, 1); assert.equal(metrics.overall.sampleLabel, "VERY_LOW_SAMPLE"); });
test("zero denominator is N/A-compatible null", () => { const metrics = shadow.shadowMetricGroup([prediction()]); assert.equal(metrics.accuracy, null); assert.equal(metrics.brierScore, null); assert.equal(metrics.logLoss, null); assert.equal(metrics.wilson95, null); });
test("Brier, log loss, tier, confidence, competition, outcome and date groups use frozen vectors", () => { const row = prediction({ settlementStatus: "SETTLED", actualOutcome: "home", predictionCorrect: true, actualHomeGoals: 2, actualAwayGoals: 1 }), metrics = shadow.calculateForwardShadowMetrics([row]); assert.ok(Math.abs(metrics.overall.brierScore - .245) < 1e-12); assert.ok(Math.abs(metrics.overall.logLoss + Math.log(.6)) < 1e-12); assert.equal(metrics.byTier.TOP_PICK.correct, 1); assert.equal(metrics.byConfidence.STRONG.correct, 1); assert.equal(metrics.byCompetition["competition-db"].correct, 1); assert.equal(metrics.bySelection.home.correct, 1); assert.equal(metrics.byFixtureDateUtc["2026-08-14"].correct, 1); });
test("migration is additive, private and protects immutable evidence", () => { assert.match(migration, /protect_shadow_prediction_evidence/); assert.match(migration, /SHADOW_PREDICTION_IMMUTABLE_FIELD_CHANGE/); assert.match(migration, /ABANDONED/); assert.match(migration, /revoke all .* public, anon, authenticated/); assert.doesNotMatch(migration, /delete from|truncate|drop table/i); });
test("settlement source has no provider prediction, odds, notification, OpenAI or generation dependency", async () => { const source = await readFile(new URL("../modules/football-intelligence/shadow-pipeline/settlement.ts", import.meta.url), "utf8"); assert.doesNotMatch(source, /predictions\?|odds\?|OpenAI|sendEmail|telegram|createHistoricalMatchIntelligence|evaluateSelectivePublishing/); });
