import "tsx/esm";
import assert from "node:assert/strict";
import test from "node:test";

const readiness = await import("../modules/football-intelligence/rolling-readiness.ts");
const shadow = await import("../modules/football-intelligence/shadow-pipeline/index.ts");
const now = "2026-08-10T12:00:00.000Z";
const teams = Array.from({ length: 10 }, (_, index) => ({ providerId: String(index + 1), competitionProviderId: "39", name: `Team ${index + 1}`, shortName: null, logoUrl: null, country: "England" }));
const fixture = (overrides = {}) => ({ providerId: "f1", competitionProviderId: "39", homeTeamProviderId: "1", awayTeamProviderId: "2", kickoffAt: "2026-08-17T11:59:00.000Z", status: "scheduled", homeScore: null, awayScore: null, ...overrides });
const evidence = new Map(teams.map((team) => [team.providerId, 10])), priorIds = new Set(teams.map((team) => team.providerId));
const audit = (row, options = {}) => readiness.auditOpeningFixtures({ fixtures: [row], currentTeams: teams, priorTopFlightTeamIds: options.priorIds ?? priorIds, priorEvidenceCounts: options.evidence ?? evidence, now })[0];

test("fixture outside 168 hours is rejected", () => assert.equal(readiness.classifyFixtureWindow(fixture({ kickoffAt: "2026-08-17T12:01:00Z" }), now), "OUTSIDE_168H"));
test("fixture at the 168-hour boundary is accepted", () => assert.equal(readiness.classifyFixtureWindow(fixture({ kickoffAt: "2026-08-17T12:00:00Z" }), now), "INSIDE_168H"));
test("started fixture is rejected", () => assert.equal(readiness.classifyFixtureWindow(fixture({ kickoffAt: now }), now), "ALREADY_STARTED_OR_INVALID"));
for (const status of ["postponed", "cancelled", "abandoned"]) test(`${status} fixture is unsafe`, () => assert.equal(readiness.classifyFixtureWindow(fixture({ status }), now), "UNSAFE_STATUS"));
test("valid prior-season evidence qualifies a new-season fixture", () => { const result = audit(fixture()); assert.equal(result.evidenceProvenance, "SAME_LEAGUE_PRIOR_SEASON"); assert.equal(result.eligibilityReason, "ELIGIBLE"); });
test("promoted club is explicitly tagged and safely skipped without comparable evidence", () => { const result = audit(fixture(), { priorIds: new Set(teams.slice(1).map((team) => team.providerId)) }); assert.equal(result.promotedClubInvolved, true); assert.equal(result.evidenceProvenance, "PROMOTED_FROM_LOWER_DIVISION"); assert.equal(result.eligibilityReason, "INSUFFICIENT_COMPARABLE_HISTORY"); });
test("insufficient prior-season evidence is skipped", () => { const result = audit(fixture(), { evidence: new Map([["1", 4], ["2", 10]]) }); assert.equal(result.eligibilityReason, "INSUFFICIENT_COMPARABLE_HISTORY"); });
test("entry timestamp is derived exactly from fixture kickoff", () => assert.equal(audit(fixture()).eligibilityEntryAt, "2026-08-10T11:59:00.000Z"));
test("upcoming league shape supports coming-soon and generating states", () => { const inside = audit(fixture()), ready = readiness.toUpcomingMajorLeague({ providerCompetitionId: "39", name: "Premier League", country: "England", season: "2026", fixtures: [inside] }), blocked = readiness.toUpcomingMajorLeague({ providerCompetitionId: "39", name: "Premier League", country: "England", season: "2026", fixtures: [{ ...inside, eligibilityReason: "INSUFFICIENT_COMPARABLE_HISTORY" }] }); assert.equal(ready.status, "PREDICTIONS_GENERATING"); assert.equal(blocked.status, "COMING_SOON"); });
test("season phases are metadata only", () => assert.deepEqual([readiness.seasonPhase(0), readiness.seasonPhase(1), readiness.seasonPhase(5)], ["OPENING", "EARLY", "ESTABLISHED"]));

const historicalTeams = teams.map((team) => ({ id: team.providerId, providerId: team.providerId, name: team.name }));
const historical = Array.from({ length: 60 }, (_, index) => ({ id: `h${index}`, providerFixtureId: `h${index}`, kickoffAt: new Date(Date.parse("2025-08-01T12:00:00Z") + index * 86_400_000).toISOString(), status: "finished", homeTeamId: String(index % 10 + 1), awayTeamId: String((index + 1) % 10 + 1), homeScore: index % 3, awayScore: (index + 1) % 2 }));
const upcoming = { id: "f1", providerFixtureId: "f1", kickoffAt: "2026-08-11T15:00:00Z", status: "scheduled", homeTeamId: "1", awayTeamId: "2", homeScore: null, awayScore: null };
const supported = { internalCompetitionId: "premier-league", providerCompetitionId: "39", name: "Premier League", country: "England", season: "2026", enabled: true };
const source = { dataset: { competition: { id: "c1", providerId: "39", name: "Premier League", country: "England", season: "2026" }, teams: historicalTeams, fixtures: historical }, upcomingFixtures: [upcoming], supportedCompetition: supported };
const controls = { enabled: true, providerCallsEnabled: false, publicPublishingEnabled: false, globallyPaused: false, horizonHours: 168, maxProviderRequestsPerRun: 0, maxFixtureRefreshAgeMinutes: 180 };
test("already-frozen fixture is skipped before generation", async () => { const repositories = { predictions: new shadow.MemoryShadowPredictionRepository(), runs: new shadow.MemoryShadowRunRepository() }, result = await readiness.runRollingShadowWorker({ lockKey: "frozen", sources: [source], repositories, controls, allowlist: [supported], frozenProviderFixtureIds: new Set(["f1"]), now }); assert.equal(result.report.fixturesFound, 0); });
test("zero-write worker creates no prediction or run rows", async () => { const repositories = { predictions: new shadow.MemoryShadowPredictionRepository(), runs: new shadow.MemoryShadowRunRepository() }, result = await readiness.runRollingShadowWorker({ lockKey: "dry", sources: [source], repositories, controls, allowlist: [supported], frozenProviderFixtureIds: new Set(), now }); assert.equal(result.report.databaseWrites, 0); assert.equal((await repositories.predictions.list()).length, 0); assert.equal((await repositories.runs.list()).length, 0); });
test("repeated dry worker remains idempotent", async () => { const repositories = { predictions: new shadow.MemoryShadowPredictionRepository(), runs: new shadow.MemoryShadowRunRepository() }, options = { lockKey: "repeat", sources: [source], repositories, controls, allowlist: [supported], frozenProviderFixtureIds: new Set(), now }; await readiness.runRollingShadowWorker(options); await readiness.runRollingShadowWorker(options); assert.equal((await repositories.predictions.list()).length, 0); });
test("overlapping worker execution fails closed", async () => { const predictions = new shadow.MemoryShadowPredictionRepository(), original = predictions.findByIdentity.bind(predictions); predictions.findByIdentity = async (...args) => { await new Promise((resolve) => setTimeout(resolve, 20)); return original(...args); }; const options = { lockKey: "overlap", sources: [source], repositories: { predictions, runs: new shadow.MemoryShadowRunRepository() }, controls, allowlist: [supported], frozenProviderFixtureIds: new Set(), now }, first = readiness.runRollingShadowWorker(options), second = await readiness.runRollingShadowWorker(options); assert.equal(second.status, "OVERLAPPING_RUN_SKIPPED"); await first; });
test("settlement-shaped target fields cannot influence rolling generation", async () => { const repositories = () => ({ predictions: new shadow.MemoryShadowPredictionRepository(), runs: new shadow.MemoryShadowRunRepository() }), options = (target) => ({ lockKey: target.homeScore === null ? "clean" : "result", sources: [{ ...source, upcomingFixtures: [target] }], repositories: repositories(), controls, allowlist: [supported], frozenProviderFixtureIds: new Set(), now }), clean = await readiness.runRollingShadowWorker(options(upcoming)), result = await readiness.runRollingShadowWorker(options({ ...upcoming, homeScore: 99, awayScore: 0 })); assert.deepEqual(clean.report.records.map((row) => [row.selectedOutcome, row.homeProbability, row.confidenceLabel, row.publishingTierCalculated]), result.report.records.map((row) => [row.selectedOutcome, row.homeProbability, row.confidenceLabel, row.publishingTierCalculated])); });
