import assert from"node:assert/strict";import{readFile}from"node:fs/promises";import test from"node:test";import{BusinessSetupCheckoutService,createPaymentReference}from"../modules/billing/b2b-checkout.ts";import{InMemoryCheckoutRepository}from"../modules/billing/b2b-checkout-repository.ts";
const read=path=>readFile(new URL(`../${path}`,import.meta.url),"utf8");
class Provider{constructor(patch={}){this.id="paystack";this.environment="test";this.patch=patch;this.calls=0;this.records=new Map()}async initialize(request){this.calls++;const result={providerId:"paystack",environment:"test",reference:request.reference,state:"initialized",amountMinor:request.expectedAmountMinor,currency:request.currency,authorizationUrl:`https://checkout.paystack.test/${request.reference}`,customerEmail:request.customerEmail,metadata:request.metadata};this.records.set(request.reference,result);return result}async verify(reference){const prior=this.records.get(reference);if(!prior)throw new Error("missing");return{...prior,state:"succeeded",...this.patch}}}
const input=(packageId="launch")=>({packageId,name:"Ada Buyer",email:"ada@example.test",phone:"08000000000",brandName:"Ada Football",acceptBusinessTerms:true,acceptRefundPolicy:true,paymentMethod:"paystack",idempotencyKey:`checkout_${packageId}_123456789`,userId:"user-ada"});
test("Launch and Business orders use trusted promotional price snapshots",async()=>{for(const[id,charged,standard]of[["launch",35000000,50000000],["business",75000000,100000000]]){const service=new BusinessSetupCheckoutService(new InMemoryCheckoutRepository(),new Provider()),result=await service.initialize(input(id));assert.equal(result.order.packageId,id);assert.equal(result.order.chargedAmountMinor,charged);assert.equal(result.order.standardAmountMinor,standard);assert.equal(result.order.currency,"NGN");assert.match(result.order.priceId,/v2/);assert.equal(result.order.purpose,"business_setup")}});
test("browser amount and currency are ignored and invalid packages or acceptance fail",async()=>{const service=new BusinessSetupCheckoutService(new InMemoryCheckoutRepository(),new Provider()),tampered={...input(),amount:1,currency:"USD"};const result=await service.initialize(tampered);assert.equal(result.order.chargedAmountMinor,35000000);await assert.rejects(()=>service.initialize({...input("fake"),packageId:"fake"}),/invalid_package/);await assert.rejects(()=>service.initialize({...input(),acceptRefundPolicy:false,idempotencyKey:"different_key_123456"}),/terms_required/)});
test("references are unpredictable-shaped, unique and duplicate submit initializes once",async()=>{assert.notEqual(createPaymentReference(),createPaymentReference());const repo=new InMemoryCheckoutRepository(),provider=new Provider(),service=new BusinessSetupCheckoutService(repo,provider),first=await service.initialize(input()),second=await service.initialize(input());assert.equal(provider.calls,1);assert.equal(second.order.id,first.order.id);assert.equal(second.transaction.reference,first.transaction.reference)});
test("successful callback is idempotent and fulfills onboarding once",async()=>{const repo=new InMemoryCheckoutRepository(),provider=new Provider(),service=new BusinessSetupCheckoutService(repo,provider),initialized=await service.initialize(input()),first=await service.verify(initialized.transaction.reference),second=await service.verify(initialized.transaction.reference);assert.equal(first.order.status,"paid");assert.equal(first.order.onboardingStatus,"awaiting_client_information");assert.equal(second.order.fulfillmentCount,1)});
test("callback rejects wrong amount, currency, reference, environment and failures",async()=>{for(const patch of[{amountMinor:1},{currency:"USD"},{reference:"wrong_reference_123"},{environment:"live"},{state:"failed"}]){const repo=new InMemoryCheckoutRepository(),provider=new Provider(patch),service=new BusinessSetupCheckoutService(repo,provider),initialized=await service.initialize(input());await assert.rejects(()=>service.verify(initialized.transaction.reference),/wrong_amount|wrong_currency|wrong_reference|wrong_environment|payment_not_successful|provider_result_mismatch/)}});
test("manual transfer remains separate and does not auto-confirm",async()=>{const provider=new Provider(),service=new BusinessSetupCheckoutService(new InMemoryCheckoutRepository(),provider),result=await service.initialize({...input(),paymentMethod:"manual-bank"});assert.equal(result.order.status,"pending_payment");assert.equal(result.transaction,null);assert.equal(provider.calls,0)});
test("Paystack adapter is test-only, server-only and maps sanitized provider data",async()=>{const source=await read("modules/billing/paystack-provider.ts");assert.match(source,/sk_test_/);assert.match(source,/payments_not_safely_enabled/);assert.match(source,/transaction\/initialize/);assert.match(source,/transaction\/verify/);assert.doesNotMatch(source,/sk_live_|NEXT_PUBLIC_PAYSTACK|console\.(log|debug)/)});
test("P3 migration is additive, private, idempotent and does not implement subscriptions",async()=>{const sql=await read("supabase/migrations/202608120002_b2b_setup_checkout.sql");for(const value of["business_terms_version","refund_policy_version","checkout_idempotency_key","awaiting_client_information","confirm_business_setup_payment","fulfillment_count"])assert.match(sql,new RegExp(value));assert.match(sql,/revoke insert,update,delete/);assert.match(sql,/auth\.role\(\)<>'service_role'/);assert.doesNotMatch(sql,/drop table|delete from|create subscription|subaccount|split payment/i)});
test("checkout UI requires both policies and exposes Paystack plus manual fallback",async()=>{const ui=await read("components/platform-checkout.tsx");for(const value of["acceptBusinessTerms","acceptRefundPolicy","Pay online with Paystack","Pay by Bank Transfer","Business Terms","Refund/Cancellation Policy"])assert.match(ui,new RegExp(value));assert.doesNotMatch(ui,/card number|CVV|secret key/i)});
