import assert from"node:assert/strict";
import{createHmac}from"node:crypto";
import{readFile}from"node:fs/promises";
import test from"node:test";
import{ConsumerSubscriptionService}from"../modules/billing/consumer-subscriptions.ts";
import{InMemoryConsumerSubscriptionRepository,MockConsumerSubscriptionProvider}from"../modules/billing/consumer-subscription-mocks.ts";
import{createConfiguredPaystackProvider}from"../modules/billing/paystack-provider.ts";
import{normalizePaystackWebhook,SubscriptionLifecycleService,verifyPaystackWebhookSignature}from"../modules/billing/paystack-webhooks.ts";
import{InMemoryLifecycleRepository}from"../modules/billing/webhook-mocks.ts";

const secret="sk_test_p7b_fixture_signature",plan="PLN_oumomc9aydw61fh",sub="SUB_p7b123456",customer="CUS_p7b123456";
const subscription=(status="active",userId="user-a")=>({id:`subscription-${userId}`,userId,billingCustomerId:`customer-${userId}`,productKey:"consumer-premium-monthly",priceId:"consumer-premium-monthly-v1",providerId:"paystack",environment:"test",providerPlanReference:plan,providerCustomerReference:customer,initialPaymentReference:`TXN_${userId}_123456789`,providerSubscriptionReference:sub,amountMinor:300000,currency:"NGN",billingInterval:"monthly",status,entitlementStatus:status==="active"?"active":status==="past_due"?"suspended":"inactive",startedAt:"2026-08-13T18:37:33.000Z",currentPeriodStart:"2026-08-13T18:37:33.000Z",currentPeriodEnd:"2026-09-13T18:37:00.000Z",nextBillingAt:"2026-09-13T18:37:00.000Z",cancelAtPeriodEnd:false,createdAt:"2026-08-13T18:37:33.000Z",updatedAt:"2026-08-13T18:37:33.000Z"});
const eventBody=(event,id,patch={})=>JSON.stringify({id,event,created_at:"2026-09-13T18:38:00.000Z",data:{id:`data-${id}`,domain:"test",status:event==="invoice.payment_failed"?"failed":event==="subscription.not_renew"?"non-renewing":event==="subscription.disable"?"cancelled":"success",paid:event!=="invoice.payment_failed",invoice_code:`INV_${id}`,amount:300000,currency:"NGN",created_at:"2026-09-13T18:38:00.000Z",paid_at:event==="invoice.update"?"2026-09-13T18:38:00.000Z":undefined,period_start:"2026-09-13T18:37:00.000Z",period_end:"2026-10-13T18:37:00.000Z",next_payment_date:"2026-10-13T18:37:00.000Z",subscription:{subscription_code:sub,next_payment_date:"2026-10-13T18:37:00.000Z"},customer:{customer_code:customer},plan:{plan_code:plan,amount:300000,currency:"NGN"},metadata:{application_user_id:"user-a",product_key:"consumer-premium-monthly"},...patch}});
const signed=body=>{const signature=createHmac("sha512",secret).update(body).digest("hex");verifyPaystackWebhookSignature(body,signature,secret);return normalizePaystackWebhook(body)};

test("successful renewal advances the billing period and preserves entitlement",async()=>{const repo=new InMemoryLifecycleRepository(subscription()),service=new SubscriptionLifecycleService(repo),result=await service.process(signed(eventBody("invoice.update","renewal-1")));assert.equal(result.subscription.status,"active");assert.equal(result.subscription.entitlementStatus,"active");assert.equal(result.subscription.currentPeriodStart,"2026-09-13T18:37:00.000Z");assert.equal(result.subscription.currentPeriodEnd,"2026-10-13T18:37:00.000Z");assert.equal(result.subscription.nextBillingAt,"2026-10-13T18:37:00.000Z")});
test("successful renewal replay does not extend twice or duplicate audit",async()=>{const repo=new InMemoryLifecycleRepository(subscription()),service=new SubscriptionLifecycleService(repo),event=signed(eventBody("invoice.update","renewal-replay"));await service.process(event);const snapshot=structuredClone(await repo.getByProviderReference(sub)),again=await service.process(event);assert.equal(again.reason,"duplicate_event");assert.deepEqual(await repo.getByProviderReference(sub),snapshot);assert.equal(repo.events.size,1);assert.equal(repo.audits.length,1)});
test("renewal rejects wrong amount, plan, customer and currency",async()=>{for(const patch of[{amount:1},{plan:{plan_code:"PLN_wrong",amount:300000,currency:"NGN"}},{customer:{customer_code:"CUS_wrong"}},{currency:"USD"}]){const repo=new InMemoryLifecycleRepository(subscription()),service=new SubscriptionLifecycleService(repo);await assert.rejects(async()=>service.process(signed(eventBody("invoice.update",`bad-${JSON.stringify(patch)}`,patch))),/wrong_amount|wrong_product_plan|wrong_customer_user|malformed_webhook_payload/)}});
test("failed recurring payment suspends entitlement without changing paid-period evidence",async()=>{const initial=subscription(),repo=new InMemoryLifecycleRepository(initial),service=new SubscriptionLifecycleService(repo),result=await service.process(signed(eventBody("invoice.payment_failed","failed-1")));assert.equal(result.subscription.status,"past_due");assert.equal(result.subscription.entitlementStatus,"suspended");assert.equal(result.subscription.currentPeriodStart,initial.currentPeriodStart);assert.equal(result.subscription.currentPeriodEnd,initial.currentPeriodEnd);assert.equal(result.subscription.nextBillingAt,initial.nextBillingAt)});
test("failed recurring payment replay persists one event and one audit",async()=>{const repo=new InMemoryLifecycleRepository(subscription()),service=new SubscriptionLifecycleService(repo),event=signed(eventBody("invoice.payment_failed","failed-replay"));await service.process(event);const again=await service.process(event);assert.equal(again.reason,"duplicate_event");assert.equal(repo.events.size,1);assert.equal(repo.audits.length,1)});
test("a later successful renewal recovers a past-due subscription",async()=>{const repo=new InMemoryLifecycleRepository(subscription("past_due")),service=new SubscriptionLifecycleService(repo),result=await service.process(signed(eventBody("invoice.update","recovery")));assert.equal(result.subscription.status,"active");assert.equal(result.subscription.entitlementStatus,"active")});
test("subscription.not_renew preserves paid access until period end",async()=>{const repo=new InMemoryLifecycleRepository(subscription()),service=new SubscriptionLifecycleService(repo),result=await service.process(signed(eventBody("subscription.not_renew","not-renew")));assert.equal(result.subscription.status,"active");assert.equal(result.subscription.entitlementStatus,"active");assert.equal(result.subscription.cancelAtPeriodEnd,true)});
test("subscription.disable ends entitlement and is replay-safe",async()=>{const repo=new InMemoryLifecycleRepository(subscription()),service=new SubscriptionLifecycleService(repo),event=signed(eventBody("subscription.disable","disable")),first=await service.process(event),again=await service.process(event);assert.equal(first.subscription.status,"cancelled");assert.equal(first.subscription.entitlementStatus,"inactive");assert.equal(again.reason,"duplicate_event");assert.equal(repo.audits.length,1)});
test("different lifecycle events for one SUB identity are not duplicates",async()=>{const repo=new InMemoryLifecycleRepository(subscription()),service=new SubscriptionLifecycleService(repo);await service.process(signed(eventBody("subscription.not_renew","distinct-1")));await service.process(signed(eventBody("subscription.disable","distinct-2")));assert.equal(repo.events.size,2);assert.equal(repo.audits.length,2)});
test("subscription.create replay remains idempotent",async()=>{const pending={...subscription("pending"),providerSubscriptionReference:undefined,currentPeriodStart:undefined,currentPeriodEnd:undefined,nextBillingAt:undefined},repo=new InMemoryLifecycleRepository(pending),service=new SubscriptionLifecycleService(repo),body=eventBody("subscription.create","create",{status:"active",subscription_code:sub,subscription:undefined,createdAt:"2026-09-13T18:38:00.000Z"}),event=signed(body);await service.process(event);await service.process(event);assert.equal(repo.events.size,1);assert.equal(repo.audits.length,1)});
test("malformed timestamps, incomplete invoices, invalid signatures and LIVE domain fail closed",async()=>{assert.throws(()=>normalizePaystackWebhook(eventBody("invoice.update","bad-time",{period_end:"not-a-date"})),/malformed/);assert.throws(()=>normalizePaystackWebhook(eventBody("invoice.update","unpaid",{paid:false})),/malformed/);assert.throws(()=>verifyPaystackWebhookSignature(eventBody("invoice.update","signature"),"bad",secret),/signature/);assert.throws(()=>normalizePaystackWebhook(eventBody("invoice.update","live",{domain:"live"})),/environment/)});

const serviceSetup=async()=>{const repo=new InMemoryConsumerSubscriptionRepository(),provider=new MockConsumerSubscriptionProvider(),service=new ConsumerSubscriptionService(repo,provider),now="2026-08-13T18:37:33.000Z",value=subscription();repo.customers.set("user-a:paystack:test",{id:"customer-user-a",userId:"user-a",providerId:"paystack",environment:"test",providerCustomerReference:customer,createdAt:now,updatedAt:now});repo.subscriptions.set(value.id,structuredClone(value));return{repo,provider,service}};
test("owner cancellation is cancel-at-period-end and idempotent",async()=>{const{service,provider}=await serviceSetup(),first=await service.cancel("user-a"),second=await service.cancel("user-a");assert.equal(first.cancelAtPeriodEnd,true);assert.equal(first.entitlementStatus,"active");assert.equal(second.id,first.id);assert.equal(provider.cancellationCalls,1)});
test("cross-user and unauthenticated cancellation fail before provider mutation",async()=>{const{service,provider}=await serviceSetup();await assert.rejects(()=>service.cancel("user-b"),/not_found/);await assert.rejects(()=>service.cancel(""),/authentication/);assert.equal(provider.cancellationCalls,0)});
test("browser cannot supply an arbitrary subscription identity to cancellation",async()=>{const source=await readFile(new URL("../modules/billing/consumer-subscriptions.ts",import.meta.url),"utf8");assert.match(source,/async cancel\(userId:string\)/);assert.doesNotMatch(source,/async cancel\(userId:string,providerSubscriptionReference/)});
test("owner can resume the same non-renewing subscription exactly once",async()=>{const{service,provider}=await serviceSetup();await service.cancel("user-a");const resumed=await service.resume("user-a"),again=await service.resume("user-a");assert.equal(resumed.cancelAtPeriodEnd,false);assert.equal(resumed.entitlementStatus,"active");assert.equal(again.id,resumed.id);assert.equal(provider.enableCalls,1)});
test("cross-user and unauthenticated resumption fail before provider mutation",async()=>{const{service,provider}=await serviceSetup();await service.cancel("user-a");await assert.rejects(()=>service.resume("user-b"),/not_found/);await assert.rejects(()=>service.resume(""),/authentication/);assert.equal(provider.enableCalls,0)});
test("cancel and resume require genuine provider subscription identity",async()=>{const{repo,service}=await serviceSetup(),value=await repo.getByUser("user-a");value.providerSubscriptionReference="TXN_not_subscription";await repo.saveSubscription(value);await assert.rejects(()=>service.cancel("user-a"),/not_found/);await assert.rejects(()=>service.resume("user-a"),/not_found/)});
test("LIVE provider supports validated cancel and resume lifecycle",async()=>{const{repo,provider}=await serviceSetup();Object.defineProperty(provider,"environment",{value:"live"});const service=new ConsumerSubscriptionService(repo,provider);const cancelled=await service.cancel("user-a");assert.equal(cancelled.cancelAtPeriodEnd,true);const resumed=await service.resume("user-a");assert.equal(resumed.cancelAtPeriodEnd,false)});

test("TEST provider factory rejects Production host and live credentials",()=>{const base={PAYMENTS_ENABLED:"true",PAYMENT_PROVIDER:"paystack",PAYSTACK_ENVIRONMENT:"test",PAYSTACK_SECRET_KEY:"sk_test_safe_fixture_123456",PAYSTACK_CONSUMER_MONTHLY_PLAN_CODE:plan};assert.throws(()=>createConfiguredPaystackProvider({...base,NEXT_PUBLIC_SITE_URL:"https://9jafootballai.com.ng"}),/production_site_forbidden/);assert.throws(()=>createConfiguredPaystackProvider({...base,PAYSTACK_SECRET_KEY:"sk_live_never_allowed"}),/payments_not_safely_enabled/)});
test("wrong consumer catalogue inputs cannot initialize a consumer checkout",async()=>{const{service}=await serviceSetup();for(const productKey of["business-launch","consumer-premium-yearly"]){await assert.rejects(()=>service.initialize({userId:"new-user",email:"member@example.test",productKey,idempotencyKey:"p7b_catalogue_123456789"}),/invalid_subscription_request/)}});
test("billing repositories use the shared environment-aware project identity guard",async()=>{const files=await Promise.all(["consumer-subscription-repository.ts","webhook-repository.ts"].map(name=>readFile(new URL(`../modules/billing/${name}`,import.meta.url),"utf8")));for(const source of files){assert.match(source,/requireServiceRoleSupabaseConfig/);assert.doesNotMatch(source,/oislplqdvtaajqxbwvut|development_supabase_required/)}});
