import assert from"node:assert/strict";
import{createHmac}from"node:crypto";
import{readFile}from"node:fs/promises";
import test from"node:test";
import{BusinessSetupCheckoutService}from"../modules/billing/b2b-checkout.ts";
import{InMemoryCheckoutRepository}from"../modules/billing/b2b-checkout-repository.ts";
import{normalizeB2BPaystackWebhook,resolveB2BPaystackWebhook}from"../modules/billing/b2b-webhooks.ts";
import{isGenuinePaystackSubscriptionReference}from"../modules/billing/consumer-subscriptions.ts";
import{verifyPaystackWebhookSignature}from"../modules/billing/paystack-webhooks.ts";

class Provider{constructor(){this.id="paystack";this.environment="test";this.initializeCalls=0;this.verifyCalls=0;this.patch={};this.records=new Map()}async initialize(request){this.initializeCalls++;const result={providerId:"paystack",environment:"test",reference:request.reference,state:"initialized",amountMinor:request.expectedAmountMinor,currency:request.currency,authorizationUrl:`https://checkout.paystack.test/${request.reference}`,customerEmail:request.customerEmail,metadata:request.metadata};this.records.set(request.reference,result);return result}async verify(reference){this.verifyCalls++;const result=this.records.get(reference);if(!result)throw new Error("missing");return{...result,state:"succeeded",...this.patch}}}
const input=(packageId="launch",patch={})=>({packageId,name:"P7C Buyer",email:"p7c@example.test",phone:"08000000000",brandName:"P7C Football",acceptBusinessTerms:true,acceptRefundPolicy:true,paymentMethod:"paystack",idempotencyKey:`p7c_${packageId}_checkout_123456789`,userId:"user-p7c",...patch});
const setup=async(packageId="launch")=>{const repository=new InMemoryCheckoutRepository(),provider=new Provider(),service=new BusinessSetupCheckoutService(repository,provider),initialized=await service.initialize(input(packageId));return{repository,provider,service,initialized}};
const webhook=(initialized,event="charge.success",patch={})=>JSON.stringify({id:`event-${event}`,event,created_at:"2026-08-13T22:00:00.000Z",data:{domain:"test",status:event==="charge.success"?"success":"failed",reference:initialized.transaction.reference,amount:initialized.order.chargedAmountMinor,currency:"NGN",created_at:"2026-08-13T22:00:00.000Z",paid_at:event==="charge.success"?"2026-08-13T22:00:00.000Z":undefined,customer:{email:initialized.order.buyer.email},metadata:{order_id:initialized.order.id,product_key:initialized.order.productKey,price_id:initialized.order.priceId},...patch}});

test("trusted Launch and Business package prices ignore caller amount and currency",async()=>{for(const[id,amount]of[["launch",35000000],["business",75000000]]){const repository=new InMemoryCheckoutRepository(),provider=new Provider(),service=new BusinessSetupCheckoutService(repository,provider),result=await service.initialize(input(id,{amount:1,currency:"USD"}));assert.equal(result.order.chargedAmountMinor,amount);assert.equal(result.order.currency,"NGN");assert.equal(result.transaction.expectedAmountMinor,amount)}});
test("unknown package and unauthenticated Paystack checkout fail before provider",async()=>{const repository=new InMemoryCheckoutRepository(),provider=new Provider(),service=new BusinessSetupCheckoutService(repository,provider);await assert.rejects(()=>service.initialize(input("fake")),/invalid_package/);await assert.rejects(()=>service.initialize(input("launch",{userId:undefined,idempotencyKey:"p7c_unauthenticated_123456"})),/authentication_required/);assert.equal(provider.initializeCalls,0)});
test("order retains immutable package, price, promotion and terms snapshot",async()=>{const{initialized}=await setup();const snapshot=structuredClone(initialized.order);assert.deepEqual({productKey:snapshot.productKey,priceId:snapshot.priceId,promotionId:snapshot.promotionId,charged:snapshot.chargedAmountMinor,standard:snapshot.standardAmountMinor,terms:snapshot.businessTermsVersion,refund:snapshot.refundPolicyVersion}, {productKey:"b2b-launch-setup",priceId:"b2b-launch-setup-v2",promotionId:"b2b-launch-setup-v2",charged:35000000,standard:50000000,terms:"2026-08-12",refund:"2026-08-12"});assert.ok(Date.parse(snapshot.acceptedAt))});
test("persistent-style idempotency returns the existing transaction and checkout URL",async()=>{const{service,provider,initialized}=await setup(),again=await service.initialize(input());assert.equal(again.order.id,initialized.order.id);assert.equal(again.transaction.reference,initialized.transaction.reference);assert.equal(again.authorizationUrl,initialized.authorizationUrl);assert.equal(provider.initializeCalls,1)});
test("abandoned checkout remains pending without onboarding or entitlement",async()=>{const{initialized}=await setup();assert.equal(initialized.order.status,"pending_payment");assert.equal(initialized.order.onboardingStatus,"awaiting_payment");assert.equal(initialized.order.fulfillmentCount,0);assert.equal("entitlementStatus"in initialized.order,false)});
test("successful verification confirms payment and onboarding exactly once",async()=>{const{service,provider,initialized}=await setup(),first=await service.verify(initialized.transaction.reference,"user-p7c"),second=await service.verify(initialized.transaction.reference,"user-p7c");assert.equal(first.order.status,"paid");assert.equal(first.order.onboardingStatus,"awaiting_client_information");assert.equal(second.order.fulfillmentCount,1);assert.equal(provider.verifyCalls,1)});
test("cross-user, unknown reference and arbitrary order access fail closed",async()=>{const{service,provider,initialized}=await setup();await assert.rejects(()=>service.verify(initialized.transaction.reference,"user-other"),/access_denied/);await assert.rejects(()=>service.verify("B2B_unknown_reference_123"),/transaction_not_found/);assert.equal(provider.verifyCalls,0)});
test("provider amount, currency, environment, reference, customer and order metadata mismatches fail",async()=>{for(const patch of[{amountMinor:1},{currency:"USD"},{environment:"live"},{reference:"B2B_wrong_reference_123"},{customerEmail:"other@example.test"},{metadata:{order_id:"wrong",product_key:"b2b-launch-setup",price_id:"b2b-launch-setup-v2"}}]){const x=await setup();x.provider.patch=patch;await assert.rejects(()=>x.service.verify(x.initialized.transaction.reference),/wrong_amount|wrong_currency|wrong_environment|wrong_reference|wrong_customer|wrong_order_metadata/)}});
test("failed verification is auditable and never starts onboarding",async()=>{const x=await setup();x.provider.patch={state:"failed"};await assert.rejects(()=>x.service.verify(x.initialized.transaction.reference),/payment_not_successful/);const order=await x.repository.getOrder(x.initialized.order.id),transaction=await x.repository.getTransaction(x.initialized.transaction.reference);assert.equal(order.status,"payment_failed");assert.equal(order.onboardingStatus,"awaiting_payment");assert.equal(transaction.state,"failed");assert.match(transaction.providerMessage,/unsuccessful/)});
test("a later valid reconciliation recovers a failed payment exactly once",async()=>{const x=await setup();x.provider.patch={state:"failed"};await assert.rejects(()=>x.service.verify(x.initialized.transaction.reference));x.provider.patch={};const recovered=await x.service.verify(x.initialized.transaction.reference),replay=await x.service.verify(x.initialized.transaction.reference);assert.equal(recovered.order.status,"paid");assert.equal(replay.order.fulfillmentCount,1)});
test("stale failure webhook cannot reverse a paid order",async()=>{const x=await setup();await x.service.verify(x.initialized.transaction.reference);const result=await x.service.processWebhook(normalizeB2BPaystackWebhook(webhook(x.initialized,"charge.failed")));assert.equal(result.order.status,"paid");assert.equal(result.order.fulfillmentCount,1)});
test("B2B webhook normalization requires exact TEST structural fields",()=>{const fixture={order:{id:"order-1",buyer:{email:"p7c@example.test"},productKey:"b2b-launch-setup",priceId:"b2b-launch-setup-v2",chargedAmountMinor:35000000},transaction:{reference:"B2B_fixture_123456789"}},body=webhook(fixture),event=normalizeB2BPaystackWebhook(body);assert.deepEqual([event.type,event.environment,event.amountMinor,event.currency],["payment_succeeded","test",35000000,"NGN"]);for(const patch of[{domain:"live"},{currency:"USD"},{customer:{}},{metadata:{}}])assert.throws(()=>normalizeB2BPaystackWebhook(webhook(fixture,"charge.success",patch)),/environment|malformed/)});
test("B2B webhook service rejects wrong amount, customer and order metadata",async()=>{for(const patch of[{amount:1},{customer:{email:"other@example.test"}},{metadata:{order_id:"wrong",product_key:"b2b-launch-setup",price_id:"b2b-launch-setup-v2"}}]){const x=await setup(),event=normalizeB2BPaystackWebhook(webhook(x.initialized,"charge.success",patch));await assert.rejects(()=>x.service.processWebhook(event),/wrong_amount|wrong_order_customer/)}});
test("signed success webhook fulfills once and replay is idempotent",async()=>{const x=await setup(),event=normalizeB2BPaystackWebhook(webhook(x.initialized));await x.service.processWebhook(event);await x.service.processWebhook(event);const order=await x.repository.getOrder(x.initialized.order.id);assert.equal(order.fulfillmentCount,1);assert.equal(x.provider.verifyCalls,1)});
test("signed failure webhook records failure once and permits later recovery",async()=>{const x=await setup(),event=normalizeB2BPaystackWebhook(webhook(x.initialized,"charge.failed"));await x.service.processWebhook(event);const timestamp=(await x.repository.getTransaction(x.initialized.transaction.reference)).updatedAt;await x.service.processWebhook(event);assert.equal((await x.repository.getTransaction(x.initialized.transaction.reference)).updatedAt,timestamp);await x.service.verify(x.initialized.transaction.reference);assert.equal((await x.repository.getOrder(x.initialized.order.id)).status,"paid")});
test("webhook signature remains mandatory before B2B lifecycle processing",()=>{const body=JSON.stringify({event:"charge.success",data:{}}),secret="sk_test_p7c_fixture";assert.throws(()=>verifyPaystackWebhookSignature(body,undefined,secret),/missing/);assert.throws(()=>verifyPaystackWebhookSignature(body,"invalid",secret),/invalid/);const signature=createHmac("sha512",secret).update(body).digest("hex");assert.equal(verifyPaystackWebhookSignature(body,signature,secret),true)});
test("webhook resolver ignores non-B2B and unknown B2B references",async()=>{let processed=0;const deps={hasTransaction:async()=>false,process:async()=>{processed++}};assert.equal(await resolveB2BPaystackWebhook(JSON.stringify({event:"subscription.create",data:{}}),deps),null);const x=await setup();assert.equal(await resolveB2BPaystackWebhook(webhook(x.initialized),deps),null);assert.equal(processed,0)});
test("consumer and B2B identities cannot cross domains",async()=>{assert.equal(isGenuinePaystackSubscriptionReference("B2B_reference_123456"),false);assert.throws(()=>normalizeB2BPaystackWebhook(JSON.stringify({event:"charge.success",data:{domain:"test",reference:"SUB_genuine123"}})),/malformed/);const callback=await readFile(new URL("../modules/billing/callback-runtime.ts",import.meta.url),"utf8");assert.match(callback,/ambiguous_payment_reference/);assert.match(callback,/reconcileConsumer/);assert.match(callback,/verifyBusiness/)});
test("B2B webhook event cannot grant consumer entitlement",async()=>{const x=await setup(),result=await x.service.processWebhook(normalizeB2BPaystackWebhook(webhook(x.initialized)));assert.equal(result.order.status,"paid");assert.equal("entitlementStatus"in result.order,false);assert.equal(x.repository.orders.size,1);assert.equal(x.repository.transactions.size,1)});
test("environment-aware repository and TEST-only provider guards remain explicit",async()=>{const[repository,provider]=await Promise.all([readFile(new URL("../modules/billing/b2b-checkout-repository.ts",import.meta.url),"utf8"),readFile(new URL("../modules/billing/paystack-provider.ts",import.meta.url),"utf8")]);assert.match(repository,/requireServiceRoleSupabaseConfig/);assert.match(provider,/production_site_forbidden_in_test/);assert.match(provider,/live_paystack_key_forbidden/)});
test("migration preserves atomic one-time fulfillment and private mutation",async()=>{const sql=await readFile(new URL("../supabase/migrations/202608120002_b2b_setup_checkout.sql",import.meta.url),"utf8");assert.match(sql,/fulfillment_count=fulfillment_count\+1/);assert.match(sql,/if v_order\.order_status='paid'then return/);assert.match(sql,/auth\.role\(\)<>'service_role'/);assert.match(sql,/unique index orders_checkout_idempotency_key_idx/)});
