import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { ManagedPlatformBillingService, addCalendarMonths, statusAt } from "../modules/billing/managed-platform.ts";
import { InMemoryManagedPlatformRepository } from "../modules/billing/managed-platform-repository.ts";

const paidOrder = (packageId = "launch", patch = {}) => ({ id: `order-${packageId}`, orderNumber: `9FA-${packageId}`, userId: "owner-1", buyer: { name: "P7D Buyer", email: "p7d@example.test" }, packageId, purpose: "business_setup", environment: "test", productKey: `b2b-${packageId}-setup`, priceId: `b2b-${packageId}-setup-v2`, standardAmountMinor: packageId === "launch" ? 50000000 : 100000000, chargedAmountMinor: packageId === "launch" ? 35000000 : 75000000, currency: "NGN", businessTermsVersion: "2026-08-12", refundPolicyVersion: "2026-08-12", acceptedAt: "2026-08-13T20:00:00.000Z", paymentMethod: "paystack", status: "paid", onboardingStatus: "awaiting_client_information", createdAt: "2026-08-13T20:00:00.000Z", updatedAt: "2026-08-13T21:51:55.676Z", paidAt: "2026-08-13T21:51:55.676Z", fulfillmentCount: 1, ...patch });
const clock = value => ({ now: () => new Date(value) });
const service = (repo, at, environment = "test") => new ManagedPlatformBillingService(repo, environment, clock(at));

test("calendar-month calculation clamps month-end and preserves exact UTC instant", () => { assert.equal(addCalendarMonths("2026-08-13T21:51:55.676Z", 6), "2027-02-13T21:51:55.676Z"); assert.equal(addCalendarMonths("2026-08-31T10:00:00.000Z", 6), "2027-02-28T10:00:00.000Z"); });
test("Launch paid setup establishes six included months and trusted ₦18,000 monthly obligation", async () => { const order = paidOrder(), repo = new InMemoryManagedPlatformRepository([order]), record = await service(repo, "2026-08-13T21:51:55.676Z").establishForPaidOrder(order.id, "owner-1"); assert.deepEqual({ product: record.productKey, amount: record.amountMinor, currency: record.currency, interval: record.billingInterval, status: record.status, start: record.includedPeriodStart, end: record.includedPeriodEnd, environment: record.environment }, { product: "managed-launch-monthly", amount: 1800000, currency: "NGN", interval: "monthly", status: "included_period", start: order.paidAt, end: "2027-02-13T21:51:55.676Z", environment: "test" }); assert.equal(repo.records.size, 1); });
test("Business paid setup establishes six included months and trusted ₦24,000 monthly obligation", async () => { const order = paidOrder("business"), repo = new InMemoryManagedPlatformRepository([order]), record = await service(repo, "2026-08-14T00:00:00Z").establishForPaidOrder(order.id, "owner-1"); assert.equal(record.amountMinor, 2400000); assert.equal(record.productKey, "managed-business-monthly"); });
test("included-period boundary is exact and deterministic", async () => { const order = paidOrder(), repo = new InMemoryManagedPlatformRepository([order]), record = await service(repo, order.paidAt).establishForPaidOrder(order.id, "owner-1"); for (const at of [order.paidAt, "2026-09-13T21:51:55.676Z", "2027-02-13T21:51:55.675Z"]) assert.equal(statusAt(record, new Date(at)), "included_period"); assert.equal(statusAt(record, new Date("2027-02-13T21:51:55.676Z")), "authorization_required"); });
test("billing authorization is impossible during included period", async () => { const order = paidOrder(), repo = new InMemoryManagedPlatformRepository([order]), current = service(repo, "2026-12-01T00:00:00Z"); await current.establishForPaidOrder(order.id, "owner-1"); await assert.rejects(() => current.requestAuthorization(order.id, "owner-1"), /included_period_active/); });
test("expiry exposes authorization requirement without initializing a charge", async () => { const order = paidOrder(), repo = new InMemoryManagedPlatformRepository([order]); await service(repo, order.paidAt).establishForPaidOrder(order.id, "owner-1"); const record = await service(repo, "2027-02-13T21:51:55.676Z").requestAuthorization(order.id, "owner-1"); assert.equal(record.status, "authorization_required"); assert.equal(record.providerSubscriptionReference, undefined); });
test("duplicate establishment is idempotent", async () => { const order = paidOrder(), repo = new InMemoryManagedPlatformRepository([order]), current = service(repo, order.paidAt), first = await current.establishForPaidOrder(order.id, "owner-1"), second = await current.establishForPaidOrder(order.id, "owner-1"); assert.equal(second.id, first.id); assert.equal(repo.records.size, 1); });
test("ownership, paid state and environment fail closed", async () => { const order = paidOrder(), repo = new InMemoryManagedPlatformRepository([order]), current = service(repo, order.paidAt); await assert.rejects(() => current.establishForPaidOrder(order.id, "other-user"), /access_denied/); const pending = paidOrder("launch", { id: "pending", status: "pending_payment", paidAt: undefined }); repo.orders.set(pending.id, pending); await assert.rejects(() => current.establishForPaidOrder(pending.id, "owner-1"), /qualifying_paid_order_required/); await assert.rejects(() => service(repo, order.paidAt, "live").establishForPaidOrder(order.id, "owner-1"), /qualifying_paid_order_required/); });
test("LIVE managed billing uses LIVE and rejects TEST records", async () => { const order = paidOrder("launch", { id: "live-order", environment: "live" }), repo = new InMemoryManagedPlatformRepository([order]), live = service(repo, order.paidAt, "live"), record = await live.establishForPaidOrder(order.id, "owner-1"); assert.equal(record.environment, "live"); await assert.rejects(() => service(repo, order.paidAt, "test").getStatus(order.id, "owner-1"), /environment_mismatch/); });
test("migration is additive, private, and environment-aware", async () => { const sql = await readFile(new URL("../supabase/migrations/202608150001_p8b11d_billing_environment_isolation.sql", import.meta.url), "utf8"); for (const value of ["p_environment", "provider_environment", "payment_environment", "establish_managed_platform_billing"]) assert.match(sql, new RegExp(value)); assert.match(sql, /auth\.role\(\) <> 'service_role'/); assert.doesNotMatch(sql, /drop table|delete from/i); });
test("managed billing source contains no checkout initialization or hard-coded runtime TEST", async () => { const [source, repository] = await Promise.all([readFile(new URL("../modules/billing/managed-platform.ts", import.meta.url), "utf8"), readFile(new URL("../modules/billing/managed-platform-repository.ts", import.meta.url), "utf8")]); assert.doesNotMatch(source, /Paystack|initializeSubscription|ConsumerSubscription|fetch\(/); assert.match(repository, /requireServiceRoleSupabaseConfig/); assert.doesNotMatch(`${source}\n${repository}`, /environment\s*:\s*["']test["']/); });
