import assert from"node:assert/strict";
import{readFile}from"node:fs/promises";
import test from"node:test";
import{ManagedPlatformBillingService,addCalendarMonths,statusAt}from"../modules/billing/managed-platform.ts";
import{InMemoryManagedPlatformRepository}from"../modules/billing/managed-platform-repository.ts";

const paidOrder=(packageId="launch",patch={})=>({id:`order-${packageId}`,orderNumber:`9FA-${packageId}`,userId:"owner-1",buyer:{name:"P7D Buyer",email:"p7d@example.test"},packageId,purpose:"business_setup",productKey:`b2b-${packageId}-setup`,priceId:`b2b-${packageId}-setup-v2`,standardAmountMinor:packageId==="launch"?50000000:100000000,chargedAmountMinor:packageId==="launch"?35000000:75000000,currency:"NGN",businessTermsVersion:"2026-08-12",refundPolicyVersion:"2026-08-12",acceptedAt:"2026-08-13T20:00:00.000Z",paymentMethod:"paystack",status:"paid",onboardingStatus:"awaiting_client_information",createdAt:"2026-08-13T20:00:00.000Z",updatedAt:"2026-08-13T21:51:55.676Z",paidAt:"2026-08-13T21:51:55.676Z",fulfillmentCount:1,...patch});
const clock=value=>({now:()=>new Date(value)});

test("calendar-month calculation clamps month-end and preserves exact UTC instant",()=>{assert.equal(addCalendarMonths("2026-08-13T21:51:55.676Z",6),"2027-02-13T21:51:55.676Z");assert.equal(addCalendarMonths("2026-08-31T10:00:00.000Z",6),"2027-02-28T10:00:00.000Z")});
test("Launch paid setup establishes six included months and trusted ₦18,000 monthly obligation",async()=>{const order=paidOrder(),repo=new InMemoryManagedPlatformRepository([order]),service=new ManagedPlatformBillingService(repo,clock("2026-08-13T21:51:55.676Z")),record=await service.establishForPaidOrder(order.id,"owner-1");assert.deepEqual({product:record.productKey,amount:record.amountMinor,currency:record.currency,interval:record.billingInterval,status:record.status,start:record.includedPeriodStart,end:record.includedPeriodEnd},{product:"managed-launch-monthly",amount:1800000,currency:"NGN",interval:"monthly",status:"included_period",start:order.paidAt,end:"2027-02-13T21:51:55.676Z"});assert.equal(order.chargedAmountMinor,35000000);assert.equal(repo.records.size,1)});
test("Business paid setup establishes six included months and trusted ₦24,000 monthly obligation",async()=>{const order=paidOrder("business"),repo=new InMemoryManagedPlatformRepository([order]),record=await new ManagedPlatformBillingService(repo,clock("2026-08-14T00:00:00Z")).establishForPaidOrder(order.id,"owner-1");assert.equal(record.amountMinor,2400000);assert.equal(record.productKey,"managed-business-monthly");assert.equal(record.status,"included_period")});
test("included-period boundary is exact and deterministic",async()=>{const order=paidOrder(),repo=new InMemoryManagedPlatformRepository([order]),record=await new ManagedPlatformBillingService(repo,clock(order.paidAt)).establishForPaidOrder(order.id,"owner-1");for(const at of[order.paidAt,"2026-09-13T21:51:55.676Z","2027-02-13T21:51:55.675Z"])assert.equal(statusAt(record,new Date(at)),"included_period");assert.equal(statusAt(record,new Date("2027-02-13T21:51:55.676Z")),"authorization_required");assert.equal(statusAt(record,new Date("2027-02-13T21:51:55.677Z")),"authorization_required")});
test("billing authorization is impossible during included period and performs no provider operation",async()=>{const order=paidOrder(),repo=new InMemoryManagedPlatformRepository([order]),service=new ManagedPlatformBillingService(repo,clock("2026-12-01T00:00:00Z"));await service.establishForPaidOrder(order.id,"owner-1");await assert.rejects(()=>service.requestAuthorization(order.id,"owner-1"),/included_period_active/);assert.equal(repo.records.size,1)});
test("expiry exposes authorization requirement but never silently initializes a charge",async()=>{const order=paidOrder(),repo=new InMemoryManagedPlatformRepository([order]),early=new ManagedPlatformBillingService(repo,clock(order.paidAt));await early.establishForPaidOrder(order.id,"owner-1");const expired=new ManagedPlatformBillingService(repo,clock("2027-02-13T21:51:55.676Z")),record=await expired.requestAuthorization(order.id,"owner-1");assert.equal(record.status,"authorization_required");assert.equal(record.providerSubscriptionReference,undefined);assert.equal(record.authorizationReference,undefined)});
test("duplicate establishment is idempotent and retains one obligation",async()=>{const order=paidOrder(),repo=new InMemoryManagedPlatformRepository([order]),service=new ManagedPlatformBillingService(repo,clock(order.paidAt)),first=await service.establishForPaidOrder(order.id,"owner-1"),second=await service.establishForPaidOrder(order.id,"owner-1");assert.equal(second.id,first.id);assert.equal(repo.records.size,1)});
test("ownership, paid state and browser-controlled dates/prices fail closed",async()=>{const order=paidOrder(),repo=new InMemoryManagedPlatformRepository([order]),service=new ManagedPlatformBillingService(repo,clock(order.paidAt));await assert.rejects(()=>service.establishForPaidOrder(order.id,"other-user"),/access_denied/);const pending=paidOrder("launch",{id:"pending",status:"pending_payment",paidAt:undefined});repo.orders.set(pending.id,pending);await assert.rejects(()=>service.establishForPaidOrder(pending.id,"owner-1"),/qualifying_paid_order_required/);const record=await service.establishForPaidOrder(order.id,"owner-1");assert.equal(record.includedPeriodStart,order.paidAt);assert.equal(record.amountMinor,1800000)});
test("status refresh is replay-safe and preserves immutable setup evidence",async()=>{const order=paidOrder(),repo=new InMemoryManagedPlatformRepository([order]),start=new ManagedPlatformBillingService(repo,clock(order.paidAt)),record=await start.establishForPaidOrder(order.id,"owner-1"),expired=new ManagedPlatformBillingService(repo,clock(record.includedPeriodEnd)),first=await expired.getStatus(order.id,"owner-1"),second=await expired.getStatus(order.id,"owner-1");assert.equal(first.status,"authorization_required");assert.deepEqual(second,first);assert.equal(repo.records.size,1);assert.equal(order.status,"paid");assert.equal(order.onboardingStatus,"awaiting_client_information");assert.equal(order.fulfillmentCount,1)});
test("migration is additive, private, order-bound and requires genuine subscription identity for active billing",async()=>{const sql=await readFile(new URL("../supabase/migrations/202608130002_managed_platform_included_period.sql",import.meta.url),"utf8");for(const value of["managed_platform_billings","setup_order_id","included_period_start","included_period_end","authorization_required","1800000","2400000","establish_managed_platform_billing","create_managed_platform_billing_after_payment"])assert.match(sql,new RegExp(value));assert.match(sql,/included_period_end=included_period_start\+interval'6 months'/);assert.match(sql,/order_status<>'paid'/);assert.match(sql,/auth\.role\(\)<>'service_role'/);assert.match(sql,/provider_subscription_reference~'\^SUB_/);assert.match(sql,/on conflict\(setup_order_id\)do nothing/);assert.match(sql,/payment_purpose='business_setup'and order_status='paid'/);assert.match(sql,/revoke insert,update,delete/);assert.doesNotMatch(sql,/drop table|delete from|alter table public\.consumer_subscriptions|update public\.consumer_subscriptions/i)});
test("managed billing source contains no checkout initialization or consumer fulfillment dependency",async()=>{const[source,repository]=await Promise.all([readFile(new URL("../modules/billing/managed-platform.ts",import.meta.url),"utf8"),readFile(new URL("../modules/billing/managed-platform-repository.ts",import.meta.url),"utf8")]);assert.doesNotMatch(source,/Paystack|initializeSubscription|ConsumerSubscription|fetch\(/);assert.match(repository,/requireServiceRoleSupabaseConfig/);assert.doesNotMatch(`${source}\n${repository}`,/sk_test_|sk_live_|consumer_subscriptions/) });
