import "tsx/esm";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const { buildSeasonSpanningEvidenceDataset, selectSeasonSpanningTeamEvidence } = await import("../modules/football-intelligence/historical-evidence-bridge.ts");
const read = (path) => readFile(new URL(`../${path}`, import.meta.url), "utf8");
const team = (id) => ({ id, providerId: id, name: id });
const evidence = (source, season) => ({ competitionId: `c-${season}`, providerCompetitionId: "39", competitionName: "Premier League", season, source });
const match = (id, date, homeTeamId, awayTeamId, source = "current-season", season = "2026") => ({ id, providerFixtureId: id, kickoffAt: date, status: "finished", homeTeamId, awayTeamId, homeScore: 1, awayScore: 0, evidence: evidence(source, season) });
const previous = Array.from({ length: 7 }, (_, index) => match(`p${index + 1}`, `2026-04-${String(index + 1).padStart(2, "0")}T15:00:00Z`, "home", `old-${index}`, "previous-season", "2025"));
const current = Array.from({ length: 2 }, (_, index) => match(`c${index + 1}`, `2026-08-${String(index + 1).padStart(2, "0")}T15:00:00Z`, "home", `new-${index}`));

test("two current matches are supplemented by the three newest previous-season league matches", () => { const audit = selectSeasonSpanningTeamEvidence([...previous, ...current], "home"); assert.equal(audit.currentSeasonUsed, 2); assert.equal(audit.previousSeasonUsed, 3); assert.deepEqual(audit.fixtureIds, ["p5", "p6", "p7", "c1", "c2"]); assert.equal(audit.eligible, true); });
test("five current matches fully replace previous-season evidence", () => { const five = [...current, ...Array.from({ length: 3 }, (_, index) => match(`c${index + 3}`, `2026-08-${index + 3}T15:00:00Z`, "home", `n-${index}`))]; const audit = selectSeasonSpanningTeamEvidence([...previous, ...five], "home"); assert.equal(audit.currentSeasonUsed, 5); assert.equal(audit.previousSeasonUsed, 0); });
test("previous-season-only evidence can satisfy five without lowering the minimum", () => { const audit = selectSeasonSpanningTeamEvidence(previous, "home"); assert.equal(audit.totalUsed, 5); assert.equal(audit.previousSeasonUsed, 5); assert.equal(audit.eligible, true); });
test("promoted team without same-league previous membership fails closed", () => { const audit = selectSeasonSpanningTeamEvidence(current, "home"); assert.equal(audit.eligible, false); assert.equal(audit.exclusionReason, "INSUFFICIENT_SAME_LEAGUE_HISTORY"); });
test("bridge keeps provenance and excludes older surplus evidence deterministically", () => { const dataset = { competition: { id: "c", providerId: "39", name: "Premier League", country: "England", season: "2026" }, teams: [team("home"), team("away")], fixtures: [...previous, ...current, ...previous.map((row, index) => ({ ...row, id: `a${index}`, providerFixtureId: `a${index}`, homeTeamId: "away" }))] }; const bridged = buildSeasonSpanningEvidenceDataset(dataset, "home", "away"); assert.equal(bridged.home.totalUsed, 5); assert.equal(bridged.away.totalUsed, 5); assert.ok(bridged.dataset.fixtures.every((row) => row.evidence?.season === "2025" || row.evidence?.season === "2026")); });
test("historical ingestion verifies the complete cohort before provider-backed idempotent ingestion", async () => { const [service, config, repository] = await Promise.all([read("modules/football-orchestration/service.ts"), read("modules/football-orchestration/config.ts"), read("modules/persistence/football-repositories.ts")]); assert.match(service, /FOOTBALL_HISTORICAL_INGESTION_ENABLED/); assert.match(service, /discoverCompetitions/); assert.match(service, /historicalLeagueTargets/); assert.match(service, /verifiedTargets\.length!==selected\.length/); assert.ok(service.indexOf("verifiedTargets.length!==selected.length") < service.indexOf("ingestHistoricalLeague" , service.indexOf("private async ingestHistorical"))); assert.match(config, /historicalIngestionEnabled:on/); assert.match(repository, /onConflict: "provider,provider_fixture_id"/); assert.doesNotMatch(service, /NEXT_PUBLIC|CRON_SECRET/); });
test("historical ingestion reserves the full daily request budget before provider verification", async () => { const service = await read("modules/football-orchestration/service.ts"); const budgetCheck = service.indexOf("requestsUsed+selected.length*3>server.dailyRequestBudget"); const providerVerification = service.indexOf("discoverCompetitions", service.indexOf("private async ingestHistorical")); assert.ok(budgetCheck > 0); assert.ok(budgetCheck < providerVerification); });
test("failed orchestration audits retain provider requests already consumed", async () => { const service = await read("modules/football-orchestration/service.ts"); assert.match(service, /providerRequestsConsumed/); assert.match(service, /providerRequestsConsumed:audits\.length/); assert.match(service, /this\.finish\(begun\.data,"FAILED",providerRequests/); });
test("prediction provenance is persisted and publication and settlement remain separate gates", async () => { const [engine, orchestrator] = await Promise.all([read("modules/football-intelligence/shadow-pipeline/engine.ts"), read("modules/football-orchestration/service.ts")]); assert.match(engine, /current-season-first-recency-selection/); assert.match(engine, /evidence: item\.input\.evidence\.provenance/); assert.match(orchestrator, /PUBLIC_PUBLISHING_DISABLED/); assert.match(orchestrator, /SETTLEMENT_DISABLED/); });
