import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { SupabaseCheckoutRepository } from "../modules/billing/b2b-checkout-repository.ts";
import { SupabaseConsumerSubscriptionRepository } from "../modules/billing/consumer-subscription-repository.ts";
import { SupabaseLifecycleRepository } from "../modules/billing/webhook-repository.ts";

const env = environment => ({ PAYMENTS_ENABLED: "true", PAYSTACK_ENVIRONMENT: environment, SUPABASE_ENVIRONMENT: "development", SUPABASE_PROJECT_REF: "abcdefghijklmnopqrst", NEXT_PUBLIC_SUPABASE_URL: "https://abcdefghijklmnopqrst.supabase.co", SUPABASE_SERVICE_ROLE_KEY: "fixture-service-role" });
const client = () => {
  const operations = [];
  return { operations, from(table) { const state = { table, filters: [] }; const query = { select() { return query; }, eq(column, value) { state.filters.push([column, value]); return query; }, in() { return query; }, order() { return query; }, limit() { return query; }, neq() { return query; }, update(value) { operations.push({ type: "update", table, value, filters: state.filters }); return query; }, insert(value) { state.value = value; operations.push({ type: "insert", table, value }); return query; }, async maybeSingle() { operations.push({ type: "query", table, filters: state.filters }); return { data: null, error: null }; }, async single() { return { data: { ...state.value, created_at: "2026-08-14T00:00:00Z", updated_at: "2026-08-14T00:00:00Z" }, error: null }; }, then(resolve) { resolve({ data: null, error: null }); } }; return query; }, async rpc() { return { data: null, error: null }; } };
};
const transaction = environment => ({ id: `tx-${environment}`, orderId: "order-1", providerId: "paystack", environment, reference: `reference-${environment}-123`, expectedAmountMinor: 35000000, currency: "NGN", state: "initialized", createdAt: "2026-08-14T00:00:00Z", updatedAt: "2026-08-14T00:00:00Z" });

for (const environment of ["test", "live"]) test(`B2B ${environment.toUpperCase()} records use ${environment}`, async () => { const fake = client(), repository = new SupabaseCheckoutRepository(env(environment), fake); await repository.createTransaction(transaction(environment)); assert.equal(fake.operations.find(item => item.type === "insert").value.environment, environment); await repository.getTransaction("reference-123"); assert.ok(fake.operations.find(item => item.type === "query").filters.some(([key, value]) => key === "environment" && value === environment)); });

for (const environment of ["test", "live"]) test(`consumer ${environment.toUpperCase()} records use ${environment}`, async () => { const fake = client(), repository = new SupabaseConsumerSubscriptionRepository(env(environment), fake); await repository.createCustomer({ id: `customer-${environment}`, userId: "user-1", providerId: "paystack", environment, providerCustomerReference: `CUS_${environment}`, createdAt: "2026-08-14T00:00:00Z", updatedAt: "2026-08-14T00:00:00Z" }); assert.equal(fake.operations.find(item => item.type === "insert").value.environment, environment); await repository.getByProviderReference("SUB_fixture"); assert.ok(fake.operations.find(item => item.type === "query").filters.some(([key, value]) => key === "environment" && value === environment)); });

for (const environment of ["test", "live"]) test(`webhook ${environment.toUpperCase()} records and lookups use ${environment}`, async () => { const fake = client(), repository = new SupabaseLifecycleRepository(env(environment), fake), event = { id: `event-${environment}`, type: "subscription_activated", providerId: "paystack", environment, providerSubscriptionReference: "SUB_fixture", providerCustomerReference: "CUS_fixture", providerPlanReference: "PLN_fixture", amountMinor: 300000, currency: "NGN", occurredAt: "2026-08-14T00:00:00Z", providerReference: "SUB_fixture" }; await repository.claimEvent(event); assert.equal(fake.operations.find(item => item.type === "insert").value.environment, environment); await repository.getByProviderReference("SUB_fixture"); assert.ok(fake.operations.find(item => item.type === "query").filters.some(([key, value]) => key === "environment" && value === environment)); });

test("TEST and LIVE repository records cannot cross-match", async () => { const testClient = client(), liveClient = client(), testB2B = new SupabaseCheckoutRepository(env("test"), testClient), liveConsumer = new SupabaseConsumerSubscriptionRepository(env("live"), liveClient), liveLifecycle = new SupabaseLifecycleRepository(env("live"), liveClient); await assert.rejects(() => testB2B.createTransaction(transaction("live")), /environment_mismatch/); await assert.rejects(() => liveConsumer.getCustomer("user-1", "paystack", "test"), /environment_mismatch/); await assert.rejects(() => liveLifecycle.claimEvent({ id: "event-test", type: "subscription_activated", providerId: "paystack", environment: "test", providerSubscriptionReference: "SUB_fixture", providerCustomerReference: "CUS_fixture", providerPlanReference: "PLN_fixture", amountMinor: 300000, currency: "NGN", occurredAt: "2026-08-14T00:00:00Z", providerReference: "SUB_fixture" }), /environment_mismatch/); });

test("runtime repositories contain no hard-coded TEST persistence or lookup", async () => { const files = await Promise.all(["b2b-checkout-repository.ts", "consumer-subscription-repository.ts", "webhook-repository.ts"].map(name => readFile(new URL(`../modules/billing/${name}`, import.meta.url), "utf8"))); for (const source of files) assert.doesNotMatch(source, /environment\s*:\s*["']test["']|eq\(["']environment["']\s*,\s*["']test["']/); });
