import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { assertCurrency, assertMinorAmount, assertPurposeSubject, createAuthoritativePayment, isPaymentPurpose, MockPaystackGatewayProvider, parsePaymentEnvironment, paymentFoundationEnabled, resolveTrustedPrice, validateProviderResult } from "../modules/billing/foundation.ts";

const read=(path)=>readFile(new URL(`../${path}`,import.meta.url),"utf8");
test("payment purposes and purpose-specific subjects are constrained",()=>{for(const value of["business_setup","consumer_subscription","managed_platform","client_subscriber_split"])assert.equal(isPaymentPurpose(value),true);assert.equal(isPaymentPurpose("membership"),false);assert.doesNotThrow(()=>assertPurposeSubject("consumer_subscription",{type:"user",id:"00000000-0000-0000-0000-000000000001"}));assert.throws(()=>assertPurposeSubject("consumer_subscription",{type:"order",id:"x"}),/invalid_payment_subject/)});
test("trusted versioned prices use integer minor units and reject browser tampering",()=>{assert.equal(resolveTrustedPrice("b2b-launch-setup").amountMinor,35000000);assert.equal(resolveTrustedPrice("consumer-premium-monthly").amountMinor,300000);const request=createAuthoritativePayment("consumer-premium-monthly",{subject:{type:"user",id:"user-1"},providerId:"paystack",environment:"test",reference:"payment_ref_12345",customerEmail:"member@example.test",metadata:{claimedAmount:"1"}});assert.equal(request.expectedAmountMinor,300000);assert.equal(request.currency,"NGN");assertMinorAmount(request.expectedAmountMinor);assert.throws(()=>assertMinorAmount(30.5),/invalid_minor_amount/);assert.throws(()=>assertCurrency("USD"),/unsupported_currency/)});
test("mock Paystack serializes deterministically, separates environments and never calls HTTP",async()=>{const provider=new MockPaystackGatewayProvider("test"),request=createAuthoritativePayment("b2b-business-setup",{subject:{type:"order",id:"order-1"},providerId:"paystack",environment:"test",reference:"payment_ref_12346",customerEmail:"buyer@example.test"}),result=await provider.initialize(request);assert.deepEqual([result.amountMinor,result.currency,result.environment,result.reference],[75000000,"NGN","test","payment_ref_12346"]);assert.match(result.authorizationUrl,/example\.test/);await assert.rejects(()=>provider.initialize(request),/duplicate_provider_reference/);await assert.rejects(()=>new MockPaystackGatewayProvider("live").initialize(request),/provider_environment_mismatch/);await assert.rejects(()=>provider.verify("missing-reference"),/malformed_provider_response/)});
test("provider result validation rejects malformed amount, currency, reference and environment",()=>{const expected=createAuthoritativePayment("consumer-premium-monthly",{subject:{type:"user",id:"user-2"},providerId:"paystack",environment:"test",reference:"payment_ref_12347",customerEmail:"member@example.test"}),valid={providerId:"paystack",environment:"test",reference:expected.reference,state:"pending",amountMinor:expected.expectedAmountMinor,currency:"NGN"};assert.equal(validateProviderResult(valid,expected),valid);for(const patch of[{amountMinor:1},{currency:"USD"},{reference:"other"},{environment:"live"}])assert.throws(()=>validateProviderResult({...valid,...patch},expected),/provider_result_mismatch/)});
test("payment foundation is inert by default and environment parsing is explicit",()=>{assert.equal(paymentFoundationEnabled({PAYMENTS_ENABLED:"false",PAYMENT_PROVIDER:"disabled"}),false);assert.equal(paymentFoundationEnabled({PAYMENTS_ENABLED:"true",PAYMENT_PROVIDER:"paystack"}),true);assert.equal(parsePaymentEnvironment("test"),"test");assert.throws(()=>parsePaymentEnvironment("production"),/invalid_payment_environment/)});
test("migration is additive, purpose-bound, minor-unit based and keeps memberships out of the ledger",async()=>{const sql=await read("supabase/migrations/202608120001_payment_foundation.sql");for(const value of["payment_products","payment_prices","payment_customers"])assert.match(sql,new RegExp(`create table public\\.${value}`));for(const value of["business_setup","consumer_subscription","managed_platform","client_subscriber_split"])assert.match(sql,new RegExp(value));assert.match(sql,/drop not null/);assert.doesNotMatch(sql,/drop table|delete from|alter table public\.memberships/i);assert.match(sql,/unique\(provider,environment,reference\)/);assert.match(sql,/payment_transactions_purpose_subject_check/);assert.match(sql,/amount_minor bigint/)});
test("secrets remain server-only and no operational Paystack transport exists",async()=>{const[env,mock,foundation,providers]=await Promise.all([read(".env.example"),read("modules/billing/mock-paystack-provider.ts"),read("modules/billing/foundation.ts"),read("modules/billing/providers.ts")]);for(const name of["PAYSTACK_SECRET_KEY","PAYSTACK_WEBHOOK_SECRET","PAYSTACK_CONSUMER_MONTHLY_PLAN_CODE"])assert.match(env,new RegExp(`^${name}=$`,"m"));assert.doesNotMatch(env,/NEXT_PUBLIC_PAYSTACK/);assert.match(foundation,/restricted to the server runtime/);assert.doesNotMatch(`${mock}${foundation}${providers}`,/fetch\(|api\.paystack\.co|Bearer /)});
