import "tsx/esm";
import assert from "node:assert/strict";
import test from "node:test";
const { selectBoundedShadowCohort, cohortGate } = await import("../modules/football-intelligence/shadow-pipeline/cohort.ts");
const row = (id, league, tier = "STANDARD_ANALYSIS", date = "2026-08-14", rank = 1) => ({ providerFixtureId: String(id), providerCompetitionId: league, publishingTierCalculated: tier, rankingDate: date, rankingPosition: rank, confidenceScoreInternal: 1 - rank / 100 });
test("cohort is capped at ten, keeps calculated Top Picks and represents leagues", () => { const records = Array.from({ length: 20 }, (_, i) => row(100 + i, String(i % 4), i < 4 ? "TOP_PICK" : "STANDARD_ANALYSIS", `2026-08-${14 + i % 3}`, i + 1)), selected = selectBoundedShadowCohort(records); assert.equal(selected.length, 10); assert.ok(records.slice(0, 4).every((item) => selected.includes(item))); assert.equal(new Set(selected.map((item) => item.providerCompetitionId)).size, 4); });
test("cohort selection is deterministic and does not mutate calculated tiers", () => { const records = [row(3, "b", "TOP_PICK"), row(1, "a"), row(2, "b")], first = selectBoundedShadowCohort(records), second = selectBoundedShadowCohort([...records].reverse()); assert.deepEqual(first.map((item) => item.providerFixtureId), second.map((item) => item.providerFixtureId)); assert.deepEqual(records.map((item) => item.publishingTierCalculated), ["TOP_PICK", "STANDARD_ANALYSIS", "STANDARD_ANALYSIS"]); });
test("minimum prediction and league gates fail closed", () => { assert.equal(cohortGate([row(1, "a"), row(2, "a"), row(3, "a"), row(4, "a")]).passed, false); assert.equal(cohortGate([row(1, "a"), row(2, "b"), row(3, "a")]).passed, false); assert.equal(cohortGate([row(1, "a"), row(2, "b"), row(3, "a"), row(4, "b")]).passed, true); });
test("continuous cohorts may select and gate up to twenty without changing the default ten-row bound", () => { const records = Array.from({ length: 20 }, (_, index) => row(200 + index, String(index % 4), index < 4 ? "TOP_PICK" : "STANDARD_ANALYSIS", `2026-08-${14 + index % 3}`, index + 1)); assert.equal(selectBoundedShadowCohort(records, 15).length, 15); assert.equal(cohortGate(selectBoundedShadowCohort(records, 15), 20).passed, true); assert.equal(cohortGate(selectBoundedShadowCohort(records, 15)).passed, false); });
