import type { BacktestPrediction, MatchOutcome } from "@/modules/football-backtesting/domain";
import type { ConfidenceCandidate, ConfidenceFeatures, ConfidenceObservation, SelectiveMetrics } from "./domain";

const clamp = (value: number) => Math.min(1, Math.max(0, value));
const probabilityFor = (prediction: BacktestPrediction) => prediction.predictedOutcome === "home" ? prediction.probabilities.homeWin : prediction.predictedOutcome === "draw" ? prediction.probabilities.draw : prediction.probabilities.awayWin;
export function extractConfidenceFeatures(prediction: BacktestPrediction): ConfidenceFeatures { const sorted = Object.values(prediction.probabilities).sort((a, b) => b - a), entropy = -Object.values(prediction.probabilities).reduce((sum, value) => sum + value * Math.log(Math.max(value, 1e-12)), 0) / Math.log(3), expectedGoalDifference = prediction.expectedGoals.home === null || prediction.expectedGoals.away === null ? 0 : Math.abs(prediction.expectedGoals.home - prediction.expectedGoals.away); return { maximumProbability: sorted[0], secondProbability: sorted[1], topMargin: sorted[0] - sorted[1], topToBottomMargin: sorted[0] - sorted[2], normalizedEntropy: entropy, concentration: Object.values(prediction.probabilities).reduce((sum, value) => sum + value ** 2, 0), selectedOutcome: prediction.predictedOutcome, minimumHistory: Math.min(prediction.evidence.homeHistoricalMatches, prediction.evidence.awayHistoricalMatches), totalHistory: prediction.evidence.homeHistoricalMatches + prediction.evidence.awayHistoricalMatches, minimumVenue: Math.min(prediction.evidence.homeVenueSampleSize, prediction.evidence.awayVenueSampleSize), recentSample: prediction.evidence.recentSampleSize, h2hSample: prediction.evidence.h2hSampleSize, evidenceAgreement: prediction.evidence.directionalFactors ? prediction.evidence.agreeingFactors / prediction.evidence.directionalFactors : .5, absoluteStrengthDifference: Math.abs(prediction.evidence.strengthDifferential), expectedGoalDifference }; }
const geometry = (f: ConfidenceFeatures) => .45 * clamp((f.maximumProbability - 1 / 3) / .4) + .35 * clamp(f.topMargin / .4) + .2 * (1 - f.normalizedEntropy);
const evidence = (f: ConfidenceFeatures) => .65 * clamp(f.minimumHistory / 20) + .35 * clamp(f.minimumVenue / 10);
export const confidenceCandidates: readonly ConfidenceCandidate[] = [
  { id: "maximum-probability", formula: "normalized maximum 1X2 probability", score: (f) => clamp((f.maximumProbability - 1 / 3) / .4) },
  { id: "probability-geometry", formula: "45% max probability + 35% top margin + 20% inverse entropy", score: geometry },
  { id: "evidence-only", formula: "65% minimum history + 35% minimum venue sample", score: evidence },
  { id: "geometry-evidence", formula: "75% probability geometry + 25% evidence quantity", score: (f) => .75 * geometry(f) + .25 * evidence(f) },
  { id: "geometry-strength", formula: "80% probability geometry + 20% absolute v1 strength difference", score: (f) => .8 * geometry(f) + .2 * clamp(f.absoluteStrengthDifference / .4) },
  { id: "compact-composite", formula: "65% probability geometry + 20% evidence + 10% factor agreement + 5% expected-goal difference", score: (f) => .65 * geometry(f) + .2 * evidence(f) + .1 * f.evidenceAgreement + .05 * clamp(f.expectedGoalDifference / 2) },
] as const;
export const selectedConfidenceCandidate = confidenceCandidates[5];

export const makeObservations = (league: string, predictions: BacktestPrediction[]) => predictions.map((prediction) => ({ prediction, league, features: extractConfidenceFeatures(prediction) }));
export function wilsonInterval(correct: number, total: number, z = 1.96) { if (!total) return null; const p = correct / total, denominator = 1 + z ** 2 / total, centre = (p + z ** 2 / (2 * total)) / denominator, margin = z * Math.sqrt(p * (1 - p) / total + z ** 2 / (4 * total ** 2)) / denominator; return { lower: centre - margin, upper: centre + margin }; }
export function selectiveMetrics(items: ConfidenceObservation[], total: number): SelectiveMetrics {
  const average = (values: number[]) => values.length ? values.reduce((sum, value) => sum + value, 0) / values.length : null, correct = items.filter((item) => item.prediction.correct).length, outcomes: MatchOutcome[] = ["home", "draw", "away"];
  return { predictions: items.length, coverage: total ? items.length / total : 0, correct, accuracy: items.length ? correct / items.length : null, brierScore: average(items.map(({ prediction: p }) => (p.probabilities.homeWin - Number(p.actualOutcome === "home")) ** 2 + (p.probabilities.draw - Number(p.actualOutcome === "draw")) ** 2 + (p.probabilities.awayWin - Number(p.actualOutcome === "away")) ** 2)), logLoss: average(items.map(({ prediction: p }) => -Math.log(Math.max(1e-12, p.actualOutcome === "home" ? p.probabilities.homeWin : p.actualOutcome === "draw" ? p.probabilities.draw : p.probabilities.awayWin)))), selections: Object.fromEntries(outcomes.map((outcome) => [outcome, items.filter((item) => item.prediction.predictedOutcome === outcome).length])) as Record<MatchOutcome, number>, actual: Object.fromEntries(outcomes.map((outcome) => [outcome, items.filter((item) => item.prediction.actualOutcome === outcome).length])) as Record<MatchOutcome, number>, wilson95: wilsonInterval(correct, items.length) };
}
export function selectCoverage(observations: ConfidenceObservation[], candidate: ConfidenceCandidate, coverage: number) { const count = coverage >= 1 ? observations.length : Math.max(1, Math.round(observations.length * coverage)); return [...observations].sort((a, b) => candidate.score(b.features) - candidate.score(a.features) || a.prediction.fixture.kickoffAt.localeCompare(b.prediction.fixture.kickoffAt) || a.prediction.fixture.providerFixtureId.localeCompare(b.prediction.fixture.providerFixtureId)).slice(0, count); }
export function coverageCurve(observations: ConfidenceObservation[], candidate: ConfidenceCandidate, coverages = [1, .5, .4, .3, .25, .2, .1]) { return coverages.map((coverage) => selectiveMetrics(selectCoverage(observations, candidate, coverage), observations.length)); }
export function selectedProbability(item: ConfidenceObservation) { return probabilityFor(item.prediction); }
