export interface HistoricalCompetition { id: string; providerId: string; name: string; country: string | null; season: string }
export interface HistoricalTeam { id: string; providerId: string; name: string }
export interface HistoricalFixture { id: string; providerFixtureId: string; kickoffAt: string; status: string; homeTeamId: string; awayTeamId: string; homeScore: number | null; awayScore: number | null; round?: string | null; evidence?: { competitionId: string; providerCompetitionId: string; competitionName: string; season: string; source: "current-season" | "previous-season" } }
export interface HistoricalDataset { competition?: HistoricalCompetition; teams: HistoricalTeam[]; fixtures: HistoricalFixture[] }
export interface HistoricalSplit { played: number; wins: number; draws: number; losses: number; goalsFor: number; goalsAgainst: number; points: number }
export interface RateCount { count: number; rate: number | null }
export type FormResult = "W" | "D" | "L";
export type ParticipantType = "regular" | "playoff_only" | "unknown";
export type DataCompleteness = "strong" | "moderate" | "limited";

export interface RecentForm extends HistoricalSplit { sequence: FormResult[]; cleanSheets: number; failedToScore: number }
export interface TeamHistoricalFeatures extends HistoricalSplit { team: HistoricalTeam; home: HistoricalSplit; away: HistoricalSplit; recentForm: FormResult[] }
export interface TeamHistoricalProfile extends HistoricalSplit {
  team: HistoricalTeam; goalDifference: number; goalsPerMatch: number | null; goalsConcededPerMatch: number | null;
  winPercentage: number | null; drawPercentage: number | null; lossPercentage: number | null;
  home: HistoricalSplit & { goalsPerMatch: number | null }; away: HistoricalSplit & { goalsPerMatch: number | null };
  recent5: RecentForm; recent10: RecentForm;
}
export interface GoalTrends { sampleSize: number; over05: RateCount; over15: RateCount; over25: RateCount; over35: RateCount; btts: RateCount; teamScored: RateCount; teamConceded: RateCount; cleanSheet: RateCount; failedToScore: RateCount }
export interface FormStrengthFeatures { recentPointsPerGame: number | null; seasonPointsPerGame: number | null; recentGoalsForPerGame: number | null; recentGoalsAgainstPerGame: number | null; homePointsPerGame: number | null; awayPointsPerGame: number | null; recentWinRate: number | null; recentUnbeatenRate: number | null; cleanSheetRate: number | null; scoringRate: number | null }
export interface StandingRow extends HistoricalSplit { position: number; team: HistoricalTeam; goalDifference: number; participantType: ParticipantType }
export interface HeadToHeadSummary { totalMeetings: number; firstTeamWins: number; draws: number; secondTeamWins: number; firstTeamGoals: number; secondTeamGoals: number; averageTotalGoals: number | null; over15: RateCount; over25: RateCount; btts: RateCount; firstTeamCleanSheets: number; secondTeamCleanSheets: number; recentMeetings: HistoricalFixture[] }
export interface AnalysisQuality { historicalSampleSize: number; recentSampleSize: number; h2hSampleSize: number; latestDataDate: string | null; dataCompleteness: DataCompleteness }
export interface LeagueScoringBaseline { matches: number; homeGoals: number; awayGoals: number; homeGoalsPerMatch: number | null; awayGoalsPerMatch: number | null }
export interface MatchAnalysisTeam { profile: TeamHistoricalProfile; relevantForm: HistoricalSplit & { goalsPerMatch: number | null }; recent: RecentForm; trends: GoalTrends; strength: FormStrengthFeatures }
export interface MatchAnalysisInput { competition: HistoricalCompetition; season: string; homeTeam: MatchAnalysisTeam; awayTeam: MatchAnalysisTeam; h2h: HeadToHeadSummary; leagueScoring: LeagueScoringBaseline; context: AnalysisQuality }

const empty = (): HistoricalSplit => ({ played: 0, wins: 0, draws: 0, losses: 0, goalsFor: 0, goalsAgainst: 0, points: 0 });
const rate = (count: number, total: number): RateCount => ({ count, rate: total ? count / total : null });
const perGame = (value: number, played: number) => played ? value / played : null;
export const isCompletedFixture = (fixture: HistoricalFixture) => fixture.status === "finished" && fixture.homeScore !== null && fixture.awayScore !== null;
function apply(split: HistoricalSplit, goalsFor: number, goalsAgainst: number): FormResult { split.played++; split.goalsFor += goalsFor; split.goalsAgainst += goalsAgainst; if (goalsFor > goalsAgainst) { split.wins++; split.points += 3; return "W"; } if (goalsFor === goalsAgainst) { split.draws++; split.points++; return "D"; } split.losses++; return "L"; }
function teamMatches(dataset: HistoricalDataset, teamId: string, venue: "all" | "home" | "away" = "all") { return dataset.fixtures.filter((fixture) => isCompletedFixture(fixture) && (venue === "home" ? fixture.homeTeamId === teamId : venue === "away" ? fixture.awayTeamId === teamId : fixture.homeTeamId === teamId || fixture.awayTeamId === teamId)).sort((a, b) => new Date(a.kickoffAt).getTime() - new Date(b.kickoffAt).getTime()); }
function scoreFor(fixture: HistoricalFixture, teamId: string) { const home = fixture.homeTeamId === teamId; return { for: home ? fixture.homeScore! : fixture.awayScore!, against: home ? fixture.awayScore! : fixture.homeScore! }; }
function summarize(matches: HistoricalFixture[], teamId: string): HistoricalSplit { const split = empty(); for (const fixture of matches) { const goals = scoreFor(fixture, teamId); apply(split, goals.for, goals.against); } return split; }

export function calculateRecentForm(dataset: HistoricalDataset, teamId: string, lastN: number): RecentForm { const matches = teamMatches(dataset, teamId).slice(-Math.max(0, lastN)), split = empty(); const sequence: FormResult[] = []; let cleanSheets = 0, failedToScore = 0; for (const fixture of matches) { const goals = scoreFor(fixture, teamId); sequence.push(apply(split, goals.for, goals.against)); if (goals.against === 0) cleanSheets++; if (goals.for === 0) failedToScore++; } return { ...split, sequence: sequence.reverse(), cleanSheets, failedToScore }; }

export function calculateTeamHistoricalFeatures(dataset: HistoricalDataset, teamId: string, lastN = 5): TeamHistoricalFeatures { const profile = calculateTeamHistoricalProfile(dataset, teamId); return { team: profile.team, played: profile.played, wins: profile.wins, draws: profile.draws, losses: profile.losses, goalsFor: profile.goalsFor, goalsAgainst: profile.goalsAgainst, points: profile.points, home: profile.home, away: profile.away, recentForm: calculateRecentForm(dataset, teamId, lastN).sequence }; }

export function calculateTeamHistoricalProfile(dataset: HistoricalDataset, teamId: string): TeamHistoricalProfile { const team = dataset.teams.find((item) => item.id === teamId); if (!team) throw new Error("Historical team was not found."); const overall = summarize(teamMatches(dataset, teamId), teamId), homeBase = summarize(teamMatches(dataset, teamId, "home"), teamId), awayBase = summarize(teamMatches(dataset, teamId, "away"), teamId); return { team, ...overall, goalDifference: overall.goalsFor - overall.goalsAgainst, goalsPerMatch: perGame(overall.goalsFor, overall.played), goalsConcededPerMatch: perGame(overall.goalsAgainst, overall.played), winPercentage: perGame(overall.wins, overall.played), drawPercentage: perGame(overall.draws, overall.played), lossPercentage: perGame(overall.losses, overall.played), home: { ...homeBase, goalsPerMatch: perGame(homeBase.goalsFor, homeBase.played) }, away: { ...awayBase, goalsPerMatch: perGame(awayBase.goalsFor, awayBase.played) }, recent5: calculateRecentForm(dataset, teamId, 5), recent10: calculateRecentForm(dataset, teamId, 10) }; }

const playoffRound = (round: string | null | undefined) => Boolean(round && /play[ -]?off|relegation round|promotion/i.test(round));
export function classifyParticipants(dataset: HistoricalDataset): Map<string, ParticipantType> { const result = new Map<string, ParticipantType>(); for (const team of dataset.teams) { const appearances = dataset.fixtures.filter((fixture) => isCompletedFixture(fixture) && (fixture.homeTeamId === team.id || fixture.awayTeamId === team.id)); const known = appearances.filter((fixture) => fixture.round?.trim()); result.set(team.id, !appearances.length || !known.length ? "unknown" : known.some((fixture) => !playoffRound(fixture.round)) ? "regular" : "playoff_only"); } return result; }

export function calculateHistoricalStandings(dataset: HistoricalDataset): StandingRow[] { const types = classifyParticipants(dataset); const regular = dataset.teams.filter((team) => types.get(team.id) === "regular"); const regularIds = new Set(regular.map((team) => team.id)); const leagueFixtures = dataset.fixtures.filter((fixture) => isCompletedFixture(fixture) && regularIds.has(fixture.homeTeamId) && regularIds.has(fixture.awayTeamId) && !playoffRound(fixture.round)); return regular.map((team) => { const split = summarize(leagueFixtures.filter((fixture) => fixture.homeTeamId === team.id || fixture.awayTeamId === team.id), team.id); return { position: 0, team, ...split, goalDifference: split.goalsFor - split.goalsAgainst, participantType: "regular" as const }; }).sort((a, b) => b.points - a.points || b.goalDifference - a.goalDifference || b.goalsFor - a.goalsFor).map((row, index) => ({ ...row, position: index + 1 })); }

export function getHeadToHeadHistory(dataset: HistoricalDataset, firstTeamId: string, secondTeamId: string, limit = 10) { return dataset.fixtures.filter((fixture) => isCompletedFixture(fixture) && ((fixture.homeTeamId === firstTeamId && fixture.awayTeamId === secondTeamId) || (fixture.homeTeamId === secondTeamId && fixture.awayTeamId === firstTeamId))).sort((a, b) => new Date(b.kickoffAt).getTime() - new Date(a.kickoffAt).getTime()).slice(0, Math.max(0, limit)); }
export function calculateHeadToHead(dataset: HistoricalDataset, firstTeamId: string, secondTeamId: string, limit = 10): HeadToHeadSummary { const meetings = getHeadToHeadHistory(dataset, firstTeamId, secondTeamId, Number.MAX_SAFE_INTEGER); let firstTeamWins = 0, draws = 0, secondTeamWins = 0, firstTeamGoals = 0, secondTeamGoals = 0, over15 = 0, over25 = 0, btts = 0, firstTeamCleanSheets = 0, secondTeamCleanSheets = 0; for (const fixture of meetings) { const firstIsHome = fixture.homeTeamId === firstTeamId, first = firstIsHome ? fixture.homeScore! : fixture.awayScore!, second = firstIsHome ? fixture.awayScore! : fixture.homeScore!; firstTeamGoals += first; secondTeamGoals += second; if (first > second) firstTeamWins++; else if (first === second) draws++; else secondTeamWins++; if (first + second > 1.5) over15++; if (first + second > 2.5) over25++; if (first > 0 && second > 0) btts++; if (second === 0) firstTeamCleanSheets++; if (first === 0) secondTeamCleanSheets++; } return { totalMeetings: meetings.length, firstTeamWins, draws, secondTeamWins, firstTeamGoals, secondTeamGoals, averageTotalGoals: meetings.length ? (firstTeamGoals + secondTeamGoals) / meetings.length : null, over15: rate(over15, meetings.length), over25: rate(over25, meetings.length), btts: rate(btts, meetings.length), firstTeamCleanSheets, secondTeamCleanSheets, recentMeetings: meetings.slice(0, Math.max(0, limit)) }; }

export function calculateGoalTrends(dataset: HistoricalDataset, teamId: string, options: { venue?: "all" | "home" | "away"; recentN?: number } = {}): GoalTrends { let matches = teamMatches(dataset, teamId, options.venue); if (options.recentN !== undefined) matches = matches.slice(-Math.max(0, options.recentN)); let over05 = 0, over15 = 0, over25 = 0, over35 = 0, btts = 0, teamScored = 0, teamConceded = 0, cleanSheet = 0, failedToScore = 0; for (const fixture of matches) { const goals = scoreFor(fixture, teamId), total = goals.for + goals.against; if (total > .5) over05++; if (total > 1.5) over15++; if (total > 2.5) over25++; if (total > 3.5) over35++; if (goals.for > 0 && goals.against > 0) btts++; if (goals.for > 0) teamScored++; else failedToScore++; if (goals.against > 0) teamConceded++; else cleanSheet++; } const total = matches.length; return { sampleSize: total, over05: rate(over05, total), over15: rate(over15, total), over25: rate(over25, total), over35: rate(over35, total), btts: rate(btts, total), teamScored: rate(teamScored, total), teamConceded: rate(teamConceded, total), cleanSheet: rate(cleanSheet, total), failedToScore: rate(failedToScore, total) }; }

export function calculateFormStrength(dataset: HistoricalDataset, teamId: string, recentN = 5): FormStrengthFeatures { const profile = calculateTeamHistoricalProfile(dataset, teamId), recent = calculateRecentForm(dataset, teamId, recentN); return { recentPointsPerGame: perGame(recent.points, recent.played), seasonPointsPerGame: perGame(profile.points, profile.played), recentGoalsForPerGame: perGame(recent.goalsFor, recent.played), recentGoalsAgainstPerGame: perGame(recent.goalsAgainst, recent.played), homePointsPerGame: perGame(profile.home.points, profile.home.played), awayPointsPerGame: perGame(profile.away.points, profile.away.played), recentWinRate: perGame(recent.wins, recent.played), recentUnbeatenRate: recent.played ? (recent.wins + recent.draws) / recent.played : null, cleanSheetRate: recent.played ? recent.cleanSheets / recent.played : null, scoringRate: recent.played ? (recent.played - recent.failedToScore) / recent.played : null }; }

export function classifyDataCompleteness(historical: number, recent: number, h2h: number): DataCompleteness { return historical >= 20 && recent >= 5 && h2h >= 3 ? "strong" : historical >= 8 && recent >= 3 && h2h >= 1 ? "moderate" : "limited"; }
export function buildMatchAnalysisInput(dataset: HistoricalDataset, homeTeamId: string, awayTeamId: string, options: { analysisDate?: string; recentN?: number } = {}): MatchAnalysisInput { if (!dataset.competition) throw new Error("Historical competition identity is required."); const recentN = options.recentN ?? 5, cutoff = options.analysisDate ? new Date(options.analysisDate).getTime() : Number.POSITIVE_INFINITY, scoped: HistoricalDataset = { ...dataset, fixtures: dataset.fixtures.filter((fixture) => new Date(fixture.kickoffAt).getTime() < cutoff) }, completed = scoped.fixtures.filter(isCompletedFixture); const homeProfile = calculateTeamHistoricalProfile(scoped, homeTeamId), awayProfile = calculateTeamHistoricalProfile(scoped, awayTeamId), homeRecent = calculateRecentForm(scoped, homeTeamId, recentN), awayRecent = calculateRecentForm(scoped, awayTeamId, recentN), h2h = calculateHeadToHead(scoped, homeTeamId, awayTeamId); const historicalSampleSize = Math.min(homeProfile.played, awayProfile.played), recentSampleSize = Math.min(homeRecent.played, awayRecent.played), latest = completed.map((fixture) => fixture.kickoffAt).sort().at(-1) ?? null, homeGoals = completed.reduce((sum, fixture) => sum + fixture.homeScore!, 0), awayGoals = completed.reduce((sum, fixture) => sum + fixture.awayScore!, 0); return { competition: dataset.competition, season: dataset.competition.season, homeTeam: { profile: homeProfile, relevantForm: homeProfile.home, recent: homeRecent, trends: calculateGoalTrends(scoped, homeTeamId, { venue: "home", recentN }), strength: calculateFormStrength(scoped, homeTeamId, recentN) }, awayTeam: { profile: awayProfile, relevantForm: awayProfile.away, recent: awayRecent, trends: calculateGoalTrends(scoped, awayTeamId, { venue: "away", recentN }), strength: calculateFormStrength(scoped, awayTeamId, recentN) }, h2h, leagueScoring: { matches: completed.length, homeGoals, awayGoals, homeGoalsPerMatch: perGame(homeGoals, completed.length), awayGoalsPerMatch: perGame(awayGoals, completed.length) }, context: { historicalSampleSize, recentSampleSize, h2hSampleSize: h2h.totalMeetings, latestDataDate: latest, dataCompleteness: classifyDataCompleteness(historicalSampleSize, recentSampleSize, h2h.totalMeetings) } }; }

export function getParticipatingTeams(dataset: HistoricalDataset) { const ids = new Set(dataset.fixtures.flatMap((fixture) => [fixture.homeTeamId, fixture.awayTeamId])); return dataset.teams.filter((team) => ids.has(team.id)); }
