if(typeof window!=="undefined")throw new Error("B2B checkout is restricted to the server runtime.");
import { randomBytes, randomUUID } from "node:crypto";
import type { BusinessPackageId, BusinessPaymentMethod, BusinessPaymentWebhookEvent, BusinessSetupOrder, BusinessSetupTransaction, InitializePaymentInput, PaymentEnvironment, ProviderPaymentResult } from "./domain";
import type { PaymentGatewayProvider } from "./providers";
import { resolveTrustedPrice, validateProviderResult } from "./foundation.ts";

export const BUSINESS_TERMS_VERSION="2026-08-12";export const REFUND_POLICY_VERSION="2026-08-12";
const products:Record<BusinessPackageId,{key:string;name:string;standard:number}>={launch:{key:"b2b-launch-setup",name:"Launch Edition",standard:50000000},business:{key:"b2b-business-setup",name:"Business Edition",standard:100000000}};
export interface CheckoutRepository{findOrderByIdempotencyKey(key:string):Promise<BusinessSetupOrder|null>;createOrder(order:BusinessSetupOrder,key:string):Promise<BusinessSetupOrder>;getOrder(id:string):Promise<BusinessSetupOrder|null>;createTransaction(transaction:BusinessSetupTransaction):Promise<BusinessSetupTransaction>;getTransaction(reference:string):Promise<BusinessSetupTransaction|null>;getTransactionByOrderId(orderId:string):Promise<BusinessSetupTransaction|null>;saveTransaction(transaction:BusinessSetupTransaction):Promise<void>;markPaid(orderId:string,transaction:BusinessSetupTransaction):Promise<BusinessSetupOrder>;markFailed(orderId:string,transaction:BusinessSetupTransaction):Promise<BusinessSetupOrder>}
export interface CheckoutInput{packageId:string;name:string;email:string;phone?:string;brandName?:string;acceptBusinessTerms:boolean;acceptRefundPolicy:boolean;paymentMethod:BusinessPaymentMethod;idempotencyKey:string;userId?:string}
const clean=(value:string|undefined,max:number)=>value?.trim().slice(0,max)||undefined;
export function validateCheckoutInput(input:CheckoutInput){if(!(input.packageId in products))throw new Error("invalid_package");if(!clean(input.name,120)||!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(input.email))throw new Error("invalid_buyer_details");if(!input.acceptBusinessTerms||!input.acceptRefundPolicy)throw new Error("terms_required");if(!/^[A-Za-z0-9_-]{16,100}$/.test(input.idempotencyKey))throw new Error("invalid_idempotency_key");if(!["manual-bank","paystack"].includes(input.paymentMethod))throw new Error("invalid_payment_method")}
export function createPaymentReference(){return`B2B_${Date.now().toString(36)}_${randomBytes(18).toString("base64url")}`}
export class BusinessSetupCheckoutService{private repository:CheckoutRepository;private provider:PaymentGatewayProvider;private environment:PaymentEnvironment;constructor(repository:CheckoutRepository,provider:PaymentGatewayProvider,environment:PaymentEnvironment="test"){this.repository=repository;this.provider=provider;this.environment=environment}
 async initialize(input:CheckoutInput){validateCheckoutInput(input);if(this.provider.environment!==this.environment)throw new Error("provider_environment_mismatch");if(input.paymentMethod==="paystack"&&!input.userId)throw new Error("authentication_required");const existing=await this.repository.findOrderByIdempotencyKey(input.idempotencyKey);if(existing){const tx=existing.paymentMethod==="paystack"?await this.repository.getTransactionByOrderId(existing.id):null;return{order:existing,transaction:tx,authorizationUrl:tx?.authorizationUrl}}
 const selected=products[input.packageId as BusinessPackageId],price=resolveTrustedPrice(selected.key),now=new Date().toISOString(),orderId=randomUUID();const order:BusinessSetupOrder={id:orderId,orderNumber:`9FA-${Date.now().toString(36).toUpperCase()}-${randomBytes(3).toString("hex").toUpperCase()}`,userId:input.userId,buyer:{name:clean(input.name,120)!,email:input.email.trim().toLowerCase(),phone:clean(input.phone,40),brandName:clean(input.brandName,120)},packageId:input.packageId as BusinessPackageId,purpose:"business_setup",productKey:selected.key,priceId:price.id,standardAmountMinor:selected.standard,chargedAmountMinor:price.amountMinor,currency:"NGN",promotionId:price.kind==="promotional"?price.id:undefined,businessTermsVersion:BUSINESS_TERMS_VERSION,refundPolicyVersion:REFUND_POLICY_VERSION,acceptedAt:now,paymentMethod:input.paymentMethod,status:"pending_payment",onboardingStatus:"awaiting_payment",...(input.paymentMethod==="manual-bank"?{manualPaymentStatus:"awaiting_manual_confirmation"as const}:{}),createdAt:now,updatedAt:now,fulfillmentCount:0};await this.repository.createOrder(order,input.idempotencyKey);if(input.paymentMethod==="manual-bank")return{order,transaction:null,authorizationUrl:undefined};
 const reference=createPaymentReference(),request:InitializePaymentInput={purpose:"business_setup",subject:{type:"order",id:order.id},providerId:"paystack",environment:this.environment,reference,expectedAmountMinor:order.chargedAmountMinor,currency:"NGN",customerEmail:order.buyer.email,metadata:{order_id:order.id,product_key:order.productKey,price_id:order.priceId}};const result=validateProviderResult(await this.provider.initialize(request),request);if(!result.authorizationUrl)throw new Error("invalid_provider_response");const transaction:BusinessSetupTransaction={id:randomUUID(),orderId:order.id,providerId:"paystack",environment:this.environment,reference,expectedAmountMinor:order.chargedAmountMinor,currency:"NGN",state:"initialized",authorizationUrl:result.authorizationUrl,createdAt:now,updatedAt:now};await this.repository.createTransaction(transaction);return{order:{...order,providerReference:reference},transaction,authorizationUrl:result.authorizationUrl}}
 async verify(reference:string,ownerUserId?:string){if(!/^[A-Za-z0-9_-]{12,100}$/.test(reference))throw new Error("invalid_reference");const transaction=await this.repository.getTransaction(reference);if(!transaction)throw new Error("transaction_not_found");const order=await this.repository.getOrder(transaction.orderId);if(!order||order.purpose!=="business_setup"||order.paymentMethod!=="paystack")throw new Error("invalid_order_relationship");if(ownerUserId&&order.userId!==ownerUserId)throw new Error("order_access_denied");if(order.status==="paid")return{order,transaction};let result:ProviderPaymentResult;try{result=await this.provider.verify(reference)}catch{await this.fail(order,transaction,"Provider verification failed.");throw new Error("payment_verification_failed")};this.validateVerification(result,reference,order);if(result.state!=="succeeded"){await this.fail(order,transaction,"Provider reported an unsuccessful payment.");throw new Error("payment_not_successful")}transaction.state="succeeded";transaction.paidAmountMinor=result.amountMinor;transaction.verifiedAt=new Date().toISOString();transaction.updatedAt=transaction.verifiedAt;await this.repository.saveTransaction(transaction);return{order:await this.repository.markPaid(order.id,transaction),transaction}}
 async processWebhook(event:BusinessPaymentWebhookEvent){if(event.environment!==this.environment||event.providerId!=="paystack")throw new Error("wrong_environment");const transaction=await this.repository.getTransaction(event.reference);if(!transaction)throw new Error("transaction_not_found");const order=await this.repository.getOrder(transaction.orderId);if(!order||order.purpose!=="business_setup"||order.paymentMethod!=="paystack")throw new Error("invalid_order_relationship");if(event.orderId!==order.id||event.productKey!==order.productKey||event.priceId!==order.priceId||event.customerEmail.toLowerCase()!==order.buyer.email.toLowerCase())throw new Error("wrong_order_customer");if(event.amountMinor!==order.chargedAmountMinor)throw new Error("wrong_amount");if(event.currency!==order.currency)throw new Error("wrong_currency");if(order.status==="paid"||event.type==="payment_failed"&&order.status==="payment_failed"&&transaction.state==="failed")return{order,transaction};if(event.type==="payment_failed"){await this.fail(order,transaction,"Signed provider failure event.");return{order:(await this.repository.getOrder(order.id))!,transaction}}return this.verify(event.reference)}
 private validateVerification(result:ProviderPaymentResult,reference:string,order:BusinessSetupOrder){if(result.environment!==this.environment)throw new Error("wrong_environment");if(result.reference!==reference)throw new Error("wrong_reference");if(result.currency!==order.currency)throw new Error("wrong_currency");if(result.amountMinor!==order.chargedAmountMinor)throw new Error("wrong_amount");if(result.customerEmail&&result.customerEmail.toLowerCase()!==order.buyer.email.toLowerCase())throw new Error("wrong_customer");if(result.metadata&&(result.metadata.order_id!==order.id||result.metadata.product_key!==order.productKey||result.metadata.price_id!==order.priceId))throw new Error("wrong_order_metadata")}
 private async fail(order:BusinessSetupOrder,transaction:BusinessSetupTransaction,message:string){if(order.status==="paid")return;transaction.state="failed";transaction.providerMessage=message;transaction.updatedAt=new Date().toISOString();await this.repository.saveTransaction(transaction);await this.repository.markFailed(order.id,transaction)}
}
