if(typeof window!=="undefined")throw new Error("B2B payment webhooks are restricted to the server runtime.");
import type{BusinessPaymentWebhookEvent}from"./domain";
import{BusinessSetupCheckoutService}from"./b2b-checkout.ts";
import{SupabaseCheckoutRepository}from"./b2b-checkout-repository.ts";
import{createConfiguredPaystackProvider}from"./paystack-provider.ts";

type Json=Record<string,unknown>;const object=(value:unknown):Json=>{if(!value||typeof value!=="object"||Array.isArray(value))throw new Error("malformed_webhook_payload");return value as Json},text=(value:unknown)=>typeof value==="string"&&value?value:null,integer=(value:unknown)=>typeof value==="number"&&Number.isSafeInteger(value)&&value>0?value:null;
export function normalizeB2BPaystackWebhook(rawBody:string):BusinessPaymentWebhookEvent|null{let parsed:unknown;try{parsed=JSON.parse(rawBody)}catch{throw new Error("malformed_webhook_payload")}const root=object(parsed),name=text(root.event);if(name!=="charge.success"&&name!=="charge.failed")return null;const data=object(root.data),metadata=object(data.metadata),customer=object(data.customer),reference=text(data.reference),amountMinor=integer(data.amount),currency=text(data.currency),customerEmail=text(customer.email),orderId=text(metadata.order_id),productKey=text(metadata.product_key),priceId=text(metadata.price_id),occurredAt=text(data.paid_at)??text(data.created_at)??text(data.createdAt)??text(root.created_at)??text(root.createdAt),id=text(root.id)??`${name}:${reference}`;if(text(data.domain)!=="test")throw new Error("wrong_provider_environment");if(!id||!reference||!/^B2B_[A-Za-z0-9_-]+$/.test(reference)||!amountMinor||currency!=="NGN"||!customerEmail||!orderId||!productKey||!priceId||!occurredAt||Number.isNaN(Date.parse(occurredAt)))throw new Error("malformed_webhook_payload");return{id,type:name==="charge.success"?"payment_succeeded":"payment_failed",providerId:"paystack",environment:"test",reference,amountMinor,currency:"NGN",customerEmail,orderId,productKey,priceId,occurredAt:new Date(occurredAt).toISOString()}}
export interface B2BWebhookDependencies{hasTransaction(reference:string):Promise<boolean>;process(event:BusinessPaymentWebhookEvent):Promise<unknown>}
const dependencies=(env:NodeJS.ProcessEnv):B2BWebhookDependencies=>{const repository=new SupabaseCheckoutRepository(env),service=new BusinessSetupCheckoutService(repository,createConfiguredPaystackProvider(env),"test");return{hasTransaction:async reference=>Boolean(await repository.getTransaction(reference)),process:event=>service.processWebhook(event)}};
export async function resolveB2BPaystackWebhook(rawBody:string,provided?:B2BWebhookDependencies){const event=normalizeB2BPaystackWebhook(rawBody);if(!event)return null;const deps=provided??dependencies(process.env);if(!await deps.hasTransaction(event.reference))return null;await deps.process(event);return{accepted:true,eventId:event.id,kind:"business"as const}}
