if (typeof window !== "undefined") throw new Error("Consumer subscription persistence is restricted to the server runtime.");
import { createClient, type SupabaseClient } from "@supabase/supabase-js";
import { requireServiceRoleSupabaseConfig } from "../../lib/supabase/server-environment.ts";
import { parsePaymentEnvironment } from "./foundation.ts";
import { requirePaymentsEnabled } from "./runtime-config.ts";
import type { ConsumerBillingCustomer, ConsumerSubscription, PaymentEnvironment } from "./domain";
import type { ConsumerSubscriptionRepository } from "./consumer-subscriptions";

type Row = Record<string, unknown>;
const text = (row: Row, key: string) => String(row[key] ?? "");
const rowEnvironment = (row: Row): PaymentEnvironment => parsePaymentEnvironment(text(row, "environment"));
const mapSubscription = (row: Row): ConsumerSubscription => ({
  id: text(row, "id"), userId: text(row, "user_id"), billingCustomerId: text(row, "billing_customer_id"), productKey: "consumer-premium-monthly", priceId: text(row, "price_id"), providerId: "paystack", environment: rowEnvironment(row), providerPlanReference: text(row, "provider_plan_reference"), providerCustomerReference: text(row, "provider_customer_reference"), initialPaymentReference: text(row, "initial_payment_reference"), ...(row.provider_subscription_reference ? { providerSubscriptionReference: text(row, "provider_subscription_reference") } : {}), amountMinor: Number(row.amount_minor), currency: "NGN", billingInterval: "monthly", status: row.status as ConsumerSubscription["status"], entitlementStatus: row.entitlement_status as ConsumerSubscription["entitlementStatus"], startedAt: row.started_at ? text(row, "started_at") : undefined, currentPeriodStart: row.current_period_start ? text(row, "current_period_start") : undefined, currentPeriodEnd: row.current_period_end ? text(row, "current_period_end") : undefined, nextBillingAt: row.next_billing_at ? text(row, "next_billing_at") : undefined, cancelledAt: row.cancelled_at ? text(row, "cancelled_at") : undefined, cancelAtPeriodEnd: Boolean(row.cancel_at_period_end), createdAt: text(row, "created_at"), updatedAt: text(row, "updated_at")
});
const mapCustomer = (row: Row): ConsumerBillingCustomer => ({ id: text(row, "id"), userId: text(row, "subject_id"), providerId: "paystack", environment: rowEnvironment(row), providerCustomerReference: text(row, "provider_customer_reference"), createdAt: text(row, "created_at"), updatedAt: text(row, "updated_at") });

export class SupabaseConsumerSubscriptionRepository implements ConsumerSubscriptionRepository {
  private db: SupabaseClient; private env: NodeJS.ProcessEnv; private environment: PaymentEnvironment;
  constructor(env: NodeJS.ProcessEnv = process.env, client?: SupabaseClient) { this.env = env; this.environment = parsePaymentEnvironment(env.PAYSTACK_ENVIRONMENT); const { url, serviceRoleKey } = requireServiceRoleSupabaseConfig(env); this.db = client ?? createClient(url, serviceRoleKey, { auth: { persistSession: false, autoRefreshToken: false } }); }
  async getCustomer(userId: string, provider: string, environment: PaymentEnvironment) { if (environment !== this.environment) throw new Error("provider_environment_mismatch"); const { data, error } = await this.db.from("payment_customers").select("*").eq("subject_type", "user").eq("subject_id", userId).eq("provider", provider).eq("environment", this.environment).maybeSingle(); if (error) throw new Error("customer_read_failed"); return data ? mapCustomer(data) : null; }
  async createCustomer(value: ConsumerBillingCustomer) { requirePaymentsEnabled(this.env); if (value.environment !== this.environment) throw new Error("provider_environment_mismatch"); const { data, error } = await this.db.from("payment_customers").insert({ id: value.id, subject_type: "user", subject_id: value.userId, provider: value.providerId, environment: this.environment, provider_customer_reference: value.providerCustomerReference }).select("*").single(); if (error) throw new Error("customer_create_failed"); return mapCustomer(data); }
  async findCheckout(key: string) { const { data, error } = await this.db.from("consumer_subscription_checkouts").select("provider_reference,subscription_id").eq("environment", this.environment).eq("idempotency_key", key).maybeSingle(); if (error) throw new Error("checkout_read_failed"); if (!data) return null; const subscription = await this.getByInitialPaymentReference(data.provider_reference); return subscription ? { reference: data.provider_reference, subscriptionId: data.subscription_id } : null; }
  async saveCheckout(key: string, value: { reference: string; subscriptionId: string }) { requirePaymentsEnabled(this.env); const subscription = await this.getByInitialPaymentReference(value.reference); if (!subscription) throw new Error("subscription_not_found"); const { error } = await this.db.from("consumer_subscription_checkouts").insert({ user_id: subscription.userId, environment: this.environment, idempotency_key: key, subscription_id: value.subscriptionId, provider_reference: value.reference }); if (error && error.code !== "23505") throw new Error("checkout_create_failed"); }
  async getByUser(userId: string) { const { data, error } = await this.db.from("consumer_subscriptions").select("*").eq("provider", "paystack").eq("environment", this.environment).eq("user_id", userId).in("status", ["pending", "active", "past_due"]).order("created_at", { ascending: false }).limit(1).maybeSingle(); if (error) throw new Error("subscription_read_failed"); return data ? mapSubscription(data) : null; }
  async getByInitialPaymentReference(reference: string) { return this.one("initial_payment_reference", reference); }
  async getByProviderReference(reference: string) { return this.one("provider_subscription_reference", reference); }
  async getPendingByCustomerAndPlan(customerReference: string, planReference: string) { const { data, error } = await this.db.from("consumer_subscriptions").select("*").eq("provider", "paystack").eq("environment", this.environment).eq("status", "pending").eq("provider_customer_reference", customerReference).eq("provider_plan_reference", planReference).maybeSingle(); if (error) throw new Error("subscription_read_failed"); return data ? mapSubscription(data) : null; }
  async createSubscription(value: ConsumerSubscription) { requirePaymentsEnabled(this.env); if (value.environment !== this.environment) throw new Error("provider_environment_mismatch"); const { data: product, error: productError } = await this.db.from("payment_products").select("id").eq("product_key", value.productKey).eq("active", true).single(); if (productError) throw new Error("trusted_product_not_found"); const { data: price, error: priceError } = await this.db.from("payment_prices").select("id").eq("product_id", product.id).eq("active", true).eq("kind", "current").eq("amount_minor", value.amountMinor).eq("currency", value.currency).eq("billing_interval", value.billingInterval).single(); if (priceError) throw new Error("trusted_price_not_found"); const { data, error } = await this.db.from("consumer_subscriptions").insert({ id: value.id, user_id: value.userId, billing_customer_id: value.billingCustomerId, product_id: product.id, price_id: price.id, provider: value.providerId, environment: this.environment, provider_plan_reference: value.providerPlanReference, provider_customer_reference: value.providerCustomerReference, initial_payment_reference: value.initialPaymentReference, provider_subscription_reference: null, amount_minor: value.amountMinor, currency: value.currency, billing_interval: value.billingInterval, status: "pending", entitlement_status: "inactive", cancel_at_period_end: false }).select("*").single(); if (error) throw new Error("subscription_create_failed"); return mapSubscription(data); }
  async saveSubscription(value: ConsumerSubscription) { requirePaymentsEnabled(this.env); if (value.environment !== this.environment) throw new Error("provider_environment_mismatch"); const { error } = await this.db.from("consumer_subscriptions").update({ provider_subscription_reference: value.providerSubscriptionReference ?? null, status: value.status, entitlement_status: value.entitlementStatus, started_at: value.startedAt ?? null, current_period_start: value.currentPeriodStart ?? null, current_period_end: value.currentPeriodEnd ?? null, next_billing_at: value.nextBillingAt ?? null, cancel_at_period_end: value.cancelAtPeriodEnd, cancelled_at: value.cancelledAt ?? null }).eq("environment", this.environment).eq("id", value.id); if (error) throw new Error("subscription_update_failed"); }
  async claimProviderEvent(reference: string) { requirePaymentsEnabled(this.env); const { error } = await this.db.from("consumer_subscription_events").insert({ provider: "paystack", environment: this.environment, provider_event_reference: reference, event_type: "controlled_verification" }); if (!error) return true; if (error.code === "23505") return false; throw new Error("event_claim_failed"); }
  private async one(column: string, value: string) { const { data, error } = await this.db.from("consumer_subscriptions").select("*").eq("provider", "paystack").eq("environment", this.environment).eq(column, value).maybeSingle(); if (error) throw new Error("subscription_read_failed"); return data ? mapSubscription(data) : null; }
}
