export type PaymentProviderId="manual-bank"|"paystack"|"flutterwave"|"stripe"|string;export type PaymentMethodType="bank-transfer"|"card"|"wallet"|"disabled";export type PaymentStatus="pending-payment"|"payment-submitted"|"payment-verified"|"payment-rejected"|"cancelled"|"completed";export type BillingInterval="monthly"|"yearly"|"lifetime";
export interface Money{amount:number;currency:string}export interface PaymentMethod{id:string;providerId:PaymentProviderId;type:PaymentMethodType;label:string;enabled:boolean;availability:"available"|"coming-soon"|"future"}
export interface OrderCustomer{name:string;email:string;phone?:string;brandName?:string}export interface PlatformSetupOrder{id:string;packageId:string;packageName:string;customer:OrderCustomer;total:Money;status:PaymentStatus;paymentProviderId:PaymentProviderId;createdAt:string;updatedAt:string}
export interface Invoice{id:string;orderId:string;number:string;total:Money;status:"draft"|"issued"|"paid"|"void";issuedAt?:string;dueAt?:string}export interface Transaction{id:string;orderId:string;providerId:PaymentProviderId;amount:Money;status:PaymentStatus;providerReference?:string;createdAt:string}export interface Subscription{id:string;userId:string;planId:string;interval:BillingInterval;status:"inactive"|"active"|"past-due"|"cancelled";providerId?:PaymentProviderId}
export interface PaymentRequest{orderId:string;amount:Money;description:string;customer:OrderCustomer}export interface PaymentResult{providerId:PaymentProviderId;status:PaymentStatus;reference:string;instructions?:string}
export interface TenantPaymentSettings{tenantId:string;enabled:boolean;providers:PaymentProviderId[];defaultProvider?:PaymentProviderId}

export const paymentPurposes=["business_setup","consumer_subscription","managed_platform","client_subscriber_split"]as const;
export type PaymentPurpose=typeof paymentPurposes[number];export type PaymentEnvironment="test"|"live";export type PaymentSubjectType="order"|"user"|"business_client"|"client_platform";export type PaymentTransactionState="initialized"|"pending"|"succeeded"|"failed"|"cancelled";
export interface PaymentSubject{type:PaymentSubjectType;id:string}export interface PaymentProduct{id:string;key:string;purpose:PaymentPurpose;name:string;active:boolean}export interface PaymentPrice{id:string;productKey:string;version:number;kind:"standard"|"promotional"|"current";amountMinor:number;currency:string;interval:"one_time"|"monthly";active:boolean;effectiveFrom:string;effectiveUntil?:string;providerPlanReference?:string}
export interface PaymentCustomerMapping{id:string;subject:PaymentSubject;providerId:PaymentProviderId;environment:PaymentEnvironment;providerCustomerReference:string;metadata?:Record<string,string>}
export interface GeneralizedPaymentTransaction{id:string;purpose:PaymentPurpose;subject:PaymentSubject;providerId:PaymentProviderId;environment:PaymentEnvironment;providerReference:string;productId?:string;priceId?:string;expectedAmountMinor:number;paidAmountMinor?:number;currency:string;state:PaymentTransactionState;createdAt:string;updatedAt:string}
export interface InitializePaymentInput{purpose:PaymentPurpose;subject:PaymentSubject;providerId:PaymentProviderId;environment:PaymentEnvironment;reference:string;expectedAmountMinor:number;currency:string;customerEmail:string;metadata?:Record<string,string>}
export interface ProviderPaymentResult{providerId:PaymentProviderId;environment:PaymentEnvironment;reference:string;state:PaymentTransactionState;amountMinor:number;currency:string;authorizationUrl?:string;providerCustomerReference?:string}
export interface ProviderSubscriptionRequest{providerCustomerReference:string;providerPlanReference:string;environment:PaymentEnvironment;localSubject:PaymentSubject}export interface ProviderSubscriptionResult{providerSubscriptionReference:string;state:"pending"|"active"|"non-renewing"|"cancelled";environment:PaymentEnvironment}
