export type PaymentProviderId="manual-bank"|"paystack"|"flutterwave"|"stripe"|string;export type PaymentMethodType="bank-transfer"|"card"|"wallet"|"disabled";export type PaymentStatus="pending-payment"|"payment-submitted"|"payment-verified"|"payment-rejected"|"cancelled"|"completed";export type BillingInterval="monthly"|"yearly"|"lifetime";
export interface Money{amount:number;currency:string}export interface PaymentMethod{id:string;providerId:PaymentProviderId;type:PaymentMethodType;label:string;enabled:boolean;availability:"available"|"coming-soon"|"future"}
export interface OrderCustomer{name:string;email:string;phone?:string;brandName?:string}export interface PlatformSetupOrder{id:string;packageId:string;packageName:string;customer:OrderCustomer;total:Money;status:PaymentStatus;paymentProviderId:PaymentProviderId;createdAt:string;updatedAt:string}
export interface Invoice{id:string;orderId:string;number:string;total:Money;status:"draft"|"issued"|"paid"|"void";issuedAt?:string;dueAt?:string}export interface Transaction{id:string;orderId:string;providerId:PaymentProviderId;amount:Money;status:PaymentStatus;providerReference?:string;createdAt:string}export interface Subscription{id:string;userId:string;planId:string;interval:BillingInterval;status:"inactive"|"active"|"past-due"|"cancelled";providerId?:PaymentProviderId}
export interface PaymentRequest{orderId:string;amount:Money;description:string;customer:OrderCustomer}export interface PaymentResult{providerId:PaymentProviderId;status:PaymentStatus;reference:string;instructions?:string}
export interface TenantPaymentSettings{tenantId:string;enabled:boolean;providers:PaymentProviderId[];defaultProvider?:PaymentProviderId}

export const paymentPurposes=["business_setup","consumer_subscription","managed_platform","client_subscriber_split"]as const;
export type PaymentPurpose=typeof paymentPurposes[number];export type PaymentEnvironment="test"|"live";export type PaymentSubjectType="order"|"user"|"business_client"|"client_platform";export type PaymentTransactionState="initialized"|"pending"|"succeeded"|"failed"|"cancelled";
export interface PaymentSubject{type:PaymentSubjectType;id:string}export interface PaymentProduct{id:string;key:string;purpose:PaymentPurpose;name:string;active:boolean}export interface PaymentPrice{id:string;productKey:string;version:number;kind:"standard"|"promotional"|"current";amountMinor:number;currency:string;interval:"one_time"|"monthly";active:boolean;effectiveFrom:string;effectiveUntil?:string;providerPlanReference?:string}
export interface PaymentCustomerMapping{id:string;subject:PaymentSubject;providerId:PaymentProviderId;environment:PaymentEnvironment;providerCustomerReference:string;metadata?:Record<string,string>}
export interface GeneralizedPaymentTransaction{id:string;purpose:PaymentPurpose;subject:PaymentSubject;providerId:PaymentProviderId;environment:PaymentEnvironment;providerReference:string;productId?:string;priceId?:string;expectedAmountMinor:number;paidAmountMinor?:number;currency:string;state:PaymentTransactionState;createdAt:string;updatedAt:string}
export interface InitializePaymentInput{purpose:PaymentPurpose;subject:PaymentSubject;providerId:PaymentProviderId;environment:PaymentEnvironment;reference:string;expectedAmountMinor:number;currency:string;customerEmail:string;metadata?:Record<string,string>}
export interface ProviderPaymentResult{providerId:PaymentProviderId;environment:PaymentEnvironment;reference:string;state:PaymentTransactionState;amountMinor:number;currency:string;authorizationUrl?:string;providerCustomerReference?:string;customerEmail?:string;metadata?:Record<string,string>}
export interface ProviderSubscriptionRequest{providerCustomerReference:string;providerPlanReference:string;environment:PaymentEnvironment;localSubject:PaymentSubject}export interface ProviderSubscriptionResult{providerSubscriptionReference:string;state:"pending"|"active"|"non-renewing"|"cancelled";environment:PaymentEnvironment}
export type BusinessPackageId="launch"|"business";export type BusinessPaymentMethod="manual-bank"|"paystack";export type BusinessOrderStatus="pending_payment"|"payment_failed"|"paid"|"cancelled";export type OnboardingStatus="not_started"|"awaiting_payment"|"awaiting_client_information";
export type ManualPaymentStatus="awaiting_manual_confirmation"|"confirmed"|"rejected";export interface BusinessSetupOrder{id:string;orderNumber:string;userId?:string;buyer:OrderCustomer;packageId:BusinessPackageId;purpose:"business_setup";productKey:string;priceId:string;standardAmountMinor:number;chargedAmountMinor:number;currency:"NGN";promotionId?:string;businessTermsVersion:string;refundPolicyVersion:string;acceptedAt:string;paymentMethod:BusinessPaymentMethod;status:BusinessOrderStatus;onboardingStatus:OnboardingStatus;manualPaymentStatus?:ManualPaymentStatus;manualConfirmedAt?:string;manualConfirmedBy?:string;createdAt:string;updatedAt:string;paidAt?:string;fulfillmentCount:number}
export interface BusinessSetupTransaction{id:string;orderId:string;providerId:"paystack";environment:PaymentEnvironment;reference:string;expectedAmountMinor:number;paidAmountMinor?:number;currency:"NGN";state:PaymentTransactionState;authorizationUrl?:string;providerMessage?:string;createdAt:string;updatedAt:string;verifiedAt?:string}
export interface BusinessPaymentWebhookEvent{id:string;type:"payment_succeeded"|"payment_failed";providerId:"paystack";environment:PaymentEnvironment;reference:string;amountMinor:number;currency:"NGN";customerEmail:string;orderId:string;productKey:string;priceId:string;occurredAt:string}
export type ManagedPlatformBillingStatus="included_period"|"authorization_required"|"pending"|"active"|"past_due"|"cancelled"|"terminated";
export interface ManagedPlatformBilling{id:string;setupOrderId:string;ownerUserId:string;packageId:BusinessPackageId;productKey:"managed-launch-monthly"|"managed-business-monthly";priceId:string;amountMinor:number;currency:"NGN";billingInterval:"monthly";includedPeriodStart:string;includedPeriodEnd:string;status:ManagedPlatformBillingStatus;providerId?:"paystack";environment:"test";providerCustomerReference?:string;providerSubscriptionReference?:string;authorizationReference?:string;currentPeriodStart?:string;currentPeriodEnd?:string;nextBillingAt?:string;cancelAtPeriodEnd:boolean;cancelledAt?:string;createdAt:string;updatedAt:string}
export type ConsumerSubscriptionStatus="pending"|"active"|"past_due"|"cancelled"|"expired"|"failed";export type ConsumerEntitlementStatus="inactive"|"active"|"suspended"|"expired";export interface ConsumerBillingCustomer{id:string;userId:string;providerId:PaymentProviderId;environment:PaymentEnvironment;providerCustomerReference:string;createdAt:string;updatedAt:string}export interface ConsumerSubscription{id:string;userId:string;billingCustomerId:string;productKey:"consumer-premium-monthly";priceId:string;providerId:PaymentProviderId;environment:PaymentEnvironment;providerPlanReference:string;providerCustomerReference:string;initialPaymentReference:string;providerSubscriptionReference?:string;amountMinor:number;currency:"NGN";billingInterval:"monthly";status:ConsumerSubscriptionStatus;entitlementStatus:ConsumerEntitlementStatus;startedAt?:string;currentPeriodStart?:string;currentPeriodEnd?:string;nextBillingAt?:string;cancelledAt?:string;cancelAtPeriodEnd:boolean;createdAt:string;updatedAt:string}
export interface ConsumerSubscriptionCheckoutRequest{userId:string;email:string;productKey:"consumer-premium-monthly";idempotencyKey:string}export interface ConsumerSubscriptionVerification{reference:string;providerId:PaymentProviderId;environment:PaymentEnvironment;status:"success"|"failed";amountMinor:number;currency:string;providerCustomerReference:string;providerPlanReference:string;providerSubscriptionReference?:string;userId:string;productKey:string;periodStart?:string;periodEnd?:string;nextBillingAt?:string}
export type SubscriptionLifecycleEventType="payment_succeeded"|"payment_failed"|"subscription_activated"|"subscription_non_renewing"|"subscription_cancelled"|"subscription_expired";export interface SubscriptionLifecycleEvent{id:string;type:SubscriptionLifecycleEventType;providerId:"paystack";environment:PaymentEnvironment;providerSubscriptionReference?:string;providerCustomerReference:string;providerPlanReference:string;applicationUserId?:string;productKey?:"consumer-premium-monthly";amountMinor:number;currency:"NGN";occurredAt:string;periodStart?:string;periodEnd?:string;nextBillingAt?:string;providerReference:string}export interface SubscriptionLifecycleAudit{id:string;subscriptionId:string;eventId:string;previousStatus:ConsumerSubscriptionStatus;resultingStatus:ConsumerSubscriptionStatus;previousEntitlement:ConsumerEntitlementStatus;resultingEntitlement:ConsumerEntitlementStatus;environment:PaymentEnvironment;occurredAt:string;processedAt:string}
