if(typeof window!=="undefined")throw new Error("Managed Platform billing is restricted to the server runtime.");
import{randomUUID}from"node:crypto";
import type{BusinessPackageId,BusinessSetupOrder,ManagedPlatformBilling,PaymentEnvironment}from"./domain.ts";
import{resolveTrustedPrice}from"./foundation.ts";

const productByPackage:Record<BusinessPackageId,ManagedPlatformBilling["productKey"]>={launch:"managed-launch-monthly",business:"managed-business-monthly"};
export interface ManagedPlatformRepository{getOrder(orderId:string):Promise<BusinessSetupOrder|null>;getByOrderId(orderId:string):Promise<ManagedPlatformBilling|null>;create(record:ManagedPlatformBilling):Promise<ManagedPlatformBilling>;save(record:ManagedPlatformBilling):Promise<ManagedPlatformBilling>}
export interface ManagedPlatformClock{now():Date}
const systemClock:ManagedPlatformClock={now:()=>new Date()};
export function addCalendarMonths(value:string,months:number){const source=new Date(value);if(Number.isNaN(source.getTime())||!Number.isInteger(months)||months<0)throw new Error("invalid_billing_date");const year=source.getUTCFullYear(),month=source.getUTCMonth()+months,targetYear=year+Math.floor(month/12),targetMonth=((month%12)+12)%12,lastDay=new Date(Date.UTC(targetYear,targetMonth+1,0)).getUTCDate(),day=Math.min(source.getUTCDate(),lastDay);return new Date(Date.UTC(targetYear,targetMonth,day,source.getUTCHours(),source.getUTCMinutes(),source.getUTCSeconds(),source.getUTCMilliseconds())).toISOString()}
export function statusAt(record:ManagedPlatformBilling,at:Date):ManagedPlatformBilling["status"]{if(["active","past_due","cancelled","terminated"].includes(record.status))return record.status;return at.getTime()<new Date(record.includedPeriodEnd).getTime()?"included_period":"authorization_required"}
export class ManagedPlatformBillingService{private repository:ManagedPlatformRepository;private environment:PaymentEnvironment;private clock:ManagedPlatformClock;constructor(repository:ManagedPlatformRepository,environment:PaymentEnvironment,clock:ManagedPlatformClock=systemClock){this.repository=repository;this.environment=environment;this.clock=clock}
 async establishForPaidOrder(orderId:string,ownerUserId:string){const order=await this.repository.getOrder(orderId);if(!order||order.purpose!=="business_setup"||order.environment!==this.environment||order.status!=="paid"||!order.paidAt)throw new Error("qualifying_paid_order_required");if(!order.userId||order.userId!==ownerUserId)throw new Error("managed_platform_access_denied");const existing=await this.repository.getByOrderId(orderId);if(existing){this.assertEnvironment(existing);this.assertOwner(existing,ownerUserId);return this.refresh(existing)}const productKey=productByPackage[order.packageId],price=resolveTrustedPrice(productKey,new Date(order.paidAt));if(price.currency!=="NGN"||price.interval!=="monthly"||price.amountMinor!==(order.packageId==="launch"?1800000:2400000))throw new Error("invalid_managed_platform_catalogue");const now=this.clock.now().toISOString(),record:ManagedPlatformBilling={id:randomUUID(),setupOrderId:order.id,ownerUserId,packageId:order.packageId,productKey,priceId:price.id,amountMinor:price.amountMinor,currency:"NGN",billingInterval:"monthly",includedPeriodStart:order.paidAt,includedPeriodEnd:addCalendarMonths(order.paidAt,6),status:"included_period",environment:this.environment,cancelAtPeriodEnd:false,createdAt:now,updatedAt:now};record.status=statusAt(record,this.clock.now());return this.repository.create(record)}
 async getStatus(orderId:string,ownerUserId:string){const record=await this.repository.getByOrderId(orderId);if(!record)throw new Error("managed_platform_billing_not_found");this.assertEnvironment(record);this.assertOwner(record,ownerUserId);return this.refresh(record)}
 async requestAuthorization(orderId:string,ownerUserId:string){const record=await this.getStatus(orderId,ownerUserId);if(record.status==="included_period")throw new Error("included_period_active");if(record.status!=="authorization_required"&&record.status!=="pending")throw new Error("managed_platform_authorization_unavailable");return record}
 private assertOwner(record:ManagedPlatformBilling,userId:string){if(!userId||record.ownerUserId!==userId)throw new Error("managed_platform_access_denied")}
 private assertEnvironment(record:ManagedPlatformBilling){if(record.environment!==this.environment)throw new Error("provider_environment_mismatch")}
 private async refresh(record:ManagedPlatformBilling){const next=statusAt(record,this.clock.now());if(next===record.status)return record;return this.repository.save({...record,status:next,updatedAt:this.clock.now().toISOString()})}
}
