if(typeof window!=="undefined")throw new Error("Paystack credentials are restricted to the server runtime.");
import type{ConsumerSubscriptionVerification,InitializePaymentInput,ProviderPaymentResult}from"./domain";import type{ConsumerSubscriptionProvider,PaymentGatewayProvider}from"./providers";
const SAFE_BASE="https://api.paystack.co";type PaystackEnvelope={status?:unknown;message?:unknown;data?:Record<string,unknown>};
export function assertPaystackTestNetworkSafety(env:NodeJS.ProcessEnv){if(env.PAYMENTS_ENABLED!=="true")throw new Error("payments_disabled");if(env.PAYMENT_PROVIDER!=="paystack")throw new Error("wrong_payment_provider");if(env.PAYSTACK_ENVIRONMENT!=="test")throw new Error("paystack_test_environment_required");const secret=env.PAYSTACK_SECRET_KEY;if(!secret||!/^sk_test_[A-Za-z0-9_-]{8,}$/.test(secret))throw new Error("valid_paystack_test_key_required");if(secret.startsWith(["sk","live",""].join("_")))throw new Error("live_paystack_key_forbidden");if((env.PAYSTACK_API_BASE_URL??SAFE_BASE)!==SAFE_BASE)throw new Error("invalid_paystack_base_url");return{secret,baseUrl:SAFE_BASE}}
const envelope=(value:unknown):PaystackEnvelope=>{if(!value||typeof value!=="object"||Array.isArray(value))throw new Error("malformed_provider_response");return value as PaystackEnvelope};const string=(value:unknown)=>typeof value==="string"&&value?value:null;
export class PaystackTestProvider implements PaymentGatewayProvider,ConsumerSubscriptionProvider{readonly id="paystack";readonly environment="test"as const;private env:NodeJS.ProcessEnv;private fetcher:typeof fetch;private callbackUrl?:string;constructor(env:NodeJS.ProcessEnv,fetcher:typeof fetch=fetch,callbackUrl?:string){this.env=env;this.fetcher=fetcher;this.callbackUrl=callbackUrl}
 private async call(path:string,init?:RequestInit){const{secret,baseUrl}=assertPaystackTestNetworkSafety(this.env);let response:Response;try{response=await this.fetcher(`${baseUrl}${path}`,{...init,headers:{Authorization:`Bearer ${secret}`,"Content-Type":"application/json",...(init?.headers??{})},signal:AbortSignal.timeout(15000)})}catch{throw new Error("paystack_network_error")};let body:unknown;try{body=await response.json()}catch{throw new Error("malformed_provider_response")};const parsed=envelope(body);if(!response.ok||parsed.status!==true)throw new Error(response.status>=500?"paystack_server_error":"paystack_request_rejected");return parsed.data??{}}
 async initialize(request:InitializePaymentInput):Promise<ProviderPaymentResult>{if(request.environment!=="test"||request.providerId!=="paystack")throw new Error("provider_environment_mismatch");const data=await this.call("/transaction/initialize",{method:"POST",body:JSON.stringify({email:request.customerEmail,amount:request.expectedAmountMinor,currency:request.currency,reference:request.reference,callback_url:this.callbackUrl,metadata:request.metadata})}),authorizationUrl=string(data.authorization_url),reference=string(data.reference);if(!authorizationUrl||reference!==request.reference)throw new Error("invalid_provider_response");return{providerId:"paystack",environment:"test",reference,state:"initialized",amountMinor:request.expectedAmountMinor,currency:request.currency,authorizationUrl}}
 async verify(reference:string):Promise<ProviderPaymentResult>{const data=await this.call(`/transaction/verify/${encodeURIComponent(reference)}`),providerReference=string(data.reference),currency=string(data.currency);if(!providerReference||typeof data.amount!=="number"||!currency||typeof data.status!=="string")throw new Error("invalid_provider_response");return{providerId:"paystack",environment:"test",reference:providerReference,state:data.status==="success"?"succeeded":"failed",amountMinor:data.amount,currency}}
 async ensureCustomer(userId:string,email:string){if(!userId||!/^\S+@\S+\.\S+$/.test(email))throw new Error("invalid_customer_request");const data=await this.call("/customer",{method:"POST",body:JSON.stringify({email,metadata:{application_user_id:userId}})}),providerCustomerReference=string(data.customer_code);if(!providerCustomerReference)throw new Error("invalid_provider_customer");return{providerCustomerReference}}
 async initializeSubscription(input:Parameters<ConsumerSubscriptionProvider["initializeSubscription"]>[0]){if(input.amountMinor!==300000||input.currency!=="NGN"||input.billingInterval!=="monthly"||input.productKey!=="consumer-premium-monthly")throw new Error("invalid_subscription_catalogue");const plan=this.env.PAYSTACK_CONSUMER_MONTHLY_PLAN_CODE;if(!plan||plan!==input.providerPlanReference||!/^PLN_[A-Za-z0-9]+$/.test(plan))throw new Error("trusted_test_plan_required");const data=await this.call("/transaction/initialize",{method:"POST",body:JSON.stringify({email:input.email,amount:input.amountMinor,currency:input.currency,reference:input.reference,plan,callback_url:this.callbackUrl,metadata:{application_user_id:input.userId,product_key:input.productKey,provider_customer_reference:input.providerCustomerReference,provider_plan_reference:plan,provider_subscription_reference:input.reference}})}),authorizationUrl=string(data.authorization_url),reference=string(data.reference);if(!authorizationUrl||reference!==input.reference)throw new Error("invalid_provider_response");return{reference,authorizationUrl}}
 async verifySubscription(reference:string):Promise<ConsumerSubscriptionVerification>{const data=await this.call(`/transaction/verify/${encodeURIComponent(reference)}`),metadata=(data.metadata&&typeof data.metadata==="object"?data.metadata:{})as Record<string,unknown>,customer=(data.customer&&typeof data.customer==="object"?data.customer:{})as Record<string,unknown>,plan=(data.plan&&typeof data.plan==="object"?data.plan:{})as Record<string,unknown>,providerReference=string(data.reference),providerCustomerReference=string(customer.customer_code)??string(metadata.provider_customer_reference),providerPlanReference=string(plan.plan_code)??string(metadata.provider_plan_reference),userId=string(metadata.application_user_id),productKey=string(metadata.product_key),providerSubscriptionReference=string(data.subscription_code)??string(metadata.provider_subscription_reference);if(!providerReference||typeof data.amount!=="number"||!string(data.currency)||!providerCustomerReference||!providerPlanReference||!userId||!productKey||!providerSubscriptionReference)throw new Error("invalid_provider_response");return{reference:providerReference,providerId:"paystack",environment:"test",status:data.status==="success"?"success":"failed",amountMinor:data.amount,currency:String(data.currency),providerCustomerReference,providerPlanReference,providerSubscriptionReference,userId,productKey}}
 async getSubscription(providerSubscriptionReference:string){const data=await this.call(`/subscription/${encodeURIComponent(providerSubscriptionReference)}`),customer=(data.customer&&typeof data.customer==="object"?data.customer:{})as Record<string,unknown>,plan=(data.plan&&typeof data.plan==="object"?data.plan:{})as Record<string,unknown>,metadata=(data.metadata&&typeof data.metadata==="object"?data.metadata:{})as Record<string,unknown>;return{reference:providerSubscriptionReference,providerId:"paystack",environment:"test",status:data.status==="active"?"success":"failed",amountMinor:Number(data.amount??plan.amount),currency:String(data.currency??plan.currency),providerCustomerReference:String(customer.customer_code??""),providerPlanReference:String(plan.plan_code??""),providerSubscriptionReference,userId:String(metadata.application_user_id??""),productKey:String(metadata.product_key??"")}as ConsumerSubscriptionVerification}
 async cancelSubscription(providerSubscriptionReference:string){const token=this.env.PAYSTACK_SUBSCRIPTION_EMAIL_TOKEN;if(!providerSubscriptionReference||!token)throw new Error("subscription_cancellation_token_required");await this.call("/subscription/disable",{method:"POST",body:JSON.stringify({code:providerSubscriptionReference,token})});return{status:"cancelled"as const,providerSubscriptionReference}}
}
export function createConfiguredPaystackProvider(env:NodeJS.ProcessEnv=process.env,fetcher:typeof fetch=fetch){try{assertPaystackTestNetworkSafety(env)}catch{throw new Error("payments_not_safely_enabled")}const site=(env.NEXT_PUBLIC_SITE_URL??"http://localhost:3000").replace(/\/$/,"");return new PaystackTestProvider(env,fetcher,`${site}/payments/paystack/callback`)}
