if(typeof window!=="undefined")throw new Error("Paystack credentials are restricted to the server runtime.");
import type { InitializePaymentInput, ProviderPaymentResult } from "./domain";
import type { PaymentGatewayProvider } from "./providers";
const safeBase="https://api.paystack.co";
type PaystackEnvelope={status?:unknown;message?:unknown;data?:Record<string,unknown>};
function parsedEnvelope(value:unknown):PaystackEnvelope{if(!value||typeof value!=="object")throw new Error("malformed_provider_response");return value as PaystackEnvelope}
export class PaystackTestProvider implements PaymentGatewayProvider{readonly id="paystack";readonly environment="test" as const;constructor(private secretKey:string,private baseUrl=safeBase,private fetcher:typeof fetch=fetch,private callbackUrl?:string){if(!secretKey||!secretKey.startsWith("sk_test_"))throw new Error("paystack_test_key_required");if(baseUrl!==safeBase)throw new Error("invalid_paystack_base_url");if(callbackUrl&&!/^https?:\/\//.test(callbackUrl))throw new Error("invalid_callback_url")}
 private async call(path:string,init?:RequestInit){const response=await this.fetcher(`${this.baseUrl}${path}`,{...init,headers:{Authorization:`Bearer ${this.secretKey}`,"Content-Type":"application/json",...(init?.headers??{})}});let body:unknown;try{body=await response.json()}catch{throw new Error("malformed_provider_response")};const envelope=parsedEnvelope(body);if(!response.ok||envelope.status!==true)throw new Error("paystack_request_failed");return envelope.data??{}}
 async initialize(request:InitializePaymentInput):Promise<ProviderPaymentResult>{if(request.environment!=="test"||request.providerId!=="paystack")throw new Error("provider_environment_mismatch");const data=await this.call("/transaction/initialize",{method:"POST",body:JSON.stringify({email:request.customerEmail,amount:request.expectedAmountMinor,currency:request.currency,reference:request.reference,callback_url:this.callbackUrl,metadata:request.metadata})});if(typeof data.authorization_url!=="string"||typeof data.reference!=="string"||data.reference!==request.reference)throw new Error("invalid_provider_response");return{providerId:"paystack",environment:"test",reference:data.reference,state:"initialized",amountMinor:request.expectedAmountMinor,currency:request.currency,authorizationUrl:data.authorization_url}}
 async verify(reference:string):Promise<ProviderPaymentResult>{const data=await this.call(`/transaction/verify/${encodeURIComponent(reference)}`);if(typeof data.reference!=="string"||typeof data.amount!=="number"||typeof data.currency!=="string"||typeof data.status!=="string")throw new Error("invalid_provider_response");return{providerId:"paystack",environment:"test",reference:data.reference,state:data.status==="success"?"succeeded":"failed",amountMinor:data.amount,currency:data.currency}}
}
export function createConfiguredPaystackProvider(env:NodeJS.ProcessEnv=process.env,fetcher:typeof fetch=fetch){if(env.PAYMENTS_ENABLED!=="true"||env.PAYMENT_PROVIDER!=="paystack"||env.PAYSTACK_ENVIRONMENT!=="test")throw new Error("payments_not_safely_enabled");const site=(env.NEXT_PUBLIC_SITE_URL??"http://localhost:3000").replace(/\/$/,"");return new PaystackTestProvider(env.PAYSTACK_SECRET_KEY??"",env.PAYSTACK_API_BASE_URL??safeBase,fetcher,`${site}/payments/paystack/callback`)}
