if(typeof window!=="undefined")throw new Error("Webhook persistence is restricted to the server runtime.");
import{createClient}from"@supabase/supabase-js";import{requireServiceRoleSupabaseConfig}from"../../lib/supabase/server-environment.ts";import{requirePaymentsEnabled}from"./runtime-config.ts";import type{ConsumerSubscription,SubscriptionLifecycleAudit,SubscriptionLifecycleEvent}from"./domain";import type{SubscriptionLifecycleRepository}from"./paystack-webhooks";
const map=(row:Record<string,unknown>):ConsumerSubscription=>({id:String(row.id),userId:String(row.user_id),billingCustomerId:String(row.billing_customer_id),productKey:"consumer-premium-monthly",priceId:String(row.price_id),providerId:"paystack",environment:"test",providerPlanReference:String(row.provider_plan_reference),providerCustomerReference:String(row.provider_customer_reference),initialPaymentReference:String(row.initial_payment_reference),...(row.provider_subscription_reference?{providerSubscriptionReference:String(row.provider_subscription_reference)}:{}),amountMinor:Number(row.amount_minor),currency:"NGN",billingInterval:"monthly",status:row.status as ConsumerSubscription["status"],entitlementStatus:row.entitlement_status as ConsumerSubscription["entitlementStatus"],startedAt:row.started_at?String(row.started_at):undefined,currentPeriodStart:row.current_period_start?String(row.current_period_start):undefined,currentPeriodEnd:row.current_period_end?String(row.current_period_end):undefined,nextBillingAt:row.next_billing_at?String(row.next_billing_at):undefined,cancelledAt:row.cancelled_at?String(row.cancelled_at):undefined,cancelAtPeriodEnd:Boolean(row.cancel_at_period_end),createdAt:String(row.created_at),updatedAt:String(row.updated_at)});
export class SupabaseLifecycleRepository implements SubscriptionLifecycleRepository{
 private db;private env:NodeJS.ProcessEnv;constructor(env:NodeJS.ProcessEnv=process.env){this.env=env;const{url,serviceRoleKey}=requireServiceRoleSupabaseConfig(env);this.db=createClient(url,serviceRoleKey,{auth:{persistSession:false,autoRefreshToken:false}})}
 async getByProviderReference(reference:string){const{data,error}=await this.db.from("consumer_subscriptions").select("*").eq("provider","paystack").eq("environment","test").eq("provider_subscription_reference",reference).maybeSingle();if(error)throw new Error("subscription_read_failed");return data?map(data):null}
 async getPendingByCustomerAndPlan(customerReference:string,planReference:string){const{data,error}=await this.db.from("consumer_subscriptions").select("*").eq("provider","paystack").eq("environment","test").eq("status","pending").eq("provider_customer_reference",customerReference).eq("provider_plan_reference",planReference).maybeSingle();if(error)throw new Error("subscription_read_failed");return data?map(data):null}
 async claimEvent(event:SubscriptionLifecycleEvent){requirePaymentsEnabled(this.env);const{error}=await this.db.from("consumer_subscription_events").insert({provider:"paystack",environment:"test",provider_event_reference:event.id,event_type:event.type,provider_reference:event.providerReference,occurred_at:event.occurredAt,processing_result:"claimed"});if(!error)return true;if(error.code==="23505")return false;throw new Error("event_claim_failed")}
 async saveSubscription(value:ConsumerSubscription){requirePaymentsEnabled(this.env);const{error}=await this.db.from("consumer_subscriptions").update({provider_subscription_reference:value.providerSubscriptionReference??null,status:value.status,entitlement_status:value.entitlementStatus,current_period_start:value.currentPeriodStart??null,current_period_end:value.currentPeriodEnd??null,next_billing_at:value.nextBillingAt??null,cancelled_at:value.cancelledAt??null,updated_at:value.updatedAt}).eq("id",value.id);if(error)throw new Error("subscription_update_failed")}
 async saveAudit(audit:SubscriptionLifecycleAudit){requirePaymentsEnabled(this.env);const{error}=await this.db.from("consumer_subscription_lifecycle_audit").insert({subscription_id:audit.subscriptionId,event_id:null,provider:"paystack",environment:"test",provider_event_reference:audit.eventId,previous_status:audit.previousStatus,resulting_status:audit.resultingStatus,previous_entitlement:audit.previousEntitlement,resulting_entitlement:audit.resultingEntitlement,occurred_at:audit.occurredAt,processed_at:audit.processedAt});if(error)throw new Error("lifecycle_audit_failed")}
}
