import { applicationConfig } from "@/config/application";
import type { CompetitionRepository, FixtureRepository, PredictionRepository, ResultsRepository } from "./repositories";
import type { IntelligenceReport, MatchStatistics, TeamForm } from "./domain";
import type { AIIntelligenceProvider } from "./providers";
import { DataUnavailableError, NotFoundError } from "./errors";

export class FixtureService { constructor(private repository: FixtureRepository) {} getDemoFixtures(competitionId?:string){const items=competitionId?this.repository.getFixturesByCompetition(competitionId):this.repository.getFixturesForDate();return items.filter(item=>item.source.isDemo)} getFeaturedFixture(){const item=this.repository.getFeaturedFixture();if(!item)throw new DataUnavailableError("No featured fixture is available.");return item} getFixture(id:string){const item=this.repository.getFixtureById(id);if(!item)throw new NotFoundError("Fixture",id);return item} }
export class PredictionService { constructor(private repository: PredictionRepository) {} getPrediction(fixtureId:string){const item=this.repository.getPredictionForFixture(fixtureId);if(!item)throw new DataUnavailableError("Prediction unavailable for this fixture.");return item} getDemoPredictions(){return this.repository.getPredictionsForDate().filter(item=>item.source.isDemo)} }
export class CompetitionService { constructor(private repository: CompetitionRepository) {} getSupported(){return this.repository.getSupportedCompetitions()} getCompetition(id:string){const item=this.repository.getCompetitionById(id);if(!item)throw new NotFoundError("Competition",id);return item} }
export class ResultsService { constructor(private repository: ResultsRepository) {} getPublicResults(status?:string,competitionId?:string){return this.repository.getRecentResults(applicationConfig.defaultResultLimit).filter(item=>(!status||status==="all"||item.outcome===status)&&(!competitionId||competitionId==="all"||item.competitionId===competitionId))} }
export class IntelligenceService {
  constructor(private fixtures:FixtureService,private competitions:CompetitionService,private forms:TeamForm[],private statistics:Record<string,MatchStatistics>,private aiProvider:AIIntelligenceProvider){}
  getFeaturedIntelligence(){return this.getIntelligenceForFixture(this.fixtures.getFeaturedFixture().id)}
  async getIntelligenceForFixture(fixtureId:string):Promise<IntelligenceReport>{const fixture=this.fixtures.getFixture(fixtureId);const competition=this.competitions.getCompetition(fixture.competitionId);const homeForm=this.forms.find(item=>item.teamId===fixture.homeTeam.id)??{teamId:fixture.homeTeam.id,sequence:[],summary:"Form unavailable"};const awayForm=this.forms.find(item=>item.teamId===fixture.awayTeam.id)??{teamId:fixture.awayTeam.id,sequence:[],summary:"Form unavailable"};return this.aiProvider.generateMatchIntelligence({fixture,competition,homeForm,awayForm,statistics:this.statistics[fixture.id]??{headToHeadSummary:"No demonstration head-to-head summary"}})}
}
