import "@/lib/server-only";
import { NextResponse } from "next/server";
import { createPrivilegedSupabaseClient } from "@/lib/supabase/privileged";
import { authorizeFootballCron } from "./auth";
import { getFootballOrchestrationConfig } from "./config";
import { FootballProductionOrchestrator,type FootballJob } from "./service";
export function createFootballCronHandler(job:FootballJob){return async function GET(request:Request){const config=getFootballOrchestrationConfig();if(!authorizeFootballCron(request,config.cronSecret))return NextResponse.json({error:"unauthorized"},{status:401});try{const result=await new FootballProductionOrchestrator(createPrivilegedSupabaseClient()).run(job);return NextResponse.json(result,{status:result.status==="OVERLAPPING_RUN_SKIPPED"?202:200})}catch{return NextResponse.json({error:"football_job_failed",job},{status:500})}}}
export const FOOTBALL_LIFECYCLE_JOBS:readonly FootballJob[]=["settlement","enrichment","verification","ingestion","prediction","publication"];
function safeError(error:unknown){const type=error instanceof Error?error.name:"ORCHESTRATION_ERROR";const raw=error instanceof Error?error.message:"Unknown lifecycle stage failure.";const message=raw.replace(/(bearer\s+)[^\s]+/gi,"$1[REDACTED]").replace(/((?:api[_-]?key|secret|token|authorization)\s*[:=]\s*)[^\s,;]+/gi,"$1[REDACTED]").slice(0,240);return{type,message}}
function safeCounts(result:Awaited<ReturnType<FootballProductionOrchestrator["run"]>>){
 if(result.status==="OVERLAPPING_RUN_SKIPPED")return{providerRequests:0,examined:0,changed:0};
 const counts:Record<string,unknown>={providerRequests:result.providerRequests,examined:result.examined,changed:result.changed},summary=result.summary as Record<string,unknown>;
 if(result.job==="settlement"){counts.settled=typeof summary.settled==="number"?summary.settled:result.changed;counts.fixturesRefreshed=typeof summary.refreshed==="number"?summary.refreshed:0}
 if(result.job==="enrichment"){
  const diagnostics=Array.isArray(summary.diagnostics)?summary.diagnostics:[],categories:Record<string,{attempts:number;requests:number;usable:number;empty:number;providerErrors:number;accessRestrictions:number;invalidMappings:number;parsingFailures:number;persistenceErrors:number;skippedFreshness:number;skippedNotExpected:number;sharedReuses:number;budgetSkipped:number;errors:Record<string,number>}>= {},identityMismatches:string[]=[];
  for(const value of diagnostics){if(!value||typeof value!=="object")continue;const item=value as Record<string,unknown>,category=typeof item.category==="string"?item.category:"unknown",status=typeof item.status==="string"?item.status:"UNKNOWN",bucket=categories[category]??={attempts:0,requests:0,usable:0,empty:0,providerErrors:0,accessRestrictions:0,invalidMappings:0,parsingFailures:0,persistenceErrors:0,skippedFreshness:0,skippedNotExpected:0,sharedReuses:0,budgetSkipped:0,errors:{}};bucket.requests+=typeof item.requestCount==="number"?item.requestCount:0;if(["PERSISTED","EMPTY","PROVIDER_ERROR","PERSISTENCE_ERROR"].includes(status))bucket.attempts++;if(status==="PERSISTED")bucket.usable++;if(status==="EMPTY")bucket.empty++;if(status==="PROVIDER_ERROR")bucket.providerErrors++;if(status==="PERSISTENCE_ERROR")bucket.persistenceErrors++;if(status==="CACHE_HIT")bucket.skippedFreshness++;if(status==="NOT_EXPECTED")bucket.skippedNotExpected++;if(status==="SHARED_REUSE")bucket.sharedReuses++;if(status==="BUDGET_SKIPPED")bucket.budgetSkipped++;const code=typeof item.errorCode==="string"?item.errorCode:null,errorCategory=typeof item.errorCategory==="string"?item.errorCategory:null,message=typeof item.errorMessage==="string"?item.errorMessage.slice(0,160):null,httpStatus=typeof item.httpStatus==="number"?item.httpStatus:null;if(code){const key=JSON.stringify({category:errorCategory,code,message,httpStatus});bucket.errors[key]=(bucket.errors[key]??0)+1;if(code==="subscription_access_restricted")bucket.accessRestrictions++;if(code==="invalid_request"||code==="invalid_or_unavailable_season")bucket.invalidMappings++;if(code==="malformed_response"||code==="normalization_rejected")bucket.parsingFailures++;}if(item.identityMatches===false&&typeof item.providerFixtureId==="string")identityMismatches.push(item.providerFixtureId)}
  counts.candidates=typeof summary.candidates==="number"?summary.candidates:result.examined;counts.ineligibleStatus=typeof summary.ineligibleStatus==="number"?summary.ineligibleStatus:0;counts.selected=Array.isArray(summary.selected)?summary.selected.slice(0,30):[];counts.categories=categories;counts.identityMismatches=[...new Set(identityMismatches)].slice(0,30);counts.snapshotsPersisted=result.changed;
 }
 if(result.job==="prediction"){counts.eligible=typeof summary.eligible==="number"?summary.eligible:0;counts.reused=typeof summary.reused==="number"?summary.reused:0;counts.held=typeof summary.held==="number"?summary.held:0;counts.holdReasons=summary.holdReasons&&typeof summary.holdReasons==="object"?summary.holdReasons:{}}
 if(result.job==="publication"){counts.published=typeof summary.published==="number"?summary.published:result.changed}
 return counts
}
function logStage(event:Record<string,unknown>,failed=false){const line=JSON.stringify({scope:"football-lifecycle",...event});if(failed)console.error(line);else console.info(line)}
export function createFootballLifecycleCronHandler(){return async function GET(request:Request){const config=getFootballOrchestrationConfig();if(!authorizeFootballCron(request,config.cronSecret))return NextResponse.json({error:"unauthorized"},{status:401});const orchestrator=new FootballProductionOrchestrator(createPrivilegedSupabaseClient()),jobs=[];let failed=false;try{logStage({stage:"preflight",status:"COMPLETED",...(await orchestrator.inspectLifecycleState())})}catch(error){failed=true;logStage({stage:"preflight",status:"FAILED",error:safeError(error)},true)}for(const job of FOOTBALL_LIFECYCLE_JOBS){logStage({stage:job,status:"STARTED"});try{const result=await orchestrator.run(job),counts=safeCounts(result);jobs.push({job,status:result.status,...counts});logStage({stage:job,status:result.status,...counts})}catch(error){failed=true;const sanitized=safeError(error);jobs.push({job,status:"FAILED",error:sanitized});logStage({stage:job,status:"FAILED",error:sanitized},true)}}return NextResponse.json({status:failed?"PARTIAL_FAILURE":"COMPLETED",jobs},{status:failed?500:200})}}
