import "@/lib/server-only";
import { NextResponse } from "next/server";
import { createPrivilegedSupabaseClient } from "@/lib/supabase/privileged";
import { authorizeFootballCron } from "./auth";
import { getFootballOrchestrationConfig } from "./config";
import { FootballProductionOrchestrator,type FootballJob } from "./service";
export function createFootballCronHandler(job:FootballJob){return async function GET(request:Request){const config=getFootballOrchestrationConfig();if(!authorizeFootballCron(request,config.cronSecret))return NextResponse.json({error:"unauthorized"},{status:401});try{const result=await new FootballProductionOrchestrator(createPrivilegedSupabaseClient()).run(job);return NextResponse.json(result,{status:result.status==="OVERLAPPING_RUN_SKIPPED"?202:200})}catch{return NextResponse.json({error:"football_job_failed",job},{status:500})}}}
export const FOOTBALL_LIFECYCLE_JOBS:readonly FootballJob[]=["settlement","enrichment","verification","ingestion","prediction","publication"];
function safeError(error:unknown){const type=error instanceof Error?error.name:"ORCHESTRATION_ERROR";const raw=error instanceof Error?error.message:"Unknown lifecycle stage failure.";const message=raw.replace(/(bearer\s+)[^\s]+/gi,"$1[REDACTED]").replace(/((?:api[_-]?key|secret|token|authorization)\s*[:=]\s*)[^\s,;]+/gi,"$1[REDACTED]").slice(0,240);return{type,message}}
function safeCounts(result:Awaited<ReturnType<FootballProductionOrchestrator["run"]>>){if(result.status==="OVERLAPPING_RUN_SKIPPED")return{providerRequests:0,examined:0,changed:0};const counts:{providerRequests:number;examined:number;changed:number;candidates?:number;settled?:number;fixturesRefreshed?:number;snapshots?:Record<string,number>}={providerRequests:result.providerRequests,examined:result.examined,changed:result.changed},summary=result.summary as Record<string,unknown>;if(result.job==="settlement"){counts.settled=typeof summary.settled==="number"?summary.settled:result.changed;counts.fixturesRefreshed=typeof summary.refreshed==="number"?summary.refreshed:0}if(result.job==="enrichment"){counts.candidates=typeof summary.candidates==="number"?summary.candidates:result.examined;const refreshed=Array.isArray(summary.refreshed)?summary.refreshed:[];counts.snapshots=refreshed.reduce<Record<string,number>>((totals,item)=>{if(item&&typeof item==="object"&&"category" in item&&typeof item.category==="string")totals[item.category]=(totals[item.category]??0)+1;return totals},{})}return counts}
function logStage(event:Record<string,unknown>,failed=false){const line=JSON.stringify({scope:"football-lifecycle",...event});if(failed)console.error(line);else console.info(line)}
export function createFootballLifecycleCronHandler(){return async function GET(request:Request){const config=getFootballOrchestrationConfig();if(!authorizeFootballCron(request,config.cronSecret))return NextResponse.json({error:"unauthorized"},{status:401});const orchestrator=new FootballProductionOrchestrator(createPrivilegedSupabaseClient()),jobs=[];let failed=false;for(const job of FOOTBALL_LIFECYCLE_JOBS){logStage({stage:job,status:"STARTED"});try{const result=await orchestrator.run(job),counts=safeCounts(result);jobs.push({job,status:result.status,...counts});logStage({stage:job,status:result.status,...counts})}catch(error){failed=true;const sanitized=safeError(error);jobs.push({job,status:"FAILED",error:sanitized});logStage({stage:job,status:"FAILED",error:sanitized},true)}}return NextResponse.json({status:failed?"PARTIAL_FAILURE":"COMPLETED",jobs},{status:failed?500:200})}}
