import "@/lib/server-only";
import type { SupabaseClient } from "@supabase/supabase-js";
import type { Database,Json } from "@/lib/supabase/database.types";
import { footballDataConfig } from "@/config/football-data";
import { getServerFootballProviderConfig } from "@/modules/football-data/server-config";
import { ApiFootballProvider } from "@/modules/football-data/api-football-provider";
import { FootballDataIngestionService } from "@/modules/football-data/service";
import { SupabaseFootballIngestionRepository,SupabaseProviderRequestRepository } from "@/modules/persistence/football-repositories";
import { SupabaseShadowPredictionRepository,SupabaseShadowRunRepository } from "@/modules/persistence/shadow-repositories";
import { loadPersistedShadowFixtureSources } from "@/modules/persistence/shadow-fixture-source";
import { settleShadowPrediction } from "@/modules/football-intelligence/shadow-pipeline";
import { getShadowPipelineControls,getSupportedShadowCompetitions } from "@/modules/football-intelligence/shadow-pipeline/config";
import { runRollingShadowWorker } from "@/modules/football-intelligence/rolling-readiness";
import { ConsumerPredictionPublicationService } from "@/modules/consumer-publication/service";
import { getFootballOrchestrationConfig } from "./config";
export type FootballJob="ingestion"|"prediction"|"publication"|"settlement";
type JobResult={status:"COMPLETED"|"SKIPPED";providerRequests:number;examined:number;changed:number;summary:Record<string,Json>};
export class FootballProductionOrchestrator{
 constructor(private readonly client:SupabaseClient<Database>,private readonly env:NodeJS.ProcessEnv=process.env){}
 async run(job:FootballJob){const config=getFootballOrchestrationConfig(this.env),dryRun=job==="ingestion"?config.ingestionDryRun:false,begun=await this.client.rpc("begin_football_orchestration_run",{p_job:job,p_environment:config.environment,p_dry_run:dryRun,p_stale_after_minutes:30});if(begun.error)throw new Error("Football orchestration lock failed.");if(!begun.data)return{status:"OVERLAPPING_RUN_SKIPPED" as const,job};try{const result=await this.execute(job);await this.finish(begun.data,result.status,result.providerRequests,result.examined,result.changed,result.summary,null);return{job,...result};}catch(error){await this.finish(begun.data,"FAILED",0,0,0,{},error instanceof Error?error.name:"ORCHESTRATION_ERROR");throw error}}
 private async finish(id:string,status:string,providerRequests:number,examined:number,changed:number,summary:Record<string,Json>,errorCode:string|null){const done=await this.client.rpc("finish_football_orchestration_run",{p_run_id:id,p_status:status,p_provider_requests:providerRequests,p_records_examined:examined,p_records_changed:changed,p_summary:summary,p_error_code:errorCode});if(done.error||done.data!==true)throw new Error("Football orchestration audit completion failed.")}
 private execute(job:FootballJob){if(job==="ingestion")return this.ingest();if(job==="prediction")return this.predict();if(job==="publication")return this.publish();return this.settle()}
 private async ingest():Promise<JobResult>{const controls=getFootballOrchestrationConfig(this.env),server=getServerFootballProviderConfig(this.env);if(!controls.providerEnabled||!controls.providerCallsEnabled||controls.ingestionDryRun)return{status:"SKIPPED",providerRequests:0,examined:0,changed:0,summary:{reason:"PROVIDER_OR_LIVE_INGESTION_DISABLED",providerConfigured:server.provider==="api-football",apiKeyConfigured:Boolean(server.apiKey),cronSecretConfigured:Boolean(controls.cronSecret)}};const selected=footballDataConfig.competitions.filter(row=>row.enabled&&row.providerId&&row.currentSeason);if(selected.length!==1)throw new Error("Controlled ingestion requires exactly one enabled competition mapping.");const audits:unknown[]=[];const provider=new ApiFootballProvider({apiKey:server.apiKey,enabled:server.enabled,onRequest:audit=>audits.push(audit)}),repository=new SupabaseFootballIngestionRepository(this.client),requests=new SupabaseProviderRequestRepository(this.client),service=new FootballDataIngestionService(provider,repository,requests,footballDataConfig.competitions,Math.min(server.dailyRequestBudget,controls.maxProviderRequestsPerRun)),result=await service.ingestCompetition(selected[0].id,"scheduled",["teams","fixtures"]),changed=result.fixtures;if(audits.length>controls.maxProviderRequestsPerRun)throw new Error("Controlled ingestion exceeded its provider request ceiling.");return{status:result.status==="completed"?"COMPLETED":"SKIPPED",providerRequests:audits.length,examined:1,changed,summary:{competition:selected[0].id,season:selected[0].currentSeason,fixturesChanged:changed,result:result.status}}}
 private async predict():Promise<JobResult>{const config=getFootballOrchestrationConfig(this.env),controls=getShadowPipelineControls();if(!config.predictionEnabled)return{status:"SKIPPED",providerRequests:0,examined:0,changed:0,summary:{reason:"PREDICTION_PIPELINE_DISABLED"}};const allowlist=getSupportedShadowCompetitions(),now=new Date().toISOString(),sources=await loadPersistedShadowFixtureSources(this.client,allowlist,now,168),predictions=new SupabaseShadowPredictionRepository(this.client),runs=new SupabaseShadowRunRepository(this.client),existing=await predictions.list(),worker=await runRollingShadowWorker({lockKey:`${config.environment}:prediction`,sources,repositories:{predictions,runs},controls:{...controls,horizonHours:168,maxProviderRequestsPerRun:config.maxProviderRequestsPerRun},allowlist,frozenProviderFixtureIds:new Set(existing.map(row=>row.providerFixtureId)),now,persist:true});if(!worker.report)return{status:"SKIPPED",providerRequests:0,examined:0,changed:0,summary:{reason:worker.status}};return{status:"COMPLETED",providerRequests:0,examined:worker.report.fixturesFound,changed:worker.report.predictionsCreated,summary:{eligible:worker.report.fixturesEligible,reused:worker.report.predictionsReused,horizonHours:168}}}
 private async publish():Promise<JobResult>{const config=getFootballOrchestrationConfig(this.env);if(!config.publishingEnabled)return{status:"SKIPPED",providerRequests:0,examined:0,changed:0,summary:{reason:"PUBLIC_PUBLISHING_DISABLED"}};const shadows=await this.client.from("football_shadow_predictions").select("id,kickoff_at,settlement_status").eq("settlement_status","PENDING").gt("kickoff_at",new Date().toISOString()),service=new ConsumerPredictionPublicationService(this.client);if(shadows.error)throw new Error("Publication candidate read failed.");let changed=0;for(const shadow of shadows.data??[]){const existing=await this.client.from("intelligence_reports").select("id,status,consumer_publication_state").eq("forward_prediction_id",shadow.id).maybeSingle();if(existing.error)throw new Error("Publication identity read failed.");const id=existing.data?.id??await service.prepare(shadow.id,"premium"),state=existing.data?.consumer_publication_state??"NOT_PUBLISHED";if(state==="PUBLISHED")continue;if(state==="NOT_PUBLISHED")await service.markReadyForReview(id);await service.publish(id);changed++}return{status:"COMPLETED",providerRequests:0,examined:shadows.data?.length??0,changed,summary:{published:changed}}}
 private async settle():Promise<JobResult>{const config=getFootballOrchestrationConfig(this.env);if(!config.settlementEnabled)return{status:"SKIPPED",providerRequests:0,examined:0,changed:0,summary:{reason:"SETTLEMENT_DISABLED"}};const repository=new SupabaseShadowPredictionRepository(this.client),predictions=(await repository.list()).filter(row=>row.settlementStatus==="PENDING"&&new Date(row.kickoffAt)<=new Date()),ids=predictions.map(row=>row.fixtureId),fixtures=ids.length?await this.client.from("fixtures").select("*,competitions(provider_id,season)").in("id",ids).in("status",["finished","cancelled","postponed","abandoned","void"]):{data:[],error:null};if(fixtures.error)throw new Error("Settlement fixture read failed.");let changed=0;for(const prediction of predictions){const fixture=fixtures.data?.find(row=>row.id===prediction.fixtureId);if(!fixture)continue;const competition=Array.isArray(fixture.competitions)?fixture.competitions[0]:fixture.competitions;if(!competition?.provider_id)continue;const result=await settleShadowPrediction(repository,prediction,{providerFixtureId:fixture.provider_fixture_id??"",providerCompetitionId:competition.provider_id,season:competition.season,homeTeamId:fixture.home_team_id,awayTeamId:fixture.away_team_id,kickoffAt:fixture.kickoff_at,status:fixture.status,homeScore:fixture.home_score,awayScore:fixture.away_score},new Date().toISOString());if(result.disposition==="UPDATED")changed++}return{status:"COMPLETED",providerRequests:0,examined:predictions.length,changed,summary:{settled:changed}}}
}
