import type { Metadata } from "next";
import { LegalDocument } from "@/components/legal-document";
export const metadata:Metadata={title:"Privacy Policy",description:"How FABRO TECH LIMITED handles information for 9ja Football AI."};
export default function Page(){return <LegalDocument eyebrow="Legal" title="Privacy Policy" intro="This policy explains how FABRO TECH LIMITED handles information when you use 9ja Football AI.">
<h2>Information we process</h2><p>When you create an account, we process your display name, email address, account identifier and authentication state. Passwords are handled by our authentication provider and are not displayed to us in readable form. We also process membership status, free-prediction usage and saved prediction entitlements needed to operate account access.</p>
<p>Our hosting and security infrastructure may process technical information such as IP address, browser or device details, timestamps, request logs and error information. If payment functionality is used, we may retain order, package, amount and payment-status records; payment providers process payment details under their own policies.</p>
<p>When you contact us through WhatsApp, your message and account information are processed by WhatsApp under its terms and may also be retained by FABRO TECH LIMITED to answer and manage the enquiry.</p>
<h2>Cookies and browser storage</h2><p>Authentication uses cookies needed to maintain secure sessions. Development fallback modes may use limited browser storage, but the public production service relies on its configured authentication and persistence services. We do not describe optional advertising cookies because they are not part of the current implementation.</p>
<h2>Why we use information</h2><p>We use information to create and secure accounts, provide entitled features, remember unlocked predictions, operate subscriptions or orders where enabled, respond to enquiries, maintain and troubleshoot the service, prevent abuse and comply with applicable obligations.</p>
<h2>Service providers</h2><p>We use infrastructure providers including Supabase for configured authentication/database services and Vercel for application hosting. WhatsApp handles messages sent through WhatsApp links. Additional payment, email or football-data providers apply only when the relevant service is enabled and will process data under their own terms.</p>
<h2>Sharing and international processing</h2><p>We share information only as needed with service providers, professional advisers, authorities where lawfully required, or in connection with a legitimate business reorganization. Infrastructure providers may process information in other countries subject to their contractual and legal safeguards.</p>
<h2>Retention and security</h2><p>We retain information for as long as needed to provide the service, maintain transaction and security records, resolve disputes and satisfy applicable obligations. We use access controls, row-level database protections and secure provider credentials, but no online service can promise absolute security.</p>
<h2>Your choices and rights</h2><p>Depending on applicable law, you may request access, correction or deletion of personal information, object to or restrict certain processing, or ask about retention. Some records may need to be retained for security, transactions or legal obligations. Contact us through WhatsApp to make a request.</p>
<h2>Children</h2><p>The service is not directed to children. Betting-related information must not be used by anyone below the lawful age in their jurisdiction.</p>
<h2>Third-party links and updates</h2><p>External sites have their own privacy practices. We may update this policy as the service changes and will publish the current version and update date on this page.</p>
</LegalDocument>}
