import type { AdminPublicationCommand, ConfidenceLabel, EligibilityCheck, PublishingControls, PublishingReasonCode, PublishingTier, SelectivePublishingInput, SelectivePublishingResult, SelectedOutcome } from "./domain";
import { SELECTIVE_PUBLISHING_V1 } from "./policy";

export const DEFAULT_PUBLISHING_CONTROLS: PublishingControls = Object.freeze({ publishingEnabled: true, topPicksEnabled: true, globalPause: false, suppressedFixtureIds: new Set<string>() });
const probabilityFor = (input: SelectivePublishingInput, outcome: SelectedOutcome) => outcome === "home" ? input.probabilities.homeWin : outcome === "draw" ? input.probabilities.draw : input.probabilities.awayWin;
const maximumProbability = (input: SelectivePublishingInput) => Math.max(input.probabilities.homeWin, input.probabilities.draw, input.probabilities.awayWin);
const topMargin = (input: SelectivePublishingInput) => { const sorted = Object.values(input.probabilities).sort((a, b) => b - a); return sorted[0] - sorted[1]; };
const minimumHistory = (input: SelectivePublishingInput) => Math.min(input.evidence.homeHistory, input.evidence.awayHistory);
const validDate = (value: string) => value.trim().length > 0 && Number.isFinite(new Date(value).getTime());
const selectedIsArgmax = (input: SelectivePublishingInput) => Math.abs(probabilityFor(input, input.selectedOutcome) - maximumProbability(input)) <= SELECTIVE_PUBLISHING_V1.probabilityTolerance;

function eligibility(input: SelectivePublishingInput) {
  const values = Object.values(input.probabilities), finite = values.every(Number.isFinite), bounded = finite && values.every((value) => value >= 0 && value <= 1), normalized = bounded && Math.abs(values.reduce((sum, value) => sum + value, 0) - 1) <= SELECTIVE_PUBLISHING_V1.probabilityTolerance, validFixture = Boolean(input.fixtureId.trim()) && validDate(input.kickoffAt), validEvidenceDate = input.evidence.latestEvidenceAt !== null && validDate(input.evidence.latestEvidenceAt) && new Date(input.evidence.latestEvidenceAt).getTime() < new Date(input.kickoffAt).getTime(), home = input.evidence.homeHistory >= SELECTIVE_PUBLISHING_V1.minimumTeamHistory, away = input.evidence.awayHistory >= SELECTIVE_PUBLISHING_V1.minimumTeamHistory;
  const checks: EligibilityCheck[] = [
    { code: "FINITE_PROBABILITIES", passed: finite }, { code: "VALID_PROBABILITIES", passed: bounded }, { code: "NORMALIZED_PROBABILITIES", passed: normalized }, { code: "VALID_SELECTED_OUTCOME", passed: ["home", "draw", "away"].includes(input.selectedOutcome) && selectedIsArgmax(input) },
    { code: "SUFFICIENT_TEAM_HISTORY", passed: home && away }, { code: "VALID_COMPETITION", passed: Boolean(input.competitionId.trim()) }, { code: "VALID_SEASON", passed: Boolean(input.season.trim()) }, { code: "VALID_FIXTURE", passed: validFixture }, { code: "PRE_KICKOFF_EVIDENCE_ONLY", passed: validEvidenceDate }, { code: "CONFIDENCE_AVAILABLE", passed: input.confidenceScore !== null && Number.isFinite(input.confidenceScore) && input.confidenceScore >= 0 && input.confidenceScore <= 1 }, { code: "SUPPORTED_METHODOLOGY", passed: input.methodology === SELECTIVE_PUBLISHING_V1.predictionMethodology },
  ];
  const reasons: PublishingReasonCode[] = [];
  if (!home && !away) reasons.push("INSUFFICIENT_BOTH_TEAM_HISTORY"); else { if (!home) reasons.push("INSUFFICIENT_HOME_HISTORY"); if (!away) reasons.push("INSUFFICIENT_AWAY_HISTORY"); }
  if (!finite) reasons.push("NON_FINITE_PROBABILITIES"); else if (!bounded) reasons.push("INVALID_PROBABILITIES"); else if (!normalized) reasons.push("UNNORMALIZED_PROBABILITIES");
  if (!["home", "draw", "away"].includes(input.selectedOutcome) || !selectedIsArgmax(input)) reasons.push("INVALID_SELECTED_OUTCOME");
  if (input.confidenceScore === null || !Number.isFinite(input.confidenceScore) || input.confidenceScore < 0 || input.confidenceScore > 1) reasons.push("MISSING_CONFIDENCE_SCORE");
  if (!validFixture) reasons.push("INVALID_FIXTURE"); if (!input.competitionId.trim()) reasons.push("INVALID_COMPETITION"); if (!input.season.trim()) reasons.push("INVALID_SEASON"); if (!validEvidenceDate) reasons.push("LEAKAGE_GUARD_FAILURE"); if (input.methodology !== SELECTIVE_PUBLISHING_V1.predictionMethodology) reasons.push("UNSUPPORTED_METHODOLOGY");
  return { checks, reasons, eligible: checks.every((check) => check.passed) };
}

const compare = (a: SelectivePublishingInput, b: SelectivePublishingInput) => (b.confidenceScore! - a.confidenceScore!) || (maximumProbability(b) - maximumProbability(a)) || (topMargin(b) - topMargin(a)) || (minimumHistory(b) - minimumHistory(a)) || a.fixtureId.localeCompare(b.fixtureId);
const confidenceLabel = (rank: number, total: number): ConfidenceLabel => { const percentile = (total - rank + 1) / total; return percentile > SELECTIVE_PUBLISHING_V1.confidencePercentiles.moderateUpper ? "STRONG" : percentile > SELECTIVE_PUBLISHING_V1.confidencePercentiles.lowUpper ? "MODERATE" : "LOW"; };

export function evaluateSelectivePublishing(inputs: readonly SelectivePublishingInput[], evaluationWindow: string, controls: PublishingControls = DEFAULT_PUBLISHING_CONTROLS): SelectivePublishingResult[] {
  const evaluated = inputs.map((input) => ({ input, ...eligibility(input) })), ranked = evaluated.filter((item) => item.eligible).map((item) => item.input).sort(compare), eligiblePopulationSize = ranked.length, topPickCutoff = eligiblePopulationSize >= SELECTIVE_PUBLISHING_V1.minimumEligiblePopulationForTopPicks ? Math.floor(eligiblePopulationSize * SELECTIVE_PUBLISHING_V1.topPickCoverage) : 0, ranks = new Map(ranked.map((input, index) => [input.fixtureId, index + 1]));
  return evaluated.map(({ input, checks, reasons, eligible }) => { const rank = ranks.get(input.fixtureId) ?? null, percentile = rank === null ? null : (eligiblePopulationSize - rank + 1) / eligiblePopulationSize, baseTier: PublishingTier = !eligible ? "LIMITED_EVIDENCE" : rank! <= topPickCutoff ? "TOP_PICK" : "STANDARD_ANALYSIS", reasonCodes = [...reasons]; if (eligible && !topPickCutoff) reasonCodes.push("INSUFFICIENT_RANKING_POPULATION");
    const suppressed = controls.suppressedFixtureIds.has(input.fixtureId); if (suppressed) reasonCodes.push("MANUALLY_SUPPRESSED"); if (controls.globalPause) reasonCodes.push("PUBLICATION_PAUSED"); if (!controls.publishingEnabled) reasonCodes.push("PUBLISHING_DISABLED"); if (!controls.topPicksEnabled && baseTier === "TOP_PICK") reasonCodes.push("TOP_PICKS_DISABLED");
    const publishable = controls.publishingEnabled && !controls.globalPause && !suppressed, publiclyPresentedTier = !publishable ? null : !controls.topPicksEnabled && baseTier === "TOP_PICK" ? "STANDARD_ANALYSIS" : baseTier;
    return { fixtureId: input.fixtureId, predictionMethodology: input.methodology, confidenceMethodology: SELECTIVE_PUBLISHING_V1.confidenceMethodology, publishingPolicy: SELECTIVE_PUBLISHING_V1.policyId, selectedOutcome: input.selectedOutcome, probabilities: { ...input.probabilities }, confidenceScore: input.confidenceScore, confidenceLabel: rank === null || !SELECTIVE_PUBLISHING_V1.confidenceLabelsEnabled ? null : confidenceLabel(rank, eligiblePopulationSize), publishingTier: baseTier, eligibility: checks, reasonCodes, rankingMetadata: { populationSize: inputs.length, eligiblePopulationSize, rank, percentile, topPickCutoff, rankingPolicy: SELECTIVE_PUBLISHING_V1.rankingPopulation, evaluationWindow }, publicationState: { publishable, publiclyPresentedTier, suppressed, paused: controls.globalPause } } satisfies SelectivePublishingResult; });
}

export function publicPublicationResults(results: readonly SelectivePublishingResult[]) { return results.filter((result) => result.publicationState.publishable); }
export function publicTopPicks(results: readonly SelectivePublishingResult[]) { return publicPublicationResults(results).filter((result) => result.publicationState.publiclyPresentedTier === "TOP_PICK"); }
export function applyAdminPublicationCommand(controls: PublishingControls, command: AdminPublicationCommand): PublishingControls { const suppressed = new Set(controls.suppressedFixtureIds); if (command.type === "SUPPRESS") suppressed.add(command.fixtureId); if (command.type === "UNSUPPRESS") suppressed.delete(command.fixtureId); return command.type === "PAUSE_PUBLICATION" ? { ...controls, globalPause: command.paused } : { ...controls, suppressedFixtureIds: suppressed }; }
