"use client";
import { useState } from "react";
import Link from "next/link";
import type { PaymentMethod } from "@/modules/billing/domain";
import { businessPaymentConfig, paymentReceiptMessage } from "@/config/payment";
import { formatNaira } from "@/config/pricing";
import { brand, whatsappUrl } from "@/config/brand";

export function PlatformCheckout({packageName,amount,managedPlatformMonthly,methods}:{packageName:string;amount:number;managedPlatformMonthly:number;methods:PaymentMethod[]}) {
  const [selected,setSelected]=useState("manual-bank"),[accepted,setAccepted]=useState(false),availableMethods=methods.filter(method=>method.enabled);
  return <div className="checkout-layout"><div className="checkout-main"><div className="checkout-status"><span>Order status</span><b>Pending Payment</b><p>This remains pending until {brand.companyName} manually verifies your transfer.</p></div><section className="payment-methods"><span className="eyebrow">Payment method</span>{availableMethods.map(method=><label className="available" key={method.id}><input type="radio" name="paymentMethod" value={method.id} checked={selected===method.id} onChange={()=>setSelected(method.id)}/><span><b>{method.label}</b><small>Available</small></span></label>)}</section>{selected==="manual-bank"&&<section className="bank-transfer-box"><div className="bank-heading"><span>Pay by Bank Transfer</span><b>{formatNaira(amount)}</b></div><dl><div><dt>Account Name</dt><dd>{businessPaymentConfig.bankTransfer.accountName}</dd></div><div><dt>Bank</dt><dd>{businessPaymentConfig.bankTransfer.displayBankName}</dd></div><div><dt>Account Number</dt><dd className="account-number">{businessPaymentConfig.bankTransfer.accountNumber}</dd></div><div><dt>Amount</dt><dd>{formatNaira(amount)}</dd></div></dl><label className="checkout-terms"><input type="checkbox" checked={accepted} onChange={event=>setAccepted(event.target.checked)}/><span>I have read and agree to the <Link href="/business-terms">Business Terms</Link> and <Link href="/refund-policy">Refund/Cancellation Policy</Link>.</span></label><ol><li>Review and accept the linked terms before proceeding.</li><li>Transfer the exact amount to the {brand.companyName} bank account shown above.</li><li>Keep your payment receipt or transaction confirmation.</li><li>Send the receipt through WhatsApp for verification.</li></ol>{accepted?<a className="button receipt-button" href={whatsappUrl(paymentReceiptMessage(packageName))} target="_blank" rel="noopener noreferrer">Send Payment Receipt on WhatsApp</a>:<button className="button receipt-button" type="button" disabled>Accept the terms to continue</button>}<p className="receipt-note">Opening WhatsApp does not confirm payment. Platform setup begins only after payment is manually verified.</p></section>}</div><aside className="checkout-summary"><span className="eyebrow">Platform setup order</span><h1>{packageName}</h1><div><span>Founder setup price</span><b>{formatNaira(amount)}</b></div><div><span>Managed Platform Plan</span><b>First 6 months included</b></div><div><span>From month 7</span><b>{formatNaira(managedPlatformMonthly)}/month</b></div><div><span>Payment method</span><b>Manual Bank Transfer</b></div><div><span>Current status</span><b>Pending Payment</b></div><p>This order purchases software development and configuration for your branded platform. Managed service supports its ongoing infrastructure.</p><Link className="text-link" href="/sales">← Return to package details</Link></aside></div>;
}
