import type { Metadata } from "next";
import Link from "next/link";
import { LegalDocument } from "@/components/legal-document";
import { getSiteUrl } from "@/config/site";
export const metadata:Metadata={title:"Terms of Use",description:"Terms governing use of the 9ja Football AI website and football-intelligence service.",alternates:{canonical:`${getSiteUrl()}/terms`}};
export default function Page(){return <LegalDocument eyebrow="Legal" title="Terms of Use" intro="These terms govern access to 9ja Football AI, a football-intelligence technology service operated by FABRO TECH LIMITED.">
<h2>1. The service</h2><p>9ja Football AI provides football information, statistics, probability-based predictions and analytical intelligence. FABRO TECH LIMITED is a technology and software provider. It is not a bookmaker, does not accept wagers and does not place bets for users.</p>
<h2>2. Informational analysis</h2><p>Predictions are probabilistic, may be incomplete or wrong, and do not guarantee accuracy, a sporting result or financial profit. You remain solely responsible for how you use the information and for every financial or betting decision you make.</p>
<h2>3. Eligibility and lawful use</h2><p>You may use the service only where lawful and, where betting-related information is involved, only if you meet the legal age and other requirements in your jurisdiction. Do not use the service to violate applicable law or third-party rights.</p>
<h2>4. Accounts</h2><p>You must provide accurate account information, protect your credentials and promptly report suspected unauthorized access. You are responsible for activity conducted through your account. We may restrict an account where reasonably necessary for security, abuse prevention or compliance.</p>
<h2>5. Acceptable conduct</h2><p>Do not interfere with the service, attempt unauthorized access, scrape or overload it, distribute malware, impersonate another person, misuse predictions as guaranteed claims, or reproduce protected content commercially without permission.</p>
<h2>6. Access and subscriptions</h2><p>Some features may be public, account-limited or available under a paid plan. Feature availability, limits and prices shown at the time of purchase apply, subject to applicable law. Paid consumer functionality will be governed by the checkout terms presented when that functionality is activated.</p>
<h2>7. Data and third-party services</h2><p>Football data, hosting, authentication and other functionality may depend on third-party providers. Their availability, terms and data can change. We do not control match postponements, source-data errors or third-party outages.</p>
<h2>8. Intellectual property</h2><p>9ja Football AI, its software, presentation, analysis methods, branding and original content are owned by or licensed to FABRO TECH LIMITED. These terms grant personal, revocable use of the service; they do not transfer source code or intellectual-property ownership.</p>
<h2>9. Availability and changes</h2><p>We aim to operate a reliable service but do not promise uninterrupted availability. Coverage may expand or change by competition. We may maintain, improve, suspend or retire features and may update these terms with the revised date displayed here.</p>
<h2>10. Suspension and termination</h2><p>We may suspend or terminate access for material breach, unlawful activity, security risk or misuse. You may stop using the service at any time. Accrued payment obligations and provisions intended to survive termination remain effective.</p>
<h2>11. Disclaimers and liability</h2><p>The service is supplied on an “as available” basis to the extent permitted by law. FABRO TECH LIMITED is not liable for betting losses, missed opportunities, decisions made from predictions, or indirect or consequential loss. Nothing here excludes liability that cannot lawfully be excluded.</p>
<h2>12. Related policies</h2><p>Use is also subject to our <Link href="/privacy">Privacy Policy</Link> and <Link href="/responsible-gaming">Responsible Use guidance</Link>. Business platform purchases are governed additionally by the <Link href="/business-terms">Business Terms</Link> and <Link href="/refund-policy">Refund and Cancellation Policy</Link>.</p>
</LegalDocument>}
