import type { HistoricalSplit, MatchAnalysisInput, MatchAnalysisTeam } from "@/modules/football-data/historical";
import type { IntelligenceConfidence, MatchIntelligenceResult } from "../domain";
import { HISTORICAL_V3_MODEL_VERSION, historicalV3Parameters, type HistoricalV3Parameters } from "./config";
import { createPoissonScoreMatrix } from "./poisson";

const clamp = (value: number, minimum: number, maximum: number) => Math.min(maximum, Math.max(minimum, value));
const round = (value: number) => Number(value.toFixed(4));
const rate = (goals: number, played: number, fallback: number) => played ? goals / played : fallback;
function venueRate(team: MatchAnalysisTeam, split: HistoricalSplit, field: "goalsFor" | "goalsAgainst", leagueFallback: number, parameters: HistoricalV3Parameters) {
  const overall = rate(team.profile[field], team.profile.played, leagueFallback);
  if (!split.played) return { value: overall, source: team.profile.played ? "overall" : "league" } as const;
  if (!parameters.venuePseudoMatches) return { value: split[field] / split.played, source: "venue" } as const;
  return { value: (split[field] + parameters.venuePseudoMatches * overall * parameters.overallWeight) / (split.played + parameters.venuePseudoMatches * parameters.overallWeight), source: "venue-overall-blend" } as const;
}
export function createHistoricalV3MatchIntelligence(input: MatchAnalysisInput, parameters: HistoricalV3Parameters = historicalV3Parameters): MatchIntelligenceResult {
  const leagueHome = input.leagueScoring.homeGoalsPerMatch ?? 1.35, leagueAway = input.leagueScoring.awayGoalsPerMatch ?? 1.1;
  const homeAttack = venueRate(input.homeTeam, input.homeTeam.relevantForm, "goalsFor", leagueHome, parameters), homeDefence = venueRate(input.homeTeam, input.homeTeam.relevantForm, "goalsAgainst", leagueAway, parameters), awayAttack = venueRate(input.awayTeam, input.awayTeam.relevantForm, "goalsFor", leagueAway, parameters), awayDefence = venueRate(input.awayTeam, input.awayTeam.relevantForm, "goalsAgainst", leagueHome, parameters);
  const homeLambda = clamp(leagueHome * (homeAttack.value / leagueHome) * (awayDefence.value / leagueHome), parameters.minimumLambda, parameters.maximumLambda), awayLambda = clamp(leagueAway * (awayAttack.value / leagueAway) * (homeDefence.value / leagueAway), parameters.minimumLambda, parameters.maximumLambda), matrix = createPoissonScoreMatrix(homeLambda, awayLambda);
  let homeWin = 0, draw = 0, awayWin = 0, over15 = 0, over25 = 0, over35 = 0, bttsYes = 0;
  for (const score of matrix.scorelines) { if (score.homeGoals > score.awayGoals) homeWin += score.probability; else if (score.homeGoals === score.awayGoals) draw += score.probability; else awayWin += score.probability; const total = score.homeGoals + score.awayGoals; if (total > 1.5) over15 += score.probability; if (total > 2.5) over25 += score.probability; if (total > 3.5) over35 += score.probability; if (score.homeGoals > 0 && score.awayGoals > 0) bttsYes += score.probability; }
  const probabilities = { homeWin: round(homeWin), draw: round(draw), awayWin: round(1 - round(homeWin) - round(draw)) }, maximum = Math.max(homeWin, draw, awayWin), sorted = [homeWin, draw, awayWin].sort((a, b) => b - a), margin = sorted[0] - sorted[1], entropy = -[homeWin, draw, awayWin].reduce((sum, value) => sum + value * Math.log(Math.max(value, 1e-12)), 0) / Math.log(3), evidence = Math.min(input.context.historicalSampleSize / 20, 1), confidence: IntelligenceConfidence = evidence >= 1 && maximum >= .55 && margin >= .15 && entropy <= .85 ? "strong" : evidence >= .5 && maximum >= .42 ? "moderate" : "low";
  return { modelVersion: HISTORICAL_V3_MODEL_VERSION, homeTeam: { id: input.homeTeam.profile.team.id, name: input.homeTeam.profile.team.name }, awayTeam: { id: input.awayTeam.profile.team.id, name: input.awayTeam.profile.team.name }, probabilities, goalMarkets: { over15: round(over15), over25: round(over25), over35: round(over35), bttsYes: round(bttsYes), bttsNo: round(1 - round(bttsYes)) }, goalExpectation: { expectedHomeGoals: round(homeLambda), expectedAwayGoals: round(awayLambda), expectedTotalGoals: round(homeLambda + awayLambda), methodology: "historical-poisson-goal-distribution" }, strength: { home: round(homeLambda), away: round(awayLambda), differential: round(homeLambda - awayLambda) }, confidence, dataQuality: { classification: input.context.dataCompleteness, confidence, historicalSampleSize: input.context.historicalSampleSize, recentSampleSize: input.context.recentSampleSize, homeVenueSampleSize: input.homeTeam.relevantForm.played, awayVenueSampleSize: input.awayTeam.relevantForm.played, h2hSampleSize: input.context.h2hSampleSize, latestDataDate: input.context.latestDataDate }, supportingFactors: [{ type: "poisson_goal_distribution", context: "match", direction: "neutral", strength: "moderate", summary: `1X2 and goal markets share one normalized Poisson score matrix; data sources: ${homeAttack.source}/${homeDefence.source} and ${awayAttack.source}/${awayDefence.source}.` }, { type: "research_confidence", context: "data", direction: "neutral", strength: maximum >= .55 ? "strong" : "slight", summary: `Research diagnostics: max probability ${round(maximum)}, margin ${round(margin)}, normalized entropy ${round(entropy)}.` }] };
}
