import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { SiteHeader } from "@/components/site-header";
import { SiteFooter } from "@/components/site-footer";
import { fixtureService, intelligenceService } from "@/modules/intelligence/application";
import { NotFoundError } from "@/modules/intelligence/errors";

export function generateStaticParams(){return fixtureService.getDemoFixtures().map(item=>({fixtureId:item.id}))}
export async function generateMetadata({params}:{params:Promise<{fixtureId:string}>}):Promise<Metadata>{const{fixtureId}=await params;try{const report=intelligenceService.getIntelligenceForFixture(fixtureId);return{title:`${report.fixture.homeTeam.name} vs ${report.fixture.awayTeam.name} Demo Analysis`,description:`Demonstration football intelligence report for ${report.fixture.homeTeam.name} vs ${report.fixture.awayTeam.name}.`}}catch{return{title:"Match Analysis Unavailable"}}}
export default async function MatchDetailPage({params}:{params:Promise<{fixtureId:string}>}){const{fixtureId}=await params;let report;try{report=intelligenceService.getIntelligenceForFixture(fixtureId)}catch(error){if(error instanceof NotFoundError)notFound();throw error}const{fixture,prediction,competition}=report;return <><SiteHeader/><main className="report-page"><section className="report-hero"><div className="grid-lines"/><div className="container"><div className="report-top"><span>{competition.name}</span><em>Demonstration report</em><time>{fixture.displayKickoff}</time></div><div className="report-fixture"><div><i>{fixture.homeTeam.shortName}</i><h1>{fixture.homeTeam.name}</h1><small>{report.homeForm.sequence.join(" · ")}</small></div><span>VS</span><div><i>{fixture.awayTeam.shortName}</i><h1>{fixture.awayTeam.name}</h1><small>{report.awayForm.sequence.join(" · ")}</small></div></div><p>Fixture status: <b>{fixture.status}</b> · Data source: <b>{report.source.sourceLabel}</b></p></div></section><section className="section"><div className="container report-layout"><article className="report-primary"><span className="eyebrow">AI match intelligence</span><h2>{prediction.market.label}</h2><p>{report.shortAnalysis}</p><div className="report-score-grid"><div><small>Confidence</small><b>{prediction.confidence.value}%</b><i className="report-meter"><span style={{width:`${prediction.confidence.value}%`}}/></i></div><div><small>Risk</small><b className={`risk-text ${prediction.risk}`}>{prediction.risk}</b></div><div><small>Status</small><b>{prediction.status}</b></div></div><h3>Reasoning</h3><ul>{prediction.reasoning.bullets.map(item=><li key={item}>{item}</li>)}</ul></article><aside className="report-support"><div><h3>Supporting factors</h3>{prediction.reasoning.supportingFactors.map(item=><span key={item}>✓ {item}</span>)}</div><div><h3>Recent form</h3><p><b>{fixture.homeTeam.shortName}</b> {report.homeForm.summary}</p><p><b>{fixture.awayTeam.shortName}</b> {report.awayForm.summary}</p></div><div><h3>Head to head</h3><p>{report.statistics.headToHeadSummary}</p></div><small>Generated from structured mock data at {new Date(report.generatedAt).toLocaleDateString("en-NG")}. This report was not generated live.</small></aside></div></section><section className="responsible"><div className="container"><span>!</span><div><h2>Demo intelligence—not guaranteed outcomes</h2><p>This analysis is for demonstration and informational purposes. Football is unpredictable, and betting involves financial risk. Never wager money you cannot afford to lose.</p></div></div></section><div className="container report-back"><Link href="/matches" className="text-link">← Back to Match Centre</Link></div></main><SiteFooter/></>}
