import { buildMatchAnalysisInput, isCompletedFixture, type HistoricalDataset, type HistoricalFixture } from "@/modules/football-data/historical";
import { createHistoricalMatchIntelligence, type MatchIntelligenceEngine, type ProbabilityTriple } from "@/modules/football-intelligence";
import type { AccuracyMetric, BacktestOptions, BacktestPrediction, BacktestReport, BaselineEvaluation, CalibrationBucket, DiagnosticPrediction, GoalMarketEvaluation, GoalMarketKey, MatchOutcome, ProbabilityMetric, TeamEvaluation } from "./domain";

const outcome = (fixture: HistoricalFixture): MatchOutcome => fixture.homeScore! > fixture.awayScore! ? "home" : fixture.homeScore! < fixture.awayScore! ? "away" : "draw";
const picked = (probability: ProbabilityTriple): MatchOutcome => probability.homeWin >= probability.draw && probability.homeWin >= probability.awayWin ? "home" : probability.awayWin >= probability.draw ? "away" : "draw";
const probabilityFor = (probability: ProbabilityTriple, result: MatchOutcome) => result === "home" ? probability.homeWin : result === "draw" ? probability.draw : probability.awayWin;
const average = (values: number[]) => values.length ? values.reduce((sum, value) => sum + value, 0) / values.length : null;
const accuracy = (items: Array<{ correct: boolean }>): AccuracyMetric => ({ predictions: items.length, correct: items.filter((item) => item.correct).length, accuracy: items.length ? items.filter((item) => item.correct).length / items.length : null });
const brier = (items: BacktestPrediction[]) => average(items.map((item) => (item.probabilities.homeWin - Number(item.actualOutcome === "home")) ** 2 + (item.probabilities.draw - Number(item.actualOutcome === "draw")) ** 2 + (item.probabilities.awayWin - Number(item.actualOutcome === "away")) ** 2));
const logLoss = (items: BacktestPrediction[]) => average(items.map((item) => -Math.log(Math.max(1e-12, probabilityFor(item.probabilities, item.actualOutcome)))));
const bucketDefinitions = [{ label: "below 40%", minimum: 0, maximum: 0.4 }, { label: "40-49%", minimum: 0.4, maximum: 0.5 }, { label: "50-59%", minimum: 0.5, maximum: 0.6 }, { label: "60-69%", minimum: 0.6, maximum: 0.7 }, { label: "70-79%", minimum: 0.7, maximum: 0.8 }, { label: "80-89%", minimum: 0.8, maximum: 0.9 }, { label: "90%+", minimum: 0.9, maximum: 1.000001 }];
function calibration(items: Array<{ probability: number; occurred: boolean }>): CalibrationBucket[] { return bucketDefinitions.map((bucket) => { const selected = items.filter((item) => item.probability >= bucket.minimum && item.probability < bucket.maximum), averageProbability = average(selected.map((item) => item.probability)), observedRate = selected.length ? selected.filter((item) => item.occurred).length / selected.length : null; return { ...bucket, predictions: selected.length, averageProbability, observedRate, calibrationGap: averageProbability === null || observedRate === null ? null : observedRate - averageProbability, lowSample: selected.length < 20 }; }); }
function marketEvaluation(predictions: BacktestPrediction[], key: GoalMarketKey, threshold: number): GoalMarketEvaluation { const items = predictions.flatMap((prediction) => { const probability = prediction.goalMarkets[key]; if (probability === null) return []; const total = prediction.fixture.homeScore! + prediction.fixture.awayScore!, occurred = key === "over15" ? total > 1.5 : key === "over25" ? total > 2.5 : key === "over35" ? total > 3.5 : key === "bttsYes" ? prediction.fixture.homeScore! > 0 && prediction.fixture.awayScore! > 0 : prediction.fixture.homeScore! === 0 || prediction.fixture.awayScore! === 0; return [{ probability, occurred, correct: (probability >= threshold) === occurred }]; }); const base = accuracy(items); return { ...base, threshold, brierScore: average(items.map((item) => (item.probability - Number(item.occurred)) ** 2)), logLoss: average(items.map((item) => -(item.occurred ? Math.log(Math.max(1e-12, item.probability)) : Math.log(Math.max(1e-12, 1 - item.probability))))), averageProbability: average(items.map((item) => item.probability)), observedRate: items.length ? items.filter((item) => item.occurred).length / items.length : null, calibration: calibration(items) }; }
function quality(items: BacktestPrediction[]): ProbabilityMetric { return { ...accuracy(items), brierScore: brier(items), logLoss: logLoss(items) }; }

function baselineMetrics(name: string, methodology: string, records: Array<{ probabilities: ProbabilityTriple; actual: MatchOutcome }>): BaselineEvaluation { const evaluated = records.map((record) => ({ ...record, predicted: picked(record.probabilities), correct: picked(record.probabilities) === record.actual })); return { name, methodology, predictions: records.length, topPickAccuracy: evaluated.length ? evaluated.filter((item) => item.correct).length / evaluated.length : null, multiclassBrierScore: average(records.map((item) => (item.probabilities.homeWin - Number(item.actual === "home")) ** 2 + (item.probabilities.draw - Number(item.actual === "draw")) ** 2 + (item.probabilities.awayWin - Number(item.actual === "away")) ** 2)), logLoss: average(records.map((item) => -Math.log(Math.max(1e-12, probabilityFor(item.probabilities, item.actual))))) }; }
function priorFrequency(dataset: HistoricalDataset): ProbabilityTriple { const completed = dataset.fixtures.filter(isCompletedFixture); if (!completed.length) return { homeWin: 1 / 3, draw: 1 / 3, awayWin: 1 / 3 }; const counts = { home: 0, draw: 0, away: 0 }; for (const fixture of completed) counts[outcome(fixture)]++; return { homeWin: counts.home / completed.length, draw: counts.draw / completed.length, awayWin: counts.away / completed.length }; }
function diagnostic(item: BacktestPrediction): DiagnosticPrediction { const selected = probabilityFor(item.probabilities, item.predictedOutcome), actualTotal = item.fixture.homeScore! + item.fixture.awayScore!, expected = item.expectedGoals.total; return { fixtureId: item.fixture.providerFixtureId, match: `${item.homeTeamName} vs ${item.awayTeamName}`, kickoffAt: item.fixture.kickoffAt, predictedOutcome: item.predictedOutcome, actualOutcome: item.actualOutcome, predictedProbability: selected, confidence: item.confidence, expectedTotalGoals: expected, actualTotalGoals: actualTotal, absoluteGoalError: expected === null ? null : Math.abs(expected - actualTotal) }; }

export function runHistoricalBacktest(dataset: HistoricalDataset, supplied: BacktestOptions = {}, intelligenceEngine: MatchIntelligenceEngine = createHistoricalMatchIntelligence): BacktestReport {
  const options = { minimumPriorMatches: supplied.minimumPriorMatches ?? 5, recentN: supplied.recentN ?? 5, marketThreshold: supplied.marketThreshold ?? 0.5 }, completed = dataset.fixtures.filter(isCompletedFixture).sort((a, b) => new Date(a.kickoffAt).getTime() - new Date(b.kickoffAt).getTime()), predictions: BacktestPrediction[] = [], skippedReasons: Record<string, number> = {}, frequencyBaselines: Array<{ probabilities: ProbabilityTriple; actual: MatchOutcome }> = [];
  for (const target of completed) {
    const cutoff = new Date(target.kickoffAt).getTime(), priorFixtures = completed.filter((fixture) => new Date(fixture.kickoffAt).getTime() < cutoff), prior: HistoricalDataset = { ...dataset, fixtures: priorFixtures };
    const homePrior = priorFixtures.filter((fixture) => fixture.homeTeamId === target.homeTeamId || fixture.awayTeamId === target.homeTeamId).length, awayPrior = priorFixtures.filter((fixture) => fixture.homeTeamId === target.awayTeamId || fixture.awayTeamId === target.awayTeamId).length;
    if (homePrior < options.minimumPriorMatches || awayPrior < options.minimumPriorMatches) { const reason = homePrior < options.minimumPriorMatches && awayPrior < options.minimumPriorMatches ? "both_teams_insufficient_history" : homePrior < options.minimumPriorMatches ? "home_team_insufficient_history" : "away_team_insufficient_history"; skippedReasons[reason] = (skippedReasons[reason] ?? 0) + 1; continue; }
    const input = buildMatchAnalysisInput(prior, target.homeTeamId, target.awayTeamId, { analysisDate: target.kickoffAt, recentN: options.recentN }), intelligence = intelligenceEngine(input), actualOutcome = outcome(target), predictedOutcome = picked(intelligence.probabilities), home = dataset.teams.find((team) => team.id === target.homeTeamId)!, away = dataset.teams.find((team) => team.id === target.awayTeamId)!;
    const directional = intelligence.supportingFactors.filter((factor) => factor.direction === "supports_home" || factor.direction === "supports_away"), expectedDirection = predictedOutcome === "home" ? "supports_home" : predictedOutcome === "away" ? "supports_away" : "neutral";
    predictions.push({ fixture: target, homeTeamName: home.name, awayTeamName: away.name, probabilities: intelligence.probabilities, predictedOutcome, actualOutcome, correct: predictedOutcome === actualOutcome, confidence: intelligence.confidence, modelVersion: intelligence.modelVersion, goalMarkets: intelligence.goalMarkets, expectedGoals: { home: intelligence.goalExpectation.expectedHomeGoals, away: intelligence.goalExpectation.expectedAwayGoals, total: intelligence.goalExpectation.expectedTotalGoals }, evidence: { priorFixtureIds: priorFixtures.map((fixture) => fixture.providerFixtureId), homeHistoricalMatches: homePrior, awayHistoricalMatches: awayPrior, historicalSampleSize: intelligence.dataQuality.historicalSampleSize, recentSampleSize: intelligence.dataQuality.recentSampleSize, h2hSampleSize: intelligence.dataQuality.h2hSampleSize, homeVenueSampleSize: intelligence.dataQuality.homeVenueSampleSize, awayVenueSampleSize: intelligence.dataQuality.awayVenueSampleSize, latestDataDate: intelligence.dataQuality.latestDataDate, strengthDifferential: intelligence.strength.differential, directionalFactors: directional.length, agreeingFactors: directional.filter((factor) => factor.direction === expectedDirection).length } });
    frequencyBaselines.push({ probabilities: priorFrequency(prior), actual: actualOutcome });
  }
  const confidence = Object.fromEntries((["low", "moderate", "strong"] as const).map((level) => [level, quality(predictions.filter((item) => item.confidence === level))])) as BacktestReport["confidence"];
  const goalMarkets = Object.fromEntries((["over15", "over25", "over35", "bttsYes", "bttsNo"] as const).map((key) => [key, marketEvaluation(predictions, key, options.marketThreshold)])) as BacktestReport["goalMarkets"];
  const expected = predictions.filter((item) => item.expectedGoals.home !== null && item.expectedGoals.away !== null && item.expectedGoals.total !== null), diagnostics = predictions.map(diagnostic);
  const teams: TeamEvaluation[] = dataset.teams.map((team) => { const items = predictions.filter((item) => item.fixture.homeTeamId === team.id || item.fixture.awayTeamId === team.id); return { teamId: team.id, teamName: team.name, ...quality(items) }; }).filter((team) => team.predictions > 0).sort((a, b) => b.predictions - a.predictions || a.teamName.localeCompare(b.teamName));
  return { modelVersion: predictions[0]?.modelVersion ?? "historical-v1", options, dataset: { totalFixtures: dataset.fixtures.length, completedFixtures: completed.length, eligibleFixtures: predictions.length, skippedFixtures: completed.length - predictions.length, skippedReasons, earliestFixture: completed[0]?.kickoffAt ?? null, latestFixture: completed.at(-1)?.kickoffAt ?? null }, predictions, oneXTwo: { overall: accuracy(predictions), multiclassBrierScore: brier(predictions), logLoss: logLoss(predictions), byPick: { home: accuracy(predictions.filter((item) => item.predictedOutcome === "home")), draw: accuracy(predictions.filter((item) => item.predictedOutcome === "draw")), away: accuracy(predictions.filter((item) => item.predictedOutcome === "away")) }, actualResults: { home: predictions.filter((item) => item.actualOutcome === "home").length, draw: predictions.filter((item) => item.actualOutcome === "draw").length, away: predictions.filter((item) => item.actualOutcome === "away").length } }, calibration: calibration(predictions.map((item) => ({ probability: probabilityFor(item.probabilities, item.predictedOutcome), occurred: item.correct }))), confidence, goalMarkets, goalExpectation: { predictions: expected.length, homeMae: average(expected.map((item) => Math.abs(item.expectedGoals.home! - item.fixture.homeScore!))), awayMae: average(expected.map((item) => Math.abs(item.expectedGoals.away! - item.fixture.awayScore!))), totalMae: average(expected.map((item) => Math.abs(item.expectedGoals.total! - item.fixture.homeScore! - item.fixture.awayScore!))) }, baselines: [baselineMetrics("equal-1x2", "Equal 33.33% probability for home, draw and away; deterministic tie handling selects home only for top-pick reporting.", predictions.map((item) => ({ probabilities: { homeWin: 1 / 3, draw: 1 / 3, awayWin: 1 / 3 }, actual: item.actualOutcome }))), baselineMetrics("prior-result-frequency", "Point-in-time home/draw/away frequencies from all competition fixtures completed before kickoff.", frequencyBaselines)], teams, diagnostics: { strongestCorrect: diagnostics.filter((item) => item.predictedOutcome === item.actualOutcome).sort((a, b) => b.predictedProbability - a.predictedProbability).slice(0, 5), strongestIncorrect: diagnostics.filter((item) => item.predictedOutcome !== item.actualOutcome).sort((a, b) => b.predictedProbability - a.predictedProbability).slice(0, 5), highConfidenceFailures: diagnostics.filter((item) => item.confidence === "strong" && item.predictedOutcome !== item.actualOutcome).sort((a, b) => b.predictedProbability - a.predictedProbability).slice(0, 5), lowConfidenceSuccesses: diagnostics.filter((item) => item.confidence === "low" && item.predictedOutcome === item.actualOutcome).sort((a, b) => b.predictedProbability - a.predictedProbability).slice(0, 5), largestGoalErrors: diagnostics.filter((item) => item.absoluteGoalError !== null).sort((a, b) => b.absoluteGoalError! - a.absoluteGoalError!).slice(0, 5) } };
}
