import type { DrawLikeThresholds, StructuralFeatureKey, StructuralFeatureRow } from "./domain";
const mean = (values: number[]) => values.length ? values.reduce((sum, value) => sum + value, 0) / values.length : null;
const median = (values: number[]) => { if (!values.length) return null; const sorted = [...values].sort((a, b) => a - b), middle = Math.floor(sorted.length / 2); return sorted.length % 2 ? sorted[middle] : (sorted[middle - 1] + sorted[middle]) / 2; };
const variance = (values: number[]) => { const centre = mean(values); return centre === null ? null : values.reduce((sum, value) => sum + (value - centre) ** 2, 0) / values.length; };
const values = (rows: StructuralFeatureRow[], key: StructuralFeatureKey) => rows.flatMap((row) => row.features[key] === null ? [] : [row.features[key]]);
export const percentile = (items: number[], p: number) => { const sorted = [...items].sort((a, b) => a - b); if (!sorted.length) throw new Error("Cannot derive a percentile from an empty development sample."); return sorted[Math.min(sorted.length - 1, Math.floor((sorted.length - 1) * p))]; };
export function auc(rows: StructuralFeatureRow[], key: StructuralFeatureKey) { const draws = values(rows.filter((row) => row.actualDraw), key), others = values(rows.filter((row) => !row.actualDraw), key); if (!draws.length || !others.length) return null; let wins = 0; for (const draw of draws) for (const other of others) wins += draw > other ? 1 : draw === other ? .5 : 0; return wins / (draws.length * others.length); }
export function featureDiagnostic(rows: StructuralFeatureRow[], key: StructuralFeatureKey) { const draw = values(rows.filter((row) => row.actualDraw), key), nonDraw = values(rows.filter((row) => !row.actualDraw), key), drawMean = mean(draw), nonDrawMean = mean(nonDraw), pooled = draw.length && nonDraw.length ? Math.sqrt((((draw.length - 1) * (variance(draw) ?? 0)) + ((nonDraw.length - 1) * (variance(nonDraw) ?? 0))) / Math.max(1, draw.length + nonDraw.length - 2)) : 0; return { sample: draw.length + nonDraw.length, missing: rows.length - draw.length - nonDraw.length, drawMean, nonDrawMean, drawMedian: median(draw), nonDrawMedian: median(nonDraw), difference: drawMean === null || nonDrawMean === null ? null : drawMean - nonDrawMean, standardizedMeanDifference: drawMean === null || nonDrawMean === null || !pooled ? null : (drawMean - nonDrawMean) / pooled, auc: auc(rows, key) }; }
export function deriveDrawLikeThresholds(rows: StructuralFeatureRow[]): DrawLikeThresholds { return { gapMaximum: percentile(rows.map((row) => row.existing.homeAwayGap), 1 / 3), drawProbabilityMinimum: percentile(rows.map((row) => row.existing.drawProbability), 2 / 3), strengthSimilarityMinimum: percentile(rows.map((row) => row.existing.strengthSimilarity), 2 / 3), expectedGoalGapMaximum: percentile(rows.flatMap((row) => row.existing.expectedGoalGap === null ? [] : [row.existing.expectedGoalGap]), 1 / 3) }; }
export function drawLikeA(row: StructuralFeatureRow, thresholds: DrawLikeThresholds) { return row.existing.homeAwayGap <= thresholds.gapMaximum && row.existing.drawProbability >= thresholds.drawProbabilityMinimum; }
export function drawLikeB(row: StructuralFeatureRow, thresholds: DrawLikeThresholds) { return row.existing.strengthSimilarity >= thresholds.strengthSimilarityMinimum && row.existing.expectedGoalGap !== null && row.existing.expectedGoalGap <= thresholds.expectedGoalGapMaximum; }
export function directionByLeague(rows: StructuralFeatureRow[], key: StructuralFeatureKey) { return Object.fromEntries([...new Set(rows.map((row) => row.league))].map((league) => [league, featureDiagnostic(rows.filter((row) => row.league === league), key).difference])); }
export function directionByThird(rows: StructuralFeatureRow[], key: StructuralFeatureKey) { const sorted = [...rows].sort((a, b) => a.kickoffAt.localeCompare(b.kickoffAt) || a.fixtureId.localeCompare(b.fixtureId)); return [0, 1, 2].map((index) => featureDiagnostic(sorted.slice(Math.floor(sorted.length * index / 3), index === 2 ? sorted.length : Math.floor(sorted.length * (index + 1) / 3)), key).difference); }
