import { buildMatchAnalysisInput, isCompletedFixture, type HistoricalDataset, type HistoricalFixture } from "@/modules/football-data/historical";
import type { BacktestPrediction } from "@/modules/football-backtesting/domain";
import { createHistoricalMatchIntelligence } from "../engine";
import { calculateHistoricalV2DrawFeatures, createHistoricalV2MatchIntelligence } from "../historical-v2";
import type { StructuralDrawFeatures, StructuralFeatureRow } from "./domain";

const mean = (values: number[]) => values.length ? values.reduce((sum, value) => sum + value, 0) / values.length : null;
const variance = (values: number[]) => { const centre = mean(values); return centre === null ? null : values.reduce((sum, value) => sum + (value - centre) ** 2, 0) / values.length; };
const rate = (values: boolean[]) => values.length ? values.filter(Boolean).length / values.length : null;
const clamp = (value: number) => Math.min(1, Math.max(0, value));
const goals = (fixture: HistoricalFixture, teamId: string) => fixture.homeTeamId === teamId ? { scored: fixture.homeScore!, conceded: fixture.awayScore! } : { scored: fixture.awayScore!, conceded: fixture.homeScore! };
const teamMatches = (fixtures: HistoricalFixture[], teamId: string, venue?: "home" | "away") => fixtures.filter((fixture) => !venue ? fixture.homeTeamId === teamId || fixture.awayTeamId === teamId : venue === "home" ? fixture.homeTeamId === teamId : fixture.awayTeamId === teamId);
const orNull = (...values: Array<number | null>) => values.every((value): value is number => value !== null) ? mean(values as number[]) : null;

function teamStructure(fixtures: HistoricalFixture[], teamId: string) {
  const records = fixtures.map((fixture) => goals(fixture, teamId)), differences = records.map((item) => item.scored - item.conceded), absolute = differences.map(Math.abs), totals = records.map((item) => item.scored + item.conceded), scorelines = new Map<string, number>();
  for (const item of records) { const key = `${item.scored}-${item.conceded}`; scorelines.set(key, (scorelines.get(key) ?? 0) + 1); }
  const concentration = records.length ? [...scorelines.values()].reduce((sum, count) => sum + (count / records.length) ** 2, 0) : null;
  const lastFive = records.slice(-5), lastDifferences = differences.slice(-5), lastDrawIndex = differences.findLastIndex((value) => value === 0), matchesSinceDraw = lastDrawIndex < 0 ? null : differences.length - 1 - lastDrawIndex;
  return {
    count: records.length, meanGoalDifference: mean(differences), goalDifferenceVariance: variance(differences), goalDifferenceStd: variance(differences) === null ? null : Math.sqrt(variance(differences)!), meanAbsoluteGoalDifference: mean(absolute),
    withinOne: rate(absolute.map((value) => value <= 1)), withinTwo: rate(absolute.map((value) => value <= 2)), closeGameRate: rate(absolute.map((value) => value <= 1)), decisiveGameRate: rate(absolute.map((value) => value >= 2)),
    scorelineConcentration: concentration, lowDrawConcentration: rate(records.map((item) => item.scored === item.conceded && item.scored <= 1)), totalGoalVariance: variance(totals), goalsScoredVariance: variance(records.map((item) => item.scored)), goalsConcededVariance: variance(records.map((item) => item.conceded)),
    scoreOneRate: rate(records.map((item) => item.scored === 1)), concedeOneRate: rate(records.map((item) => item.conceded === 1)), scoreZeroRate: rate(records.map((item) => item.scored === 0)), scoreTwoPlusRate: rate(records.map((item) => item.scored >= 2)), concedeZeroRate: rate(records.map((item) => item.conceded === 0)), concedeTwoPlusRate: rate(records.map((item) => item.conceded >= 2)),
    recentDrawRate5: rate(lastFive.map((item) => item.scored === item.conceded)), drawRecencySupport: matchesSinceDraw === null ? 0 : 1 / (1 + matchesSinceDraw), recentDecisiveMargin: mean(lastDifferences.map(Math.abs)), attackDefenceBalance: records.length ? Math.abs(records.reduce((sum, item) => sum + item.scored, 0) / records.length - records.reduce((sum, item) => sum + item.conceded, 0) / records.length) : null,
  };
}

export function calculateStructuralDrawFeatures(dataset: HistoricalDataset, prediction: BacktestPrediction, league: string): StructuralFeatureRow {
  const cutoff = new Date(prediction.fixture.kickoffAt).getTime(), prior = dataset.fixtures.filter((fixture) => isCompletedFixture(fixture) && new Date(fixture.kickoffAt).getTime() < cutoff), homeAll = teamMatches(prior, prediction.fixture.homeTeamId), awayAll = teamMatches(prior, prediction.fixture.awayTeamId), homeVenue = teamMatches(prior, prediction.fixture.homeTeamId, "home"), awayVenue = teamMatches(prior, prediction.fixture.awayTeamId, "away"), home = teamStructure(homeAll, prediction.fixture.homeTeamId), away = teamStructure(awayAll, prediction.fixture.awayTeamId), homeAtVenue = teamStructure(homeVenue, prediction.fixture.homeTeamId), awayAtVenue = teamStructure(awayVenue, prediction.fixture.awayTeamId);
  const input = buildMatchAnalysisInput({ ...dataset, fixtures: prior }, prediction.fixture.homeTeamId, prediction.fixture.awayTeamId), v1 = createHistoricalMatchIntelligence(input), v2 = createHistoricalV2MatchIntelligence(input), existing = calculateHistoricalV2DrawFeatures(input, v1), expectedHome = v1.goalExpectation.expectedHomeGoals, expectedAway = v1.goalExpectation.expectedAwayGoals, expectedTotal = v1.goalExpectation.expectedTotalGoals;
  const overallDifference = home.meanGoalDifference === null || away.meanGoalDifference === null ? null : home.meanGoalDifference - away.meanGoalDifference, venueDifference = homeAtVenue.meanGoalDifference === null || awayAtVenue.meanGoalDifference === null ? null : homeAtVenue.meanGoalDifference - awayAtVenue.meanGoalDifference;
  const features: StructuralDrawFeatures = {
    goalDifferenceVolatility: orNull(home.goalDifferenceStd, away.goalDifferenceStd), volatilitySimilarity: home.goalDifferenceStd === null || away.goalDifferenceStd === null ? null : 1 / (1 + Math.abs(home.goalDifferenceStd - away.goalDifferenceStd)), closeGameRate: orNull(home.closeGameRate, away.closeGameRate), decisiveGameRate: orNull(home.decisiveGameRate, away.decisiveGameRate), scorelineConcentration: orNull(home.scorelineConcentration, away.scorelineConcentration), lowDrawConcentration: orNull(home.lowDrawConcentration, away.lowDrawConcentration), oneGoalConcentration: orNull(home.scoreOneRate, home.concedeOneRate, away.scoreOneRate, away.concedeOneRate), recentDrawRate5: orNull(home.recentDrawRate5, away.recentDrawRate5), drawRecencySupport: orNull(home.drawRecencySupport, away.drawRecencySupport), recentDecisiveMargin: orNull(home.recentDecisiveMargin, away.recentDecisiveMargin), scoringVariance: orNull(home.goalsScoredVariance, home.goalsConcededVariance, away.goalsScoredVariance, away.goalsConcededVariance), attackDefenceBalanceSimilarity: home.attackDefenceBalance === null || away.attackDefenceBalance === null ? null : 1 / (1 + Math.abs(home.attackDefenceBalance - away.attackDefenceBalance)), expectedScorelineConcentration: expectedHome === null || expectedAway === null ? null : 1 / (1 + Math.abs(expectedHome - 1) + Math.abs(expectedAway - 1)), lowTotalBalanceShape: expectedTotal === null ? null : (1 - clamp(expectedTotal / 4)) * existing.strengthProximity, venueAsymmetry: overallDifference === null || venueDifference === null ? null : Math.abs(overallDifference - venueDifference),
  };
  return { league, fixtureId: prediction.fixture.providerFixtureId, kickoffAt: prediction.fixture.kickoffAt, actualDraw: prediction.actualOutcome === "draw", prediction, features, evidence: { homeOverall: homeAll.length, awayOverall: awayAll.length, homeVenue: homeVenue.length, awayVenue: awayVenue.length, recentHome: Math.min(5, homeAll.length), recentAway: Math.min(5, awayAll.length) }, existing: { drawProbability: v2.probabilities.draw, homeAwayGap: Math.abs(v2.probabilities.homeWin - v2.probabilities.awayWin), strengthSimilarity: existing.strengthProximity, expectedGoalGap: expectedHome === null || expectedAway === null ? null : Math.abs(expectedHome - expectedAway) } };
}
