import type { Metadata } from "next";
import { LegalDocument } from "@/components/legal-document";
import { getSiteUrl } from "@/config/site";
export const metadata:Metadata={title:"Business Platform Terms",description:"Terms for branded football-intelligence platform development and managed services from FABRO TECH LIMITED.",alternates:{canonical:`${getSiteUrl()}/business-terms`}};
export default function Page(){return <LegalDocument eyebrow="Business services" title="Platform Development and Service Terms" intro="These terms apply when FABRO TECH LIMITED builds, configures or manages a branded football-intelligence platform for a business client.">
<h2>1. Service scope</h2><p>We provide technology services: configuration, branding, deployment and, where included, managed hosting and infrastructure for a client-specific AI football-intelligence platform. The agreed package, written quotation and confirmed requirements define the project scope.</p>
<h2>2. Packages</h2><h3>Launch Edition</h3><p>A branded platform with a free member-access tier and one paid subscriber tier, together with the Launch features represented on the Sales page.</p><h3>Business Edition</h3><p>An expanded platform with a free member-access tier, two paid subscriber tiers and the additional Business capabilities represented on the Sales page. The second paid tier gives the client an additional monetisation option; subscriber revenue belongs to the client subject to payment-provider fees, applicable law and the client’s arrangements.</p>
<h2>3. Delivery</h2><p>Typical delivery is 7–14 working days for Launch Edition and 14–21 working days for Business Edition. Delivery begins after the required payment is confirmed and all necessary client materials are received. Missing information, delayed approvals, third-party reviews, domain changes or agreed scope changes may extend delivery.</p>
<h2>4. Client responsibilities</h2><p>The client must provide accurate business details, brand name, logo and assets, preferred domain information, subscription pricing decisions, required policies and prompt feedback or approvals. The client is responsible for the legality of its business, marketing, subscriber relationship and supplied content.</p>
<h2>5. Revisions and scope changes</h2><p>We will make reasonable corrections within the agreed scope before launch. New features, substantial redesigns or requirements outside the agreed package are scope changes and may require revised timing and a separate quotation. These terms do not include unlimited revisions.</p>
<h2>6. Third-party services</h2><p>Domains, football-data APIs, AI services, databases, hosting, email and payment processors are subject to third-party availability, verification, terms, coverage and limits. Charges or unusually heavy usage outside the included managed scope may be payable separately after notice and agreement.</p>
<h2>7. Setup payments</h2><p>Setup payments purchase professional software-development, configuration and deployment work. Work begins only after the agreed payment and required materials are received. Refund treatment follows our Refund and Cancellation Policy.</p>
<h2>8. Managed Platform Plan</h2><p>The first six months of managed service are included. From month seven, the current Managed Platform Plan fee is ₦18,000 per month for Launch Edition and ₦24,000 per month for Business Edition.</p><p>The Managed Platform Plan supports the represented hosting, football-data infrastructure, AI infrastructure within fair-use limits, database and backend infrastructure, security maintenance, backups, routine updates and technical support. Major redesigns, new features, custom integrations and services outside the agreed managed scope may be quoted separately.</p><p>Continued managed hosting, infrastructure, maintenance and technical support after the included six-month period are conditional upon payment of the applicable Managed Platform Plan. If the plan is not renewed or payment becomes overdue, FABRO TECH LIMITED may suspend or discontinue the relevant managed services after reasonable notice.</p><p>Managed Platform Plan fees are subject to periodic review and may be changed where reasonably necessary because of changes in operating costs, inflation, exchange rates, third-party service or data-provider charges, hosting or infrastructure requirements, regulatory or tax changes, platform usage or scale, or other material circumstances affecting the cost of providing the managed service.</p><p>Where a fee change affects an existing client, FABRO TECH LIMITED will provide reasonable advance notice before the revised fee takes effect. A client who does not wish to continue at the revised fee may cancel the future Managed Platform Plan before the new fee becomes applicable, subject to any outstanding obligations.</p><p>Where a client generates usage materially above the normal fair-use level—for example unusually high football-data API usage, AI processing, database traffic, bandwidth, storage or other infrastructure consumption—FABRO TECH LIMITED may require an appropriate higher-capacity or custom managed-service arrangement. Any additional recurring charge will be communicated to and agreed with the client before it becomes applicable, except where immediate action is reasonably required to protect platform stability, security or third-party service limits.</p>
<h2>9. Ownership and licence</h2><p>The client retains ownership of its logo and client-supplied content. A domain purchased and owned by the client remains the client’s property. Client subscriber/customer data belongs to the client subject to applicable law and infrastructure arrangements.</p><p>FABRO TECH LIMITED retains its reusable software framework, systems, source code, libraries, methodologies, tooling and platform intellectual property unless a separate written source-code transfer or buyout agreement says otherwise. The client receives the right to operate the delivered branded platform under the agreed service arrangement.</p>
<h2>10. Cancellation and termination</h2><p>A client may cancel future managed service by giving reasonable notice through the agreed contact channel. Access to managed hosting, maintenance and infrastructure may end after the paid service period. We do not promise unsupported portability or source-code transfer. Either party may terminate for material breach that is not remedied after reasonable notice, subject to accrued obligations and applicable law.</p>
<h2>11. Predictions and client operation</h2><p>Predictions and football intelligence provided through the technology are probabilistic and informational; they do not guarantee sporting results, betting success, income, profit or any financial return. A client must not advertise or represent the platform as guaranteeing wins, betting success, income, profits or financial returns.</p><p>FABRO TECH LIMITED is a technology provider and must not be represented as a bookmaker or betting operator. The client remains responsible for its pricing, customers and subscribers, marketing, supplied content and the lawful operation of its business.</p>
</LegalDocument>}
