import type { Metadata } from "next";
import { LegalDocument } from "@/components/legal-document";
import { getSiteUrl } from "@/config/site";
export const metadata:Metadata={title:"Business Platform Terms",description:"Terms for branded football-intelligence platform development and managed services from FABRO TECH LIMITED.",alternates:{canonical:`${getSiteUrl()}/business-terms`}};
export default function Page(){return <LegalDocument eyebrow="Business services" title="Platform Development and Service Terms" intro="These terms apply when FABRO TECH LIMITED builds, configures or manages a branded football-intelligence platform for a business client.">
<h2>1. Service scope</h2><p>We provide technology services: configuration, branding, deployment and, where included, managed hosting and infrastructure for a client-specific AI football-intelligence platform. The agreed package, written quotation and confirmed requirements define the project scope.</p>
<h2>2. Packages</h2><h3>Launch Edition</h3><p>A branded platform with a free member-access tier and one paid subscriber tier, together with the Launch features represented on the Sales page.</p><h3>Business Edition</h3><p>An expanded platform with a free member-access tier, two paid subscriber tiers and the additional Business capabilities represented on the Sales page. The second paid tier gives the client an additional monetisation option; subscriber revenue belongs to the client subject to payment-provider fees, applicable law and the client’s arrangements.</p>
<h2>3. Delivery</h2><p>Typical delivery is 7–14 working days for Launch Edition and 14–21 working days for Business Edition. Delivery begins after the required payment is confirmed and all necessary client materials are received. Missing information, delayed approvals, third-party reviews, domain changes or agreed scope changes may extend delivery.</p>
<h2>4. Client responsibilities</h2><p>The client must provide accurate business details, brand name, logo and assets, preferred domain information, subscription pricing decisions, required policies and prompt feedback or approvals. The client is responsible for the legality of its business, marketing, subscriber relationship and supplied content.</p>
<h2>5. Revisions and scope changes</h2><p>We will make reasonable corrections within the agreed scope before launch. New features, substantial redesigns or requirements outside the agreed package are scope changes and may require revised timing and a separate quotation. These terms do not include unlimited revisions.</p>
<h2>6. Third-party services</h2><p>Domains, football-data APIs, AI services, databases, hosting, email and payment processors are subject to third-party availability, verification, terms, coverage and limits. Charges or unusually heavy usage outside the included managed scope may be payable separately after notice and agreement.</p>
<h2>7. Setup payments</h2><p>Setup payments purchase professional software-development, configuration and deployment work. Work begins only after the agreed payment and required materials are received. Refund treatment follows our Refund and Cancellation Policy.</p>
<h2>8. Managed Platform Plan</h2><p>The first six months are included. Paid managed service begins in month seven at ₦18,000 per month for Launch Edition and ₦24,000 per month for Business Edition. It supports the represented hosting, football-data infrastructure, AI infrastructure within fair-use limits, database/backend infrastructure, security maintenance, backups, updates and technical support. Major redesigns and custom integrations are outside routine managed service.</p>
<h2>9. Ownership and licence</h2><p>The client retains ownership of its logo and client-supplied content. A domain purchased and owned by the client remains the client’s property. Client subscriber/customer data belongs to the client subject to applicable law and infrastructure arrangements.</p><p>FABRO TECH LIMITED retains its reusable software framework, systems, source code, libraries, methodologies, tooling and platform intellectual property unless a separate written source-code transfer or buyout agreement says otherwise. The client receives the right to operate the delivered branded platform under the agreed service arrangement.</p>
<h2>10. Cancellation and termination</h2><p>A client may cancel future managed service by giving reasonable notice through the agreed contact channel. Access to managed hosting, maintenance and infrastructure may end after the paid service period. We do not promise unsupported portability or source-code transfer. Either party may terminate for material breach that is not remedied after reasonable notice, subject to accrued obligations and applicable law.</p>
<h2>11. Predictions and client operation</h2><p>The technology provides probabilistic information, not guaranteed results. The client must not advertise guaranteed profits or present FABRO TECH LIMITED as a bookmaker. The client remains responsible for its pricing, customers, marketing and lawful operation.</p>
</LegalDocument>}
