begin;
alter table public.consumer_subscription_events add column if not exists provider_reference text,add column if not exists occurred_at timestamptz,add column if not exists payload_digest text,add column if not exists previous_status public.consumer_subscription_status,add column if not exists resulting_status public.consumer_subscription_status,add column if not exists processing_result text not null default'pending',add column if not exists safe_diagnostic_code text;
create table public.consumer_subscription_lifecycle_audit(id uuid primary key default gen_random_uuid(),subscription_id uuid not null references public.consumer_subscriptions(id)on delete restrict,event_id uuid references public.consumer_subscription_events(id)on delete restrict,provider text not null,environment public.payment_environment not null,provider_event_reference text not null,previous_status public.consumer_subscription_status not null,resulting_status public.consumer_subscription_status not null,previous_entitlement public.consumer_entitlement_status not null,resulting_entitlement public.consumer_entitlement_status not null,occurred_at timestamptz not null,processed_at timestamptz not null default now(),metadata jsonb not null default'{}'::jsonb,unique(provider,environment,provider_event_reference));
create table public.consumer_subscription_reconciliation_runs(id uuid primary key default gen_random_uuid(),subscription_id uuid not null references public.consumer_subscriptions(id)on delete restrict,provider text not null,environment public.payment_environment not null,issue_code text not null,recommended_action text not null,applied boolean not null default false,checked_at timestamptz not null default now(),metadata jsonb not null default'{}'::jsonb);
create index consumer_subscription_events_ordering_idx on public.consumer_subscription_events(subscription_id,occurred_at desc);create index consumer_subscription_audit_subscription_idx on public.consumer_subscription_lifecycle_audit(subscription_id,processed_at desc);create index consumer_subscription_reconciliation_idx on public.consumer_subscription_reconciliation_runs(subscription_id,checked_at desc);
alter table public.consumer_subscription_lifecycle_audit enable row level security;alter table public.consumer_subscription_reconciliation_runs enable row level security;
revoke all on public.consumer_subscription_events,public.consumer_subscription_lifecycle_audit,public.consumer_subscription_reconciliation_runs from anon,authenticated;grant select on public.consumer_subscription_lifecycle_audit to authenticated;
create policy consumer_subscription_audit_own_read on public.consumer_subscription_lifecycle_audit for select to authenticated using(exists(select 1 from public.consumer_subscriptions s where s.id=subscription_id and(s.user_id=(select auth.uid())or public.is_admin())));
commit;
