begin;
create type public.payment_purpose as enum ('business_setup','consumer_subscription','managed_platform','client_subscriber_split');
create type public.payment_environment as enum ('test','live');
create type public.payment_subject_type as enum ('order','user','business_client','client_platform');
create type public.payment_transaction_state as enum ('initialized','pending','succeeded','failed','cancelled');
create type public.payment_price_kind as enum ('standard','promotional','current');
create type public.payment_billing_interval as enum ('one_time','monthly');

create table public.payment_products(id uuid primary key default gen_random_uuid(),product_key text not null unique,purpose public.payment_purpose not null,name text not null,active boolean not null default true,metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.payment_prices(id uuid primary key default gen_random_uuid(),product_id uuid not null references public.payment_products(id) on delete restrict,version integer not null check(version>0),kind public.payment_price_kind not null,amount_minor bigint not null check(amount_minor>0),currency text not null check(currency~'^[A-Z]{3}$'),billing_interval public.payment_billing_interval not null,active boolean not null default true,effective_from timestamptz not null,effective_until timestamptz,provider text,provider_environment public.payment_environment,provider_plan_reference text,metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(product_id,version),check(effective_until is null or effective_until>effective_from),check((provider_plan_reference is null and provider is null and provider_environment is null)or(provider_plan_reference is not null and provider is not null and provider_environment is not null)));
create table public.payment_customers(id uuid primary key default gen_random_uuid(),subject_type public.payment_subject_type not null,subject_id uuid not null,provider text not null,environment public.payment_environment not null,provider_customer_reference text not null,metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(provider,environment,provider_customer_reference),unique(subject_type,subject_id,provider,environment));
create trigger set_payment_products_updated_at before update on public.payment_products for each row execute function public.set_updated_at();create trigger set_payment_prices_updated_at before update on public.payment_prices for each row execute function public.set_updated_at();create trigger set_payment_customers_updated_at before update on public.payment_customers for each row execute function public.set_updated_at();

insert into public.payment_products(product_key,purpose,name) values('b2b-launch-setup','business_setup','Launch Edition setup'),('b2b-business-setup','business_setup','Business Edition setup'),('consumer-premium-monthly','consumer_subscription','Premium monthly'),('managed-launch-monthly','managed_platform','Launch Managed Platform'),('managed-business-monthly','managed_platform','Business Managed Platform');
insert into public.payment_prices(product_id,version,kind,amount_minor,currency,billing_interval,effective_from) select id,v.version,v.kind::public.payment_price_kind,v.amount_minor,'NGN',v.interval::public.payment_billing_interval,'2026-01-01T00:00:00Z'::timestamptz from public.payment_products cross join lateral(values case product_key when'b2b-launch-setup'then 1 when'b2b-business-setup'then 1 else 1 end,case when product_key like'b2b-%'then'standard'else'current'end,case product_key when'b2b-launch-setup'then 50000000 when'b2b-business-setup'then 100000000 when'consumer-premium-monthly'then 300000 when'managed-launch-monthly'then 1800000 else 2400000 end,case when product_key like'b2b-%'then'one_time'else'monthly'end))as v(version,kind,amount_minor,interval);
insert into public.payment_prices(product_id,version,kind,amount_minor,currency,billing_interval,effective_from) select id,2,'promotional',case product_key when'b2b-launch-setup'then 35000000 else 75000000 end,'NGN','one_time','2026-01-01T00:00:00Z' from public.payment_products where product_key in('b2b-launch-setup','b2b-business-setup');

alter table public.payment_transactions alter column order_id drop not null;
alter table public.payment_transactions add column purpose public.payment_purpose,add column subject_type public.payment_subject_type,add column subject_id uuid,add column environment public.payment_environment not null default 'test',add column product_id uuid references public.payment_products(id) on delete restrict,add column price_id uuid references public.payment_prices(id) on delete restrict,add column expected_amount_minor bigint,add column paid_amount_minor bigint,add column transaction_state public.payment_transaction_state not null default 'pending',add column verified_at timestamptz;
update public.payment_transactions set purpose='business_setup',subject_type='order',subject_id=order_id,expected_amount_minor=amount_minor,paid_amount_minor=case when status in('payment-verified','completed','success')then amount_minor else null end where purpose is null;
alter table public.payment_transactions alter column purpose set not null,alter column subject_type set not null,alter column subject_id set not null,alter column expected_amount_minor set not null;
alter table public.payment_transactions add constraint payment_transactions_expected_amount_positive check(expected_amount_minor>0),add constraint payment_transactions_paid_amount_nonnegative check(paid_amount_minor is null or paid_amount_minor>=0),add constraint payment_transactions_purpose_subject_check check((purpose='business_setup' and subject_type='order' and order_id=subject_id)or(purpose='consumer_subscription' and subject_type='user' and order_id is null)or(purpose in('managed_platform','client_subscriber_split')and subject_type='client_platform' and order_id is null));
alter table public.payment_transactions drop constraint if exists payment_transactions_provider_reference_key;
alter table public.payment_transactions add constraint payment_transactions_provider_environment_reference_key unique(provider,environment,reference);
create index payment_products_purpose_active_idx on public.payment_products(purpose,active);create index payment_prices_product_effective_idx on public.payment_prices(product_id,effective_from desc);create index payment_transactions_subject_idx on public.payment_transactions(purpose,subject_type,subject_id,created_at desc);
alter table public.payment_products enable row level security;alter table public.payment_prices enable row level security;alter table public.payment_customers enable row level security;
create policy payment_products_admin_read on public.payment_products for select to authenticated using(public.is_admin());create policy payment_prices_admin_read on public.payment_prices for select to authenticated using(public.is_admin());create policy payment_customers_own_read on public.payment_customers for select to authenticated using((subject_type='user' and subject_id=(select auth.uid()))or public.is_admin());
grant select on public.payment_products,public.payment_prices,public.payment_customers to authenticated;
commit;
