begin;
create type public.managed_platform_billing_status as enum('included_period','authorization_required','pending','active','past_due','cancelled','terminated');
create table public.managed_platform_billings(
 id uuid primary key default gen_random_uuid(),setup_order_id uuid not null references public.orders(id)on delete restrict,owner_user_id uuid not null references auth.users(id)on delete restrict,package_id text not null check(package_id in('launch','business')),product_key text not null check(product_key in('managed-launch-monthly','managed-business-monthly')),price_snapshot_id text not null,amount_minor bigint not null check(amount_minor in(1800000,2400000)),currency text not null default'NGN'check(currency='NGN'),billing_interval text not null default'monthly'check(billing_interval='monthly'),included_period_start timestamptz not null,included_period_end timestamptz not null,billing_status public.managed_platform_billing_status not null default'included_period',provider text check(provider is null or provider='paystack'),provider_environment public.payment_environment not null default'test',provider_customer_reference text,provider_subscription_reference text,authorization_reference text,current_period_start timestamptz,current_period_end timestamptz,next_billing_at timestamptz,cancel_at_period_end boolean not null default false,cancelled_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(setup_order_id),check(included_period_end=included_period_start+interval'6 months'),check((package_id='launch'and product_key='managed-launch-monthly'and amount_minor=1800000)or(package_id='business'and product_key='managed-business-monthly'and amount_minor=2400000)),check(provider_subscription_reference is null or provider_subscription_reference~'^SUB_[A-Za-z0-9]+$'),check(billing_status not in('active','past_due')or(provider='paystack'and provider_customer_reference is not null and provider_subscription_reference~'^SUB_[A-Za-z0-9]+$'))
);
create index managed_platform_billings_owner_status_idx on public.managed_platform_billings(owner_user_id,billing_status,included_period_end);
create unique index managed_platform_billings_provider_subscription_idx on public.managed_platform_billings(provider,provider_environment,provider_subscription_reference)where provider_subscription_reference is not null;
create trigger set_managed_platform_billings_updated_at before update on public.managed_platform_billings for each row execute function public.set_updated_at();
alter table public.managed_platform_billings enable row level security;
create policy managed_platform_billings_owner_read on public.managed_platform_billings for select to authenticated using(owner_user_id=(select auth.uid())or public.is_admin());
grant select on public.managed_platform_billings to authenticated;
revoke insert,update,delete on public.managed_platform_billings from public,anon,authenticated;
create or replace function public.establish_managed_platform_billing(p_order_id uuid,p_owner_user_id uuid,p_record_id uuid default gen_random_uuid())returns uuid language plpgsql security definer set search_path='' as $$declare v_order public.orders;v_existing uuid;v_product text;v_price text;v_amount bigint;begin if auth.role()<>'service_role'then raise exception'forbidden';end if;select*into v_order from public.orders where id=p_order_id for update;if not found or v_order.payment_purpose<>'business_setup'or v_order.order_status<>'paid'or v_order.paid_at is null or v_order.user_id is distinct from p_owner_user_id then raise exception'invalid_qualifying_order';end if;select id into v_existing from public.managed_platform_billings where setup_order_id=p_order_id;if found then return v_existing;end if;if v_order.package_id='launch'then v_product:='managed-launch-monthly';v_price:='managed-launch-monthly-v1';v_amount:=1800000;elsif v_order.package_id='business'then v_product:='managed-business-monthly';v_price:='managed-business-monthly-v1';v_amount:=2400000;else raise exception'invalid_package';end if;insert into public.managed_platform_billings(id,setup_order_id,owner_user_id,package_id,product_key,price_snapshot_id,amount_minor,included_period_start,included_period_end,billing_status)values(p_record_id,p_order_id,p_owner_user_id,v_order.package_id,v_product,v_price,v_amount,v_order.paid_at,v_order.paid_at+interval'6 months',case when now()<v_order.paid_at+interval'6 months'then'included_period'::public.managed_platform_billing_status else'authorization_required'::public.managed_platform_billing_status end)returning id into v_existing;return v_existing;end$$;
revoke all on function public.establish_managed_platform_billing(uuid,uuid,uuid)from public,anon,authenticated;grant execute on function public.establish_managed_platform_billing(uuid,uuid,uuid)to service_role;
create or replace function public.create_managed_platform_billing_for_paid_order()returns trigger language plpgsql security definer set search_path='' as $$begin if new.payment_purpose='business_setup'and new.order_status='paid'and new.paid_at is not null and new.user_id is not null and new.package_id in('launch','business')then insert into public.managed_platform_billings(setup_order_id,owner_user_id,package_id,product_key,price_snapshot_id,amount_minor,included_period_start,included_period_end,billing_status)values(new.id,new.user_id,new.package_id,case new.package_id when'launch'then'managed-launch-monthly'else'managed-business-monthly'end,case new.package_id when'launch'then'managed-launch-monthly-v1'else'managed-business-monthly-v1'end,case new.package_id when'launch'then 1800000 else 2400000 end,new.paid_at,new.paid_at+interval'6 months',case when now()<new.paid_at+interval'6 months'then'included_period'::public.managed_platform_billing_status else'authorization_required'::public.managed_platform_billing_status end)on conflict(setup_order_id)do nothing;end if;return new;end$$;
create trigger create_managed_platform_billing_after_payment after insert or update of order_status,paid_at on public.orders for each row execute function public.create_managed_platform_billing_for_paid_order();
insert into public.managed_platform_billings(setup_order_id,owner_user_id,package_id,product_key,price_snapshot_id,amount_minor,included_period_start,included_period_end,billing_status)select id,user_id,package_id,case package_id when'launch'then'managed-launch-monthly'else'managed-business-monthly'end,case package_id when'launch'then'managed-launch-monthly-v1'else'managed-business-monthly-v1'end,case package_id when'launch'then 1800000 else 2400000 end,paid_at,paid_at+interval'6 months',case when now()<paid_at+interval'6 months'then'included_period'::public.managed_platform_billing_status else'authorization_required'::public.managed_platform_billing_status end from public.orders where payment_purpose='business_setup'and order_status='paid'and paid_at is not null and user_id is not null and package_id in('launch','business')on conflict(setup_order_id)do nothing;
commit;
