import type{Metadata}from"next";import Link from"next/link";import{SiteHeader}from"@/components/site-header";import{SiteFooter}from"@/components/site-footer";import{SectionHeading}from"@/components/section-heading";import{BusinessInquiryForm}from"@/components/business-inquiry-form";import{FloatingWhatsApp,WhatsAppLink}from"@/components/whatsapp-cta";import{brand}from"@/config/brand";import{businessPackages,commercialJourney,formatNaira,founderOffer,managedPlatformPlan}from"@/config/pricing";
export const metadata:Metadata={title:"Launch Your AI Football Prediction Platform",description:`Build a branded AI football prediction website and launch your football prediction business with ${brand.companyName} and ${brand.siteName}.`,openGraph:{title:"Launch Your AI Football Prediction Platform",description:`Professional football prediction websites configured and managed by ${brand.companyName}.`,images:["/og.png"]}};
const comparison=[["Development time","Often months of coordination","A faster, guided launch"],["AI integration","Sourced and managed separately","Included within the managed platform"],["Football data","Separate provider setup","Infrastructure configured as part of delivery"],["Infrastructure & deployment","Multiple technical decisions","One Managed Platform Plan"],["Maintenance & security","Ongoing internal responsibility","Included within managed technical operations"],["Updates & support","Separate vendors or retainers","One managed relationship"]];
const process=[["Choose Your Edition","Select Starter or Business Edition."],["Initial Payment","Project setup begins after payment is confirmed."],["Submit Your Brand","Provide your platform name, logo, colours, contacts, domain and commercial information."],["Build & Configuration",`${brand.companyName} configures the platform around your brand and selected package.`],["Review & Testing","Review the platform and complete agreed corrections."],["Domain Connection & Launch","Connect the final platform to your domain and launch."]];
const trust=["Built and managed by FABRO TECH LIMITED","Professional deployment","Managed Platform service","30 Top Football Leagues & Competitions capability","AI-powered intelligence architecture","Mobile-responsive platform","Security and technical maintenance","Responsible gaming safeguards"];
const faqs=[
 ["How long does it take to launch my platform?","Starter Edition projects are typically delivered within 7–14 working days after the initial payment and receipt of the required branding/content materials. Business Edition projects typically require 14–21 working days depending on the selected modules and custom requirements."],
 ["Do I own my domain?","Your platform operates on your own domain, or a domain connected for your brand, subject to the agreed package and domain arrangement."],
 ["Do I need to arrange platform infrastructure myself?","No. The Managed Platform Plan supports the infrastructure required to operate your platform, and the first 6 months are included with your setup."],
 ["What happens after the first 6 months?",`Paid Managed Platform service begins in month 7: ${formatNaira(businessPackages[0].managedPlatformMonthly)}/month for Starter Edition and ${formatNaira(businessPackages[1].managedPlatformMonthly)}/month for Business Edition.`],
 ["What does the Managed Platform Plan cover?",`${managedPlatformPlan.description} This includes ${managedPlatformPlan.includes.join(", ")}. Fair-use limits and the agreed service scope apply.`],
 ["Are all 30 competitions live on 9ja Football AI now?","No. The client-platform capability is designed for 30 top football leagues and competitions, but the live football-data provider is not active on the current 9ja Football AI demonstration platform."],
 ["Can I set my own subscription prices?","Yes. Your platform can be configured around your business and preferred subscription pricing."],
 ["Will my website look exactly like 9ja Football AI?","No. 9ja Football AI demonstrates the technology and product capability. Each client platform is configured around the client's branding, identity and agreed requirements."],
 ["Can I request additional features?","Yes. Additional custom features and integrations can be discussed and may require a separate quotation."],
 ["Do you guarantee winning predictions?","No. The platform provides AI-assisted football analysis and predictions based on available data. Sports outcomes cannot be guaranteed."],
 ["Can I speak to someone before buying?",`Yes. Chat with ${brand.companyName} on WhatsApp at ${brand.contactPhone}.`],
];
export default function SalesPage(){return <div className="commercial-page"><SiteHeader/><main><section className="sales-hero"><div className="orb orb-one"/><div className="grid-lines"/><div className="container sales-hero-grid"><div><span className="eyebrow">For football creators and entrepreneurs</span><h1>Launch Your Own AI Football Intelligence Business</h1><p>Purchase the setup and build of your own branded AI-powered football intelligence business, with the first six months of managed platform service included.</p><div className="hero-actions"><a className="button" href="#packages">Start Your Platform <span>→</span></a><WhatsAppLink className="button button-ghost"/><Link className="sales-demo-link" href="/#today-matches">See 9ja Football AI in Action →</Link></div></div><div className="sales-hero-card"><span>Professionally configured for you</span>{["Your brand","Your domain","Your subscribers","Your pricing","30 Top Football Leagues & Competitions capability"].map(item=><b key={item}>✓ {item}</b>)}<small>Live coverage for all 30 competitions is not active on this demo.</small></div></div></section>
<section className="founder-offer"><div className="container"><div><span className="eyebrow">Founder launch pricing</span><h2>Secure Founder Pricing Before It Ends</h2><p>{founderOffer.disclaimer}</p></div><div className="offer-prices">{businessPackages.map(item=><div key={item.id}><span>{item.name}</span><del>{formatNaira(item.standardPrice)}</del><b>{formatNaira(item.founderPrice)}</b></div>)}</div></div></section>
<section className="section package-section" id="packages"><div className="container"><SectionHeading eyebrow="Business packages" title="Choose the platform that fits your ambition" copy="Both editions purchase the setup of your own branded AI-powered football intelligence business and include the first 6 months of managed platform service." align="center"/><div className="business-package-grid">{businessPackages.map((item,index)=><article key={item.id} className={index===1?"business-package featured-business-package":"business-package"}><div className="package-head"><span>{item.name}</span>{index===1&&<em>Business</em>}<h2>{item.audience}</h2><div><del>Standard {formatNaira(item.standardPrice)}</del><b>{formatNaira(item.founderPrice)}</b><small>Founder Launch Offer</small></div></div><ul>{item.features.map(feature=><li key={feature}>{feature}</li>)}</ul>{"capabilityNote"in item&&<p className="capability-note">{item.capabilityNote}</p>}<div className="delivery-card"><span>Typical Delivery</span><b>{item.typicalDelivery}</b><p>{item.deliveryNote}</p></div><div className="care-price"><span>Managed Platform Plan · first 6 months included</span><b>{formatNaira(item.managedPlatformMonthly)}/month from month 7</b></div><a className={index===1?"button":"button button-ghost"} href="#inquiry">Get {item.name}<span>→</span></a><div className="package-whatsapp"><span>Questions before you proceed?</span><WhatsAppLink message={item.whatsappMessage} label="Chat with us on WhatsApp" className="text-link"/></div></article>)}</div><p className="delivery-disclaimer">{commercialJourney.deliveryDisclaimer}</p></div></section>
<section className="section care-section"><div className="container care-layout"><div><SectionHeading eyebrow="First 6 months included" title="A managed platform—not another technical burden." copy="Paid Managed Platform service begins in month 7 and contributes toward the ongoing infrastructure required to operate your platform."/><p>{managedPlatformPlan.description}</p><p className="care-exclusion">{managedPlatformPlan.exclusions}</p></div><div className="care-grid">{managedPlatformPlan.includes.map((item,index)=><div key={item}><span>{String(index+1).padStart(2,"0")}</span><b>{item}</b></div>)}</div></div></section>
<section className="section comparison-section"><div className="container"><SectionHeading eyebrow="A more direct route" title="Why not build everything from scratch?" copy="Bring the moving parts together through one professionally managed solution." align="center"/><div className="comparison-table" role="table" aria-label="Custom development and 9ja Football AI-powered platform comparison"><div className="comparison-row comparison-head" role="row"><b>Area</b><b>Custom Development</b><b>Powered by 9ja Football AI</b></div>{comparison.map(([area,custom,managed])=><div className="comparison-row" role="row" key={area}><strong>{area}</strong><span>{custom}</span><span>{managed}</span></div>)}</div></div></section>
<section className="section onboarding-section"><div className="container"><SectionHeading eyebrow="How delivery works" title="A clear route from edition to launch" copy="Your timeline begins after payment and receipt of the materials needed to configure your platform." align="center"/><div className="delivery-ranges">{businessPackages.map(item=><div key={item.id}><span>{item.name}</span><b>{item.typicalDelivery}</b></div>)}</div><div className="onboarding-grid">{process.map(([title,copy],index)=><article key={title}><span>{index+1}</span><h3>{title}</h3><p>{copy}</p>{index<process.length-1&&<i>→</i>}</article>)}</div></div></section>
<section className="section requirements-section"><div className="container requirements-layout"><div><SectionHeading eyebrow="What we need from you" title="Prepare the essentials for a smooth delivery" copy="Timely, complete materials help us begin configuration and keep your project moving."/><div className="requirements-grid">{commercialJourney.clientRequirements.map(item=><span key={item}>✓ {item}</span>)}</div></div><aside><span className="eyebrow">Immediately after purchase</span><h2>Onboarding begins with your requirements.</h2><p>After your order is confirmed, {brand.companyName} will send your onboarding requirements and begin platform configuration once the necessary materials are received.</p><small>This is a guided process; automated onboarding is not currently used.</small></aside></div></section>
<section className="section sales-trust-section"><div className="container"><SectionHeading eyebrow="Professional foundations" title="Built for a credible football business" copy="Practical technology, managed delivery and responsible product safeguards—without inflated promises." align="center"/><div className="sales-trust-grid">{trust.map((item,index)=><div key={item}><span>{String(index+1).padStart(2,"0")}</span><b>{item}</b></div>)}</div></div></section>
<section className="section whatsapp-section"><div className="container whatsapp-panel"><div><span className="eyebrow">Have questions before you decide?</span><h2>Ask first. Decide with clarity.</h2><p>Choosing the right platform is an important business decision. Chat directly with {brand.companyName} on WhatsApp about features, branding, delivery, the Managed Platform Plan, integrations or your requirements.</p><small>No pressure. Ask your questions before you decide.</small></div><div><WhatsAppLink/><b>{brand.contactPhone}</b></div></div></section>
<section className="section sales-faq"><div className="container"><SectionHeading eyebrow="Buyer questions" title="Everything you should know before proceeding" copy="Clear answers about delivery, ownership, managed infrastructure and platform capability."/><div className="faq-list">{faqs.map(([question,answer])=><details key={question}><summary>{question}<span aria-hidden="true">+</span></summary><p>{answer}</p></details>)}</div></div></section>
<section className="section inquiry-section" id="inquiry"><div className="container"><SectionHeading eyebrow="Start your platform" title="Tell us about your football brand" copy="Review the prepared requirements form or speak with platform sales directly on WhatsApp."/><BusinessInquiryForm/></div></section></main><FloatingWhatsApp/><SiteFooter/></div>}
