import type{Metadata}from"next";import Link from"next/link";import{SiteHeader}from"@/components/site-header";import{SiteFooter}from"@/components/site-footer";import{SectionHeading}from"@/components/section-heading";import{BusinessInquiryForm}from"@/components/business-inquiry-form";import{FloatingWhatsApp,WhatsAppLink}from"@/components/whatsapp-cta";import{brand}from"@/config/brand";import{getSiteUrl}from"@/config/site";import{businessPackages,commercialJourney,formatNaira,founderOffer,managedPlatformPlan}from"@/config/pricing";
export const metadata:Metadata={title:"Launch Your Own AI Football Intelligence Platform",description:`Launch a branded AI-powered football intelligence platform for your audience with technology, configuration, deployment and managed infrastructure from ${brand.companyName}.`,alternates:{canonical:`${getSiteUrl()}/sales`},openGraph:{title:"Launch Your Own AI Football Intelligence Platform | 9jaFootballAI",description:`Launch a branded AI-powered football intelligence platform for your audience with technology, configuration, deployment and managed infrastructure from ${brand.companyName}.`,url:`${getSiteUrl()}/sales`,images:[{url:"/og-sales.png",width:1200,height:630,alt:"Launch Your Own AI Football Intelligence Platform — Powered by 9jaFootballAI Technology"}]},twitter:{card:"summary_large_image",title:"Launch Your Own AI Football Intelligence Platform | 9jaFootballAI",description:`Branded AI football intelligence platform technology from ${brand.companyName}.`,images:["/og-sales.png"]}};
const comparison=[["Development time","Often months of coordination","A faster, guided launch"],["AI integration","Sourced and managed separately","Included within the managed platform"],["Football data","Separate provider setup","Infrastructure configured as part of delivery"],["Infrastructure & deployment","Multiple technical decisions","One Managed Platform Plan"],["Maintenance & security","Ongoing internal responsibility","Included within managed technical operations"],["Updates & support","Separate vendors or retainers","One managed relationship"]];
const process=[["Choose Your Edition","Select Launch or Business Edition."],["Initial Payment","Project setup begins after payment is confirmed."],["Submit Your Brand","Provide your platform name, logo, colours, contacts, domain and commercial information."],["Build & Configuration",`${brand.companyName} configures the platform around your brand and selected package.`],["Review & Testing","Review the platform and complete agreed corrections."],["Domain Connection & Launch","Connect the final platform to your domain and launch."]];
const trust=["Built and managed by FABRO TECH LIMITED","Professional deployment","Managed Platform service","30 Top Football Leagues & Competitions capability","AI-powered intelligence architecture","Mobile-responsive platform","Security and technical maintenance","Responsible gaming safeguards"];
const setupGbp={launch:"£200",business:"£425"}as const;
const monthlyGbp={launch:"£10",business:"£15"}as const;
const faqs=[
 ["How long does it take to launch my platform?","Launch Edition projects are typically delivered within 7–14 working days after the initial payment and receipt of the required branding/content materials. Business Edition projects typically require 14–21 working days depending on the selected modules and custom requirements."],
 ["Do I own my domain?","Your platform operates on your own domain, or a domain connected for your brand, subject to the agreed package and domain arrangement."],
 ["Do I need to arrange platform infrastructure myself?","No. The Managed Platform Plan supports the infrastructure required to operate your platform, and the first 6 months are included with your setup."],
 ["What happens after the first 6 months?",`Paid Managed Platform service begins in month 7: ${formatNaira(businessPackages[0].managedPlatformMonthly)}/month for Launch Edition and ${formatNaira(businessPackages[1].managedPlatformMonthly)}/month for Business Edition.`],
 ["What does the Managed Platform Plan cover?",`${managedPlatformPlan.description} This includes ${managedPlatformPlan.includes.join(", ")}. Fair-use limits and the agreed service scope apply.`],
 ["Are all 30 competitions live on 9ja Football AI now?","No. Client platforms support configurable competition coverage, while current 9ja Football AI coverage expands as competitions and provider services are enabled."],
 ["Can I set my own subscription prices?","Yes. You set the prices charged to your own audience. The Managed Platform Plan is the technology-management fee paid to FABRO TECH LIMITED after the included six-month period."],
 ["Will my website look exactly like 9ja Football AI?","No. 9jaFootballAI is the flagship platform and technology showcase. Each client platform is configured around the client's branding, identity and agreed requirements."],
 ["Can I request additional features?","Yes. Additional custom features and integrations can be discussed and may require a separate quotation."],
 ["Do you guarantee winning predictions?","No. The platform provides AI-assisted football analysis and predictions based on available data. Sports outcomes cannot be guaranteed."],
 ["Can I speak to someone before buying?",`Yes. Chat with ${brand.companyName} on WhatsApp at ${brand.contactPhone}.`],
];
export default function SalesPage(){return <div className="commercial-page"><SiteHeader/><main><section className="sales-hero"><div className="orb orb-one"/><div className="grid-lines"/><div className="container sales-hero-grid"><div><span className="eyebrow">For football creators and entrepreneurs</span><h1>Launch Your Own AI Football Intelligence Business</h1><p>Get a professionally built football intelligence platform powered by the same technology behind 9jaFootballAI. We configure your branding, platform structure, subscriber access and deployment so you can launch under your own identity.</p><div className="hero-actions"><WhatsAppLink className="button"/><a className="button button-ghost" href="#packages">Compare Packages <span>→</span></a><Link className="sales-demo-link" href="/#today-matches">See the Technology in Action →</Link></div></div><div className="sales-hero-card"><span>Professionally configured for you</span>{["Your brand","Your domain","Your subscribers","Your pricing","30 Top Football Leagues & Competitions capability"].map(item=><b key={item}>✓ {item}</b>)}<small>Coverage is configured competition by competition and expands as provider services are enabled.</small></div></div></section>
<section className="section b2b-audience"><div className="container"><SectionHeading eyebrow="Who it is for" title="Built for Football Businesses and Communities" copy="For football tipster brands, sports media publishers, Telegram and WhatsApp communities, social football brands, sports entrepreneurs, analysis websites and established audiences ready for a subscription platform." align="center"/><div className="b2b-value-grid"><article><h3>What You Receive</h3><p>A branded, mobile-responsive football intelligence website with your identity, domain support, user accounts, subscriber access, match-centre experience, platform onboarding and managed deployment.</p></article><article><h3>Build Your Own Subscription Revenue</h3><p>You set the prices charged to your audience. Launch Edition supports Free Access plus one paid tier. Business Edition supports Free Access plus two paid tiers for standard and higher-value memberships.</p></article><article><h3>See the Technology in Action</h3><p>9jaFootballAI is our flagship football intelligence platform. Client platforms use the same technology foundation with their own branding, domain, subscription structure and business identity.</p></article></div></div></section><section className="section b2b-control"><div className="container b2b-control-grid"><article><span className="eyebrow">You control</span><h2>Your customer-facing business</h2><p>Your brand identity, agreed domain, subscriber relationship, public membership names and the prices you charge your audience remain under your commercial direction, subject to the Business Terms.</p></article><article><span className="eyebrow">We manage</span><h2>The technology foundation</h2><p>FABRO TECH LIMITED manages the platform software, deployment, infrastructure, maintenance, updates and agreed third-party technology integrations.</p></article><article><span className="eyebrow">External services</span><h2>Some costs may be separate</h2><p>Domain registration or renewal, premium data plans, payment-provider transaction charges, premium email services and optional integrations may attract separate third-party costs.</p></article></div></section><section className="founder-offer"><div className="container"><div><span className="eyebrow">Founder launch pricing</span><h2>Secure Founder Pricing Before It Ends</h2><p>{founderOffer.disclaimer}</p></div><div className="offer-prices">{businessPackages.map(item=><div key={item.id}><span>{item.name}</span><del>{formatNaira(item.standardPrice)}</del><b>{formatNaira(item.founderPrice)} (approx. {setupGbp[item.id]})</b></div>)}</div></div></section>
<section className="section package-section" id="packages"><div className="container"><SectionHeading eyebrow="Business packages" title="Choose the platform that fits your ambition" copy="Both editions purchase the setup of your own branded AI-powered football intelligence business and include the first 6 months of managed platform service." align="center"/><div className="business-package-grid">{businessPackages.map((item,index)=><article key={item.id} className={index===1?"business-package featured-business-package":"business-package"}><div className="package-head"><span>{item.name}</span>{index===1&&<em>Business</em>}<h2>{item.audience}</h2><div><del>Standard {formatNaira(item.standardPrice)}</del><b>{formatNaira(item.founderPrice)} (approx. {setupGbp[item.id]})</b><small>Founder Launch Offer</small></div></div><ul>{item.features.map(feature=><li key={feature}>{feature}</li>)}</ul>{"capabilityNote"in item&&<p className="capability-note">{item.capabilityNote}</p>}<div className="delivery-card"><span>Typical Delivery</span><b>{item.typicalDelivery}</b><p>{item.deliveryNote}</p></div><div className="care-price"><span>Managed Platform Plan · first 6 months included</span><b>{formatNaira(item.managedPlatformMonthly)}/month (approx. {monthlyGbp[item.id]}/month) from month 7</b></div><a className={index===1?"button":"button button-ghost"} href="#inquiry">Get {item.name}<span>→</span></a><div className="package-whatsapp"><span>Questions before you proceed?</span><WhatsAppLink message={item.whatsappMessage} label="Chat with us on WhatsApp" className="text-link"/></div></article>)}</div><p className="delivery-disclaimer">GBP amounts are approximate and provided for international reference. Actual conversion may vary depending on exchange rates and your payment provider.</p><p className="delivery-disclaimer">{commercialJourney.deliveryDisclaimer}</p></div></section>
<section className="section care-section"><div className="container care-layout"><div><SectionHeading eyebrow="First 6 months included" title="A managed platform—not another technical burden." copy="Paid Managed Platform service begins in month 7 and contributes toward the ongoing infrastructure required to operate your platform."/><p>{managedPlatformPlan.description}</p><p className="care-exclusion">{managedPlatformPlan.exclusions}</p></div><div className="care-grid">{managedPlatformPlan.includes.map((item,index)=><div key={item}><span>{String(index+1).padStart(2,"0")}</span><b>{item}</b></div>)}</div></div></section>
<section className="section comparison-section"><div className="container"><SectionHeading eyebrow="A more direct route" title="Why not build everything from scratch?" copy="Bring the moving parts together through one professionally managed solution." align="center"/><div className="comparison-table" role="table" aria-label="Custom development and 9ja Football AI-powered platform comparison"><div className="comparison-row comparison-head" role="row"><b>Area</b><b>Custom Development</b><b>Powered by 9ja Football AI</b></div>{comparison.map(([area,custom,managed])=><div className="comparison-row" role="row" key={area}><strong>{area}</strong><span>{custom}</span><span>{managed}</span></div>)}</div></div></section>
<section className="section onboarding-section"><div className="container"><SectionHeading eyebrow="How delivery works" title="A clear route from edition to launch" copy="Your timeline begins after payment and receipt of the materials needed to configure your platform." align="center"/><div className="delivery-ranges">{businessPackages.map(item=><div key={item.id}><span>{item.name}</span><b>{item.typicalDelivery}</b></div>)}</div><div className="onboarding-grid">{process.map(([title,copy],index)=><article key={title}><span>{index+1}</span><h3>{title}</h3><p>{copy}</p>{index<process.length-1&&<i>→</i>}</article>)}</div></div></section>
<section className="section requirements-section"><div className="container requirements-layout"><div><SectionHeading eyebrow="What we need from you" title="Prepare the essentials for a smooth delivery" copy="Timely, complete materials help us begin configuration and keep your project moving."/><div className="requirements-grid">{commercialJourney.clientRequirements.map(item=><span key={item}>✓ {item}</span>)}</div></div><aside><span className="eyebrow">Immediately after purchase</span><h2>Onboarding begins with your requirements.</h2><p>After your order is confirmed, {brand.companyName} will send your onboarding requirements and begin platform configuration once the necessary materials are received.</p><small>Onboarding is guided directly by our team.</small></aside></div></section>
<section className="section sales-trust-section"><div className="container"><SectionHeading eyebrow="Professional foundations" title="Built for a credible football business" copy="Practical technology, managed delivery and responsible product safeguards—without inflated promises." align="center"/><div className="sales-trust-grid">{trust.map((item,index)=><div key={item}><span>{String(index+1).padStart(2,"0")}</span><b>{item}</b></div>)}</div></div></section>
<section className="section whatsapp-section"><div className="container whatsapp-panel"><div><span className="eyebrow">Have questions before you decide?</span><h2>Ask first. Decide with clarity.</h2><p>Choosing the right platform is an important business decision. Chat directly with {brand.companyName} on WhatsApp about features, branding, delivery, the Managed Platform Plan, integrations or your requirements.</p><small>No pressure. Ask your questions before you decide.</small></div><div><WhatsAppLink/></div></div></section>
<section className="section sales-faq"><div className="container"><SectionHeading eyebrow="Buyer questions" title="Everything you should know before proceeding" copy="Clear answers about delivery, ownership, managed infrastructure and platform capability."/><div className="faq-list">{faqs.map(([question,answer])=><details key={question}><summary>{question}<span aria-hidden="true">+</span></summary><p>{answer}</p></details>)}</div></div></section>
<section className="section inquiry-section" id="inquiry"><div className="container"><SectionHeading eyebrow="Start your platform" title="Ready to discuss your platform?" copy="Prepare the essentials and speak directly with platform sales on WhatsApp."/><BusinessInquiryForm/></div></section></main><FloatingWhatsApp/><SiteFooter/></div>}
